// Copyright 2025 the Fearless_SIMD Authors
// SPDX-License-Identifier: Apache-2.0 OR MIT

// This file is automatically generated by `fearless_simd_core_gen`.
// Its template can be found in `fearless_simd_core/gen/templates`.

//! The x86-64-v1 microarchitecture level.

use crate::{TargetFeatureToken, trampoline};

use core::fmt::Debug;

// TODO: Level specific docs?
/// A token indicating that the current CPU has the x86-64-v1 microarchitecture level.
///
/// For more details on the microarchitecture levels, see
/// <https://en.wikipedia.org/wiki/X86-64#Microarchitecture_levels>.
///
/// # Example
///
/// This can be used to [`trampoline!`] into functions like:
///
/// ```rust
/// #[cfg(any(target_arch = "x86", target_arch = "x86_64"))]
/// #[target_feature(enable = "fxsr,sse2")]
/// fn uses_x86_64_v1() {
///     // ...
/// }
/// ```
///
/// This struct internally contains only the minimal features required to enable this level.
/// This is done to ensure that the fewest target features are checked.
/// However, it can be turned into any target feature it implies using the from impls.
#[derive(Copy, Clone, Hash, PartialEq, Eq)]
pub struct V1 {
    /// The contained proof that `fxsave + fxrstor` is available.
    pub fxsr: crate::x86::v1::Fxsr,
    /// The contained proof that SSE2 is available.
    pub sse2: crate::x86::v1::Sse2,
    // This struct explicitly is not non_exhaustive, because it is
    // completely safe to construct from the fields.
}

impl Debug for V1 {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, r#"x86-64-v1 enabled."#)
    }
}

// Safety: This token can only be constructed if you have proofs that all the requisite
// target features are enabled.
unsafe impl TargetFeatureToken for V1 {
    const FEATURES: &[&str] = &["fxsr", "sse", "sse2"];

    #[inline(always)]
    fn vectorize<R>(self, f: impl FnOnce() -> R) -> R {
        // We use the explicitly written out form here as validation that the set of
        // features we've created correctly mapes to the target feature string.
        trampoline!([crate::x86::v1::Fxsr = self.fxsr, crate::x86::v1::Sse2 = self.sse2] => "fxsr,sse2", <(R)> fn<(R)>(f: impl FnOnce() -> R = f) -> R { f() })
    }
}

impl V1 {
    #[cfg(feature = "std")]
    /// Create a new token if the x86-64-v1 target feature is detected as enabled.
    ///
    /// This does not do any caching internally, although note that the standard
    /// library does internally cache the features it detects.
    // TODO: Consider a manual override feature/env var?
    pub fn try_new() -> Option<Self> {
        Some(Self {
            fxsr: crate::x86::v1::Fxsr::try_new()?,
            sse2: crate::x86::v1::Sse2::try_new()?,
        })
    }

    #[target_feature(enable = "fxsr,sse2")]
    /// Create a new token for the x86-64-v1 microarchitecture level.
    ///
    /// This method is useful to get a new token if you have an external proof that
    /// x86-64-v1 is available. This could happen if you are in a target feature
    /// function called by an external library user.
    ///
    /// # Safety
    ///
    /// No conditions other than those inherited from the target feature attribute,
    /// i.e. that the "fxsr,sse2" target feature is available.
    pub fn new() -> Self {
        Self {
            fxsr: crate::x86::v1::Fxsr::new(),
            sse2: crate::x86::v1::Sse2::new(),
        }
    }
}
// TODO: From impls to convert into lower x86 versions.

impl From<V1> for crate::x86::v1::Fxsr {
    fn from(value: V1) -> Self {
        // This serves as a correctness check of the implicitly enabled features.
        trampoline!([V1 = value] => "fxsr,sse2", fn() -> crate::x86::v1::Fxsr { crate::x86::v1::Fxsr::new() })
    }
}

impl From<V1> for crate::x86::v1::Sse {
    fn from(value: V1) -> Self {
        // This serves as a correctness check of the implicitly enabled features.
        trampoline!([V1 = value] => "fxsr,sse2", fn() -> crate::x86::v1::Sse { crate::x86::v1::Sse::new() })
    }
}

impl From<V1> for crate::x86::v1::Sse2 {
    fn from(value: V1) -> Self {
        // This serves as a correctness check of the implicitly enabled features.
        trampoline!([V1 = value] => "fxsr,sse2", fn() -> crate::x86::v1::Sse2 { crate::x86::v1::Sse2::new() })
    }
}

const _: () = {
    assert!(
        core::mem::size_of::<V1>() == 0,
        "Target feature tokens should be zero sized."
    );
};
