// Copyright 2026 the Fearless_SIMD Authors
// SPDX-License-Identifier: Apache-2.0 OR MIT

// This file is autogenerated by fearless_simd_gen

#![doc = "Access to intrinsics on `aarch64`."]
mod neon;
pub use neon::Neon;
