// Copyright 2025 the Fearless_SIMD Authors
// SPDX-License-Identifier: Apache-2.0 OR MIT

// This file is automatically generated by `fearless_simd_core_gen`.
// Its template can be found in `fearless_simd_core/gen/templates`.
//! The SSSE3 target feature.

use crate::{TargetFeatureToken, trampoline};

use core::fmt::Debug;

/// [SSSE3] --- Supplemental Streaming<abbr title="Single Instruction Multiple Data">SIMD</abbr>Extensions 3
///
/// [SSSE3]: https://en.wikipedia.org/wiki/SSSE3
///
/// A token indicating that the current CPU has the `ssse3` target feature.
///
/// # Example
///
/// This can be used to [`trampoline!`] into functions like:
///
/// ```rust
/// #[cfg(any(target_arch = "x86", target_arch = "x86_64"))]
/// #[target_feature(enable = "ssse3")]
/// fn uses_ssse3() {
///     // ...
/// }
/// ```
#[derive(Copy, Clone, Hash, PartialEq, Eq)]
pub struct SupplementalSse3 {
    // We don't use non_exhaustive because we don't want this struct to be constructible.
    // in different modules in this crate.
    _private: (),
}

impl Debug for SupplementalSse3 {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, r#""ssse3" enabled."#)
    }
}

// Safety: This token can only be constructed if you have proof that all the requisite
// target feature is enabled.
unsafe impl TargetFeatureToken for SupplementalSse3 {
    const FEATURES: &[&str] = &["ssse3", "sse", "sse2", "sse3"];

    #[inline(always)]
    fn vectorize<R>(self, f: impl FnOnce() -> R) -> R {
        // Because we need the safety check to be eagerly evaluated, it uses an constant item.
        // This means we can't use `Self = self` here, unfortunately.
        trampoline!([SupplementalSse3 = self] => "ssse3", <(R)> fn<(R)>(f: impl FnOnce() -> R = f) -> R { f() })
    }
}

impl SupplementalSse3 {
    #[cfg(feature = "std")]
    /// Create a new token if the `"ssse3"` target feature is detected as enabled.
    ///
    /// This does not do any caching internally, although note that the standard
    /// library does internally cache the features it detects.
    // TODO: Consider a manual override feature/env var?
    pub fn try_new() -> Option<Self> {
        // Feature flag required to make docs compile.
        // TODO: Extract into a (private) crate::x86::is_x86_feature_detected?
        #[cfg(any(target_arch = "x86", target_arch = "x86_64"))]
        if std::arch::is_x86_feature_detected!("ssse3") {
            // Safety: The required CPU feature was detected.
            unsafe { Some(Self::new()) }
        } else {
            None
        }
    }

    #[target_feature(enable = "ssse3")]
    /// Create a new token for the "ssse3" target feature.
    ///
    /// This method is useful to get a new token if you have an external proof that
    /// SSSE3 is available. This could happen if you are in a target feature
    /// function called by an external library user.
    ///
    /// # Safety
    ///
    /// No conditions other than those inherited from the target feature attribute,
    /// i.e. that the "ssse3" target feature is available.
    ///
    /// [implicitly enables]: https://doc.rust-lang.org/beta/reference/attributes/codegen.html?highlight=implicitly%20enabled#r-attributes.codegen.target_feature.safety-restrictions
    pub fn new() -> Self {
        Self { _private: () }
    }
}

impl From<SupplementalSse3> for crate::x86::sse::Sse {
    fn from(value: SupplementalSse3) -> Self {
        // This also serves as a correctness check of the implicitly enabled features.
        trampoline!([SupplementalSse3 = value] => "ssse3", fn() -> crate::x86::sse::Sse { crate::x86::sse::Sse::new() })
    }
}

impl From<SupplementalSse3> for crate::x86::sse::Sse2 {
    fn from(value: SupplementalSse3) -> Self {
        // This also serves as a correctness check of the implicitly enabled features.
        trampoline!([SupplementalSse3 = value] => "ssse3", fn() -> crate::x86::sse::Sse2 { crate::x86::sse::Sse2::new() })
    }
}

impl From<SupplementalSse3> for crate::x86::sse::Sse3 {
    fn from(value: SupplementalSse3) -> Self {
        // This also serves as a correctness check of the implicitly enabled features.
        trampoline!([SupplementalSse3 = value] => "ssse3", fn() -> crate::x86::sse::Sse3 { crate::x86::sse::Sse3::new() })
    }
}

const _: () = {
    assert!(
        core::mem::size_of::<SupplementalSse3>() == 0,
        "Target feature tokens should be zero sized."
    );
};
