// Copyright 2025 the Fearless_SIMD Authors
// SPDX-License-Identifier: Apache-2.0 OR MIT

// This file is automatically generated by `fearless_simd_core_gen`.
// Its template can be found in `fearless_simd_core/gen/templates`.

//! The x86-64-v4 microarchitecture level.

use crate::{TargetFeatureToken, trampoline};

use core::fmt::Debug;

// TODO: Level specific docs?
/// A token indicating that the current CPU has the x86-64-v4 microarchitecture level.
///
/// For more details on the microarchitecture levels, see
/// <https://en.wikipedia.org/wiki/X86-64#Microarchitecture_levels>.
///
/// # Example
///
/// This can be used to [`trampoline!`] into functions like:
///
/// ```rust
/// #[cfg(any(target_arch = "x86", target_arch = "x86_64"))]
/// #[target_feature(enable = "avx512bw,avx512cd,avx512dq,avx512vl,bmi1,bmi2,cmpxchg16b,fxsr,lzcnt,movbe,popcnt,xsave")]
/// fn uses_x86_64_v4() {
///     // ...
/// }
/// ```
///
/// This struct internally contains only the minimal features required to enable this level.
/// This is done to ensure that the fewest target features are checked.
/// However, it can be turned into any target feature it implies using the from impls.
#[derive(Copy, Clone, Hash, PartialEq, Eq)]
pub struct V4 {
    /// The contained proof that AVX512-BW is available.
    pub avx512bw: crate::x86::v4::Avx512bw,
    /// The contained proof that AVX512-CD is available.
    pub avx512cd: crate::x86::v4::Avx512cd,
    /// The contained proof that AVX512-DQ is available.
    pub avx512dq: crate::x86::v4::Avx512dq,
    /// The contained proof that AVX512-VL is available.
    pub avx512vl: crate::x86::v4::Avx512vl,
    /// The contained proof that  1 is available.
    pub bmi1: crate::x86::v4::Bmi1,
    /// The contained proof that BMI2 is available.
    pub bmi2: crate::x86::v4::Bmi2,
    /// The contained proof that `cmpxchg16b` is available.
    pub cmpxchg16b: crate::x86::v4::Cmpxchg16b,
    /// The contained proof that `fxsave + fxrstor` is available.
    pub fxsr: crate::x86::v4::Fxsr,
    /// The contained proof that `lzcnt` is available.
    pub lzcnt: crate::x86::v4::Lzcnt,
    /// The contained proof that `movbe` is available.
    pub movbe: crate::x86::v4::Movbe,
    /// The contained proof that `popcnt` is available.
    pub popcnt: crate::x86::v4::Popcnt,
    /// The contained proof that `xsave` is available.
    pub xsave: crate::x86::v4::Xsave,
    // This struct explicitly is not non_exhaustive, because it is
    // completely safe to construct from the fields.
}

impl Debug for V4 {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, r#"x86-64-v4 enabled."#)
    }
}

// Safety: This token can only be constructed if you have proofs that all the requisite
// target features are enabled.
unsafe impl TargetFeatureToken for V4 {
    const FEATURES: &[&str] = &[
        "avx",
        "avx2",
        "avx512bw",
        "avx512cd",
        "avx512dq",
        "avx512f",
        "avx512vl",
        "bmi1",
        "bmi2",
        "cmpxchg16b",
        "f16c",
        "fma",
        "fxsr",
        "lzcnt",
        "movbe",
        "popcnt",
        "sse",
        "sse2",
        "sse3",
        "sse4.1",
        "sse4.2",
        "ssse3",
        "xsave",
    ];

    #[inline(always)]
    fn vectorize<R>(self, f: impl FnOnce() -> R) -> R {
        // We use the explicitly written out form here as validation that the set of
        // features we've created correctly mapes to the target feature string.
        trampoline!([crate::x86::v4::Avx512bw = self.avx512bw, crate::x86::v4::Avx512cd = self.avx512cd, crate::x86::v4::Avx512dq = self.avx512dq, crate::x86::v4::Avx512vl = self.avx512vl, crate::x86::v4::Bmi1 = self.bmi1, crate::x86::v4::Bmi2 = self.bmi2, crate::x86::v4::Cmpxchg16b = self.cmpxchg16b, crate::x86::v4::Fxsr = self.fxsr, crate::x86::v4::Lzcnt = self.lzcnt, crate::x86::v4::Movbe = self.movbe, crate::x86::v4::Popcnt = self.popcnt, crate::x86::v4::Xsave = self.xsave] => "avx512bw,avx512cd,avx512dq,avx512vl,bmi1,bmi2,cmpxchg16b,fxsr,lzcnt,movbe,popcnt,xsave", <(R)> fn<(R)>(f: impl FnOnce() -> R = f) -> R { f() })
    }
}

impl V4 {
    #[cfg(feature = "std")]
    /// Create a new token if the x86-64-v4 target feature is detected as enabled.
    ///
    /// This does not do any caching internally, although note that the standard
    /// library does internally cache the features it detects.
    // TODO: Consider a manual override feature/env var?
    pub fn try_new() -> Option<Self> {
        Some(Self {
            avx512bw: crate::x86::v4::Avx512bw::try_new()?,
            avx512cd: crate::x86::v4::Avx512cd::try_new()?,
            avx512dq: crate::x86::v4::Avx512dq::try_new()?,
            avx512vl: crate::x86::v4::Avx512vl::try_new()?,
            bmi1: crate::x86::v4::Bmi1::try_new()?,
            bmi2: crate::x86::v4::Bmi2::try_new()?,
            cmpxchg16b: crate::x86::v4::Cmpxchg16b::try_new()?,
            fxsr: crate::x86::v4::Fxsr::try_new()?,
            lzcnt: crate::x86::v4::Lzcnt::try_new()?,
            movbe: crate::x86::v4::Movbe::try_new()?,
            popcnt: crate::x86::v4::Popcnt::try_new()?,
            xsave: crate::x86::v4::Xsave::try_new()?,
        })
    }

    #[target_feature(
        enable = "avx512bw,avx512cd,avx512dq,avx512vl,bmi1,bmi2,cmpxchg16b,fxsr,lzcnt,movbe,popcnt,xsave"
    )]
    /// Create a new token for the x86-64-v4 microarchitecture level.
    ///
    /// This method is useful to get a new token if you have an external proof that
    /// x86-64-v4 is available. This could happen if you are in a target feature
    /// function called by an external library user.
    ///
    /// # Safety
    ///
    /// No conditions other than those inherited from the target feature attribute,
    /// i.e. that the "avx512bw,avx512cd,avx512dq,avx512vl,bmi1,bmi2,cmpxchg16b,fxsr,lzcnt,movbe,popcnt,xsave" target feature is available.
    pub fn new() -> Self {
        Self {
            avx512bw: crate::x86::v4::Avx512bw::new(),
            avx512cd: crate::x86::v4::Avx512cd::new(),
            avx512dq: crate::x86::v4::Avx512dq::new(),
            avx512vl: crate::x86::v4::Avx512vl::new(),
            bmi1: crate::x86::v4::Bmi1::new(),
            bmi2: crate::x86::v4::Bmi2::new(),
            cmpxchg16b: crate::x86::v4::Cmpxchg16b::new(),
            fxsr: crate::x86::v4::Fxsr::new(),
            lzcnt: crate::x86::v4::Lzcnt::new(),
            movbe: crate::x86::v4::Movbe::new(),
            popcnt: crate::x86::v4::Popcnt::new(),
            xsave: crate::x86::v4::Xsave::new(),
        }
    }
}

impl From<V4> for crate::x86::v4::Avx {
    fn from(value: V4) -> Self {
        // This serves as a correctness check of the implicitly enabled features.
        trampoline!([V4 = value] => "avx512bw,avx512cd,avx512dq,avx512vl,bmi1,bmi2,cmpxchg16b,fxsr,lzcnt,movbe,popcnt,xsave", fn() -> crate::x86::v4::Avx { crate::x86::v4::Avx::new() })
    }
}

impl From<V4> for crate::x86::v4::Avx2 {
    fn from(value: V4) -> Self {
        // This serves as a correctness check of the implicitly enabled features.
        trampoline!([V4 = value] => "avx512bw,avx512cd,avx512dq,avx512vl,bmi1,bmi2,cmpxchg16b,fxsr,lzcnt,movbe,popcnt,xsave", fn() -> crate::x86::v4::Avx2 { crate::x86::v4::Avx2::new() })
    }
}

impl From<V4> for crate::x86::v4::Avx512bw {
    fn from(value: V4) -> Self {
        // This serves as a correctness check of the implicitly enabled features.
        trampoline!([V4 = value] => "avx512bw,avx512cd,avx512dq,avx512vl,bmi1,bmi2,cmpxchg16b,fxsr,lzcnt,movbe,popcnt,xsave", fn() -> crate::x86::v4::Avx512bw { crate::x86::v4::Avx512bw::new() })
    }
}

impl From<V4> for crate::x86::v4::Avx512cd {
    fn from(value: V4) -> Self {
        // This serves as a correctness check of the implicitly enabled features.
        trampoline!([V4 = value] => "avx512bw,avx512cd,avx512dq,avx512vl,bmi1,bmi2,cmpxchg16b,fxsr,lzcnt,movbe,popcnt,xsave", fn() -> crate::x86::v4::Avx512cd { crate::x86::v4::Avx512cd::new() })
    }
}

impl From<V4> for crate::x86::v4::Avx512dq {
    fn from(value: V4) -> Self {
        // This serves as a correctness check of the implicitly enabled features.
        trampoline!([V4 = value] => "avx512bw,avx512cd,avx512dq,avx512vl,bmi1,bmi2,cmpxchg16b,fxsr,lzcnt,movbe,popcnt,xsave", fn() -> crate::x86::v4::Avx512dq { crate::x86::v4::Avx512dq::new() })
    }
}

impl From<V4> for crate::x86::v4::Avx512f {
    fn from(value: V4) -> Self {
        // This serves as a correctness check of the implicitly enabled features.
        trampoline!([V4 = value] => "avx512bw,avx512cd,avx512dq,avx512vl,bmi1,bmi2,cmpxchg16b,fxsr,lzcnt,movbe,popcnt,xsave", fn() -> crate::x86::v4::Avx512f { crate::x86::v4::Avx512f::new() })
    }
}

impl From<V4> for crate::x86::v4::Avx512vl {
    fn from(value: V4) -> Self {
        // This serves as a correctness check of the implicitly enabled features.
        trampoline!([V4 = value] => "avx512bw,avx512cd,avx512dq,avx512vl,bmi1,bmi2,cmpxchg16b,fxsr,lzcnt,movbe,popcnt,xsave", fn() -> crate::x86::v4::Avx512vl { crate::x86::v4::Avx512vl::new() })
    }
}

impl From<V4> for crate::x86::v4::Bmi1 {
    fn from(value: V4) -> Self {
        // This serves as a correctness check of the implicitly enabled features.
        trampoline!([V4 = value] => "avx512bw,avx512cd,avx512dq,avx512vl,bmi1,bmi2,cmpxchg16b,fxsr,lzcnt,movbe,popcnt,xsave", fn() -> crate::x86::v4::Bmi1 { crate::x86::v4::Bmi1::new() })
    }
}

impl From<V4> for crate::x86::v4::Bmi2 {
    fn from(value: V4) -> Self {
        // This serves as a correctness check of the implicitly enabled features.
        trampoline!([V4 = value] => "avx512bw,avx512cd,avx512dq,avx512vl,bmi1,bmi2,cmpxchg16b,fxsr,lzcnt,movbe,popcnt,xsave", fn() -> crate::x86::v4::Bmi2 { crate::x86::v4::Bmi2::new() })
    }
}

impl From<V4> for crate::x86::v4::Cmpxchg16b {
    fn from(value: V4) -> Self {
        // This serves as a correctness check of the implicitly enabled features.
        trampoline!([V4 = value] => "avx512bw,avx512cd,avx512dq,avx512vl,bmi1,bmi2,cmpxchg16b,fxsr,lzcnt,movbe,popcnt,xsave", fn() -> crate::x86::v4::Cmpxchg16b { crate::x86::v4::Cmpxchg16b::new() })
    }
}

impl From<V4> for crate::x86::v4::F16c {
    fn from(value: V4) -> Self {
        // This serves as a correctness check of the implicitly enabled features.
        trampoline!([V4 = value] => "avx512bw,avx512cd,avx512dq,avx512vl,bmi1,bmi2,cmpxchg16b,fxsr,lzcnt,movbe,popcnt,xsave", fn() -> crate::x86::v4::F16c { crate::x86::v4::F16c::new() })
    }
}

impl From<V4> for crate::x86::v4::Fma {
    fn from(value: V4) -> Self {
        // This serves as a correctness check of the implicitly enabled features.
        trampoline!([V4 = value] => "avx512bw,avx512cd,avx512dq,avx512vl,bmi1,bmi2,cmpxchg16b,fxsr,lzcnt,movbe,popcnt,xsave", fn() -> crate::x86::v4::Fma { crate::x86::v4::Fma::new() })
    }
}

impl From<V4> for crate::x86::v4::Fxsr {
    fn from(value: V4) -> Self {
        // This serves as a correctness check of the implicitly enabled features.
        trampoline!([V4 = value] => "avx512bw,avx512cd,avx512dq,avx512vl,bmi1,bmi2,cmpxchg16b,fxsr,lzcnt,movbe,popcnt,xsave", fn() -> crate::x86::v4::Fxsr { crate::x86::v4::Fxsr::new() })
    }
}

impl From<V4> for crate::x86::v4::Lzcnt {
    fn from(value: V4) -> Self {
        // This serves as a correctness check of the implicitly enabled features.
        trampoline!([V4 = value] => "avx512bw,avx512cd,avx512dq,avx512vl,bmi1,bmi2,cmpxchg16b,fxsr,lzcnt,movbe,popcnt,xsave", fn() -> crate::x86::v4::Lzcnt { crate::x86::v4::Lzcnt::new() })
    }
}

impl From<V4> for crate::x86::v4::Movbe {
    fn from(value: V4) -> Self {
        // This serves as a correctness check of the implicitly enabled features.
        trampoline!([V4 = value] => "avx512bw,avx512cd,avx512dq,avx512vl,bmi1,bmi2,cmpxchg16b,fxsr,lzcnt,movbe,popcnt,xsave", fn() -> crate::x86::v4::Movbe { crate::x86::v4::Movbe::new() })
    }
}

impl From<V4> for crate::x86::v4::Popcnt {
    fn from(value: V4) -> Self {
        // This serves as a correctness check of the implicitly enabled features.
        trampoline!([V4 = value] => "avx512bw,avx512cd,avx512dq,avx512vl,bmi1,bmi2,cmpxchg16b,fxsr,lzcnt,movbe,popcnt,xsave", fn() -> crate::x86::v4::Popcnt { crate::x86::v4::Popcnt::new() })
    }
}

impl From<V4> for crate::x86::v4::Sse {
    fn from(value: V4) -> Self {
        // This serves as a correctness check of the implicitly enabled features.
        trampoline!([V4 = value] => "avx512bw,avx512cd,avx512dq,avx512vl,bmi1,bmi2,cmpxchg16b,fxsr,lzcnt,movbe,popcnt,xsave", fn() -> crate::x86::v4::Sse { crate::x86::v4::Sse::new() })
    }
}

impl From<V4> for crate::x86::v4::Sse2 {
    fn from(value: V4) -> Self {
        // This serves as a correctness check of the implicitly enabled features.
        trampoline!([V4 = value] => "avx512bw,avx512cd,avx512dq,avx512vl,bmi1,bmi2,cmpxchg16b,fxsr,lzcnt,movbe,popcnt,xsave", fn() -> crate::x86::v4::Sse2 { crate::x86::v4::Sse2::new() })
    }
}

impl From<V4> for crate::x86::v4::Sse3 {
    fn from(value: V4) -> Self {
        // This serves as a correctness check of the implicitly enabled features.
        trampoline!([V4 = value] => "avx512bw,avx512cd,avx512dq,avx512vl,bmi1,bmi2,cmpxchg16b,fxsr,lzcnt,movbe,popcnt,xsave", fn() -> crate::x86::v4::Sse3 { crate::x86::v4::Sse3::new() })
    }
}

impl From<V4> for crate::x86::v4::Sse4_1 {
    fn from(value: V4) -> Self {
        // This serves as a correctness check of the implicitly enabled features.
        trampoline!([V4 = value] => "avx512bw,avx512cd,avx512dq,avx512vl,bmi1,bmi2,cmpxchg16b,fxsr,lzcnt,movbe,popcnt,xsave", fn() -> crate::x86::v4::Sse4_1 { crate::x86::v4::Sse4_1::new() })
    }
}

impl From<V4> for crate::x86::v4::Sse4_2 {
    fn from(value: V4) -> Self {
        // This serves as a correctness check of the implicitly enabled features.
        trampoline!([V4 = value] => "avx512bw,avx512cd,avx512dq,avx512vl,bmi1,bmi2,cmpxchg16b,fxsr,lzcnt,movbe,popcnt,xsave", fn() -> crate::x86::v4::Sse4_2 { crate::x86::v4::Sse4_2::new() })
    }
}

impl From<V4> for crate::x86::v4::SupplementalSse3 {
    fn from(value: V4) -> Self {
        // This serves as a correctness check of the implicitly enabled features.
        trampoline!([V4 = value] => "avx512bw,avx512cd,avx512dq,avx512vl,bmi1,bmi2,cmpxchg16b,fxsr,lzcnt,movbe,popcnt,xsave", fn() -> crate::x86::v4::SupplementalSse3 { crate::x86::v4::SupplementalSse3::new() })
    }
}

impl From<V4> for crate::x86::v4::Xsave {
    fn from(value: V4) -> Self {
        // This serves as a correctness check of the implicitly enabled features.
        trampoline!([V4 = value] => "avx512bw,avx512cd,avx512dq,avx512vl,bmi1,bmi2,cmpxchg16b,fxsr,lzcnt,movbe,popcnt,xsave", fn() -> crate::x86::v4::Xsave { crate::x86::v4::Xsave::new() })
    }
}

const _: () = {
    assert!(
        core::mem::size_of::<V4>() == 0,
        "Target feature tokens should be zero sized."
    );
};
