// Copyright 2026 the Fearless_SIMD Authors
// SPDX-License-Identifier: Apache-2.0 OR MIT

// This file is autogenerated by fearless_simd_gen

use arch::*;
#[cfg(target_arch = "x86")]
use core::arch::x86 as arch;
#[cfg(target_arch = "x86_64")]
use core::arch::x86_64 as arch;
#[doc = "A token for `Avx` intrinsics on `x86` and `x86_64`."]
#[derive(Clone, Copy, Debug)]
pub struct Avx {
    _private: (),
}
#[allow(
    clippy::missing_safety_doc,
    reason = "The underlying functions have their own safety docs"
)]
impl Avx {
    #[doc = r" Create a SIMD token."]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" The required CPU features must be available."]
    #[inline]
    pub const unsafe fn new_unchecked() -> Self {
        Self { _private: () }
    }
    #[doc = "See [`arch::_mm256_add_pd`]."]
    #[inline(always)]
    pub fn _mm256_add_pd(self, a: __m256d, b: __m256d) -> __m256d {
        unsafe { _mm256_add_pd(a, b) }
    }
    #[doc = "See [`arch::_mm256_add_ps`]."]
    #[inline(always)]
    pub fn _mm256_add_ps(self, a: __m256, b: __m256) -> __m256 {
        unsafe { _mm256_add_ps(a, b) }
    }
    #[doc = "See [`arch::_mm256_and_pd`]."]
    #[inline(always)]
    pub fn _mm256_and_pd(self, a: __m256d, b: __m256d) -> __m256d {
        unsafe { _mm256_and_pd(a, b) }
    }
    #[doc = "See [`arch::_mm256_and_ps`]."]
    #[inline(always)]
    pub fn _mm256_and_ps(self, a: __m256, b: __m256) -> __m256 {
        unsafe { _mm256_and_ps(a, b) }
    }
    #[doc = "See [`arch::_mm256_or_pd`]."]
    #[inline(always)]
    pub fn _mm256_or_pd(self, a: __m256d, b: __m256d) -> __m256d {
        unsafe { _mm256_or_pd(a, b) }
    }
    #[doc = "See [`arch::_mm256_or_ps`]."]
    #[inline(always)]
    pub fn _mm256_or_ps(self, a: __m256, b: __m256) -> __m256 {
        unsafe { _mm256_or_ps(a, b) }
    }
    #[doc = "See [`arch::_mm256_shuffle_pd`]."]
    #[inline(always)]
    pub fn _mm256_shuffle_pd<const MASK: i32>(self, a: __m256d, b: __m256d) -> __m256d {
        unsafe { _mm256_shuffle_pd::<MASK>(a, b) }
    }
    #[doc = "See [`arch::_mm256_shuffle_ps`]."]
    #[inline(always)]
    pub fn _mm256_shuffle_ps<const MASK: i32>(self, a: __m256, b: __m256) -> __m256 {
        unsafe { _mm256_shuffle_ps::<MASK>(a, b) }
    }
    #[doc = "See [`arch::_mm256_andnot_pd`]."]
    #[inline(always)]
    pub fn _mm256_andnot_pd(self, a: __m256d, b: __m256d) -> __m256d {
        unsafe { _mm256_andnot_pd(a, b) }
    }
    #[doc = "See [`arch::_mm256_andnot_ps`]."]
    #[inline(always)]
    pub fn _mm256_andnot_ps(self, a: __m256, b: __m256) -> __m256 {
        unsafe { _mm256_andnot_ps(a, b) }
    }
    #[doc = "See [`arch::_mm256_max_pd`]."]
    #[inline(always)]
    pub fn _mm256_max_pd(self, a: __m256d, b: __m256d) -> __m256d {
        unsafe { _mm256_max_pd(a, b) }
    }
    #[doc = "See [`arch::_mm256_max_ps`]."]
    #[inline(always)]
    pub fn _mm256_max_ps(self, a: __m256, b: __m256) -> __m256 {
        unsafe { _mm256_max_ps(a, b) }
    }
    #[doc = "See [`arch::_mm256_min_pd`]."]
    #[inline(always)]
    pub fn _mm256_min_pd(self, a: __m256d, b: __m256d) -> __m256d {
        unsafe { _mm256_min_pd(a, b) }
    }
    #[doc = "See [`arch::_mm256_min_ps`]."]
    #[inline(always)]
    pub fn _mm256_min_ps(self, a: __m256, b: __m256) -> __m256 {
        unsafe { _mm256_min_ps(a, b) }
    }
    #[doc = "See [`arch::_mm256_mul_pd`]."]
    #[inline(always)]
    pub fn _mm256_mul_pd(self, a: __m256d, b: __m256d) -> __m256d {
        unsafe { _mm256_mul_pd(a, b) }
    }
    #[doc = "See [`arch::_mm256_mul_ps`]."]
    #[inline(always)]
    pub fn _mm256_mul_ps(self, a: __m256, b: __m256) -> __m256 {
        unsafe { _mm256_mul_ps(a, b) }
    }
    #[doc = "See [`arch::_mm256_addsub_pd`]."]
    #[inline(always)]
    pub fn _mm256_addsub_pd(self, a: __m256d, b: __m256d) -> __m256d {
        unsafe { _mm256_addsub_pd(a, b) }
    }
    #[doc = "See [`arch::_mm256_addsub_ps`]."]
    #[inline(always)]
    pub fn _mm256_addsub_ps(self, a: __m256, b: __m256) -> __m256 {
        unsafe { _mm256_addsub_ps(a, b) }
    }
    #[doc = "See [`arch::_mm256_sub_pd`]."]
    #[inline(always)]
    pub fn _mm256_sub_pd(self, a: __m256d, b: __m256d) -> __m256d {
        unsafe { _mm256_sub_pd(a, b) }
    }
    #[doc = "See [`arch::_mm256_sub_ps`]."]
    #[inline(always)]
    pub fn _mm256_sub_ps(self, a: __m256, b: __m256) -> __m256 {
        unsafe { _mm256_sub_ps(a, b) }
    }
    #[doc = "See [`arch::_mm256_div_ps`]."]
    #[inline(always)]
    pub fn _mm256_div_ps(self, a: __m256, b: __m256) -> __m256 {
        unsafe { _mm256_div_ps(a, b) }
    }
    #[doc = "See [`arch::_mm256_div_pd`]."]
    #[inline(always)]
    pub fn _mm256_div_pd(self, a: __m256d, b: __m256d) -> __m256d {
        unsafe { _mm256_div_pd(a, b) }
    }
    #[doc = "See [`arch::_mm256_round_pd`]."]
    #[inline(always)]
    pub fn _mm256_round_pd<const ROUNDING: i32>(self, a: __m256d) -> __m256d {
        unsafe { _mm256_round_pd::<ROUNDING>(a) }
    }
    #[doc = "See [`arch::_mm256_ceil_pd`]."]
    #[inline(always)]
    pub fn _mm256_ceil_pd(self, a: __m256d) -> __m256d {
        unsafe { _mm256_ceil_pd(a) }
    }
    #[doc = "See [`arch::_mm256_floor_pd`]."]
    #[inline(always)]
    pub fn _mm256_floor_pd(self, a: __m256d) -> __m256d {
        unsafe { _mm256_floor_pd(a) }
    }
    #[doc = "See [`arch::_mm256_round_ps`]."]
    #[inline(always)]
    pub fn _mm256_round_ps<const ROUNDING: i32>(self, a: __m256) -> __m256 {
        unsafe { _mm256_round_ps::<ROUNDING>(a) }
    }
    #[doc = "See [`arch::_mm256_ceil_ps`]."]
    #[inline(always)]
    pub fn _mm256_ceil_ps(self, a: __m256) -> __m256 {
        unsafe { _mm256_ceil_ps(a) }
    }
    #[doc = "See [`arch::_mm256_floor_ps`]."]
    #[inline(always)]
    pub fn _mm256_floor_ps(self, a: __m256) -> __m256 {
        unsafe { _mm256_floor_ps(a) }
    }
    #[doc = "See [`arch::_mm256_sqrt_ps`]."]
    #[inline(always)]
    pub fn _mm256_sqrt_ps(self, a: __m256) -> __m256 {
        unsafe { _mm256_sqrt_ps(a) }
    }
    #[doc = "See [`arch::_mm256_sqrt_pd`]."]
    #[inline(always)]
    pub fn _mm256_sqrt_pd(self, a: __m256d) -> __m256d {
        unsafe { _mm256_sqrt_pd(a) }
    }
    #[doc = "See [`arch::_mm256_blend_pd`]."]
    #[inline(always)]
    pub fn _mm256_blend_pd<const IMM4: i32>(self, a: __m256d, b: __m256d) -> __m256d {
        unsafe { _mm256_blend_pd::<IMM4>(a, b) }
    }
    #[doc = "See [`arch::_mm256_blend_ps`]."]
    #[inline(always)]
    pub fn _mm256_blend_ps<const IMM8: i32>(self, a: __m256, b: __m256) -> __m256 {
        unsafe { _mm256_blend_ps::<IMM8>(a, b) }
    }
    #[doc = "See [`arch::_mm256_blendv_pd`]."]
    #[inline(always)]
    pub fn _mm256_blendv_pd(self, a: __m256d, b: __m256d, c: __m256d) -> __m256d {
        unsafe { _mm256_blendv_pd(a, b, c) }
    }
    #[doc = "See [`arch::_mm256_blendv_ps`]."]
    #[inline(always)]
    pub fn _mm256_blendv_ps(self, a: __m256, b: __m256, c: __m256) -> __m256 {
        unsafe { _mm256_blendv_ps(a, b, c) }
    }
    #[doc = "See [`arch::_mm256_dp_ps`]."]
    #[inline(always)]
    pub fn _mm256_dp_ps<const IMM8: i32>(self, a: __m256, b: __m256) -> __m256 {
        unsafe { _mm256_dp_ps::<IMM8>(a, b) }
    }
    #[doc = "See [`arch::_mm256_hadd_pd`]."]
    #[inline(always)]
    pub fn _mm256_hadd_pd(self, a: __m256d, b: __m256d) -> __m256d {
        unsafe { _mm256_hadd_pd(a, b) }
    }
    #[doc = "See [`arch::_mm256_hadd_ps`]."]
    #[inline(always)]
    pub fn _mm256_hadd_ps(self, a: __m256, b: __m256) -> __m256 {
        unsafe { _mm256_hadd_ps(a, b) }
    }
    #[doc = "See [`arch::_mm256_hsub_pd`]."]
    #[inline(always)]
    pub fn _mm256_hsub_pd(self, a: __m256d, b: __m256d) -> __m256d {
        unsafe { _mm256_hsub_pd(a, b) }
    }
    #[doc = "See [`arch::_mm256_hsub_ps`]."]
    #[inline(always)]
    pub fn _mm256_hsub_ps(self, a: __m256, b: __m256) -> __m256 {
        unsafe { _mm256_hsub_ps(a, b) }
    }
    #[doc = "See [`arch::_mm256_xor_pd`]."]
    #[inline(always)]
    pub fn _mm256_xor_pd(self, a: __m256d, b: __m256d) -> __m256d {
        unsafe { _mm256_xor_pd(a, b) }
    }
    #[doc = "See [`arch::_mm256_xor_ps`]."]
    #[inline(always)]
    pub fn _mm256_xor_ps(self, a: __m256, b: __m256) -> __m256 {
        unsafe { _mm256_xor_ps(a, b) }
    }
    #[doc = "See [`arch::_mm_cmp_pd`]."]
    #[inline(always)]
    pub fn _mm_cmp_pd<const IMM5: i32>(self, a: __m128d, b: __m128d) -> __m128d {
        unsafe { _mm_cmp_pd::<IMM5>(a, b) }
    }
    #[doc = "See [`arch::_mm256_cmp_pd`]."]
    #[inline(always)]
    pub fn _mm256_cmp_pd<const IMM5: i32>(self, a: __m256d, b: __m256d) -> __m256d {
        unsafe { _mm256_cmp_pd::<IMM5>(a, b) }
    }
    #[doc = "See [`arch::_mm_cmp_ps`]."]
    #[inline(always)]
    pub fn _mm_cmp_ps<const IMM5: i32>(self, a: __m128, b: __m128) -> __m128 {
        unsafe { _mm_cmp_ps::<IMM5>(a, b) }
    }
    #[doc = "See [`arch::_mm256_cmp_ps`]."]
    #[inline(always)]
    pub fn _mm256_cmp_ps<const IMM5: i32>(self, a: __m256, b: __m256) -> __m256 {
        unsafe { _mm256_cmp_ps::<IMM5>(a, b) }
    }
    #[doc = "See [`arch::_mm_cmp_sd`]."]
    #[inline(always)]
    pub fn _mm_cmp_sd<const IMM5: i32>(self, a: __m128d, b: __m128d) -> __m128d {
        unsafe { _mm_cmp_sd::<IMM5>(a, b) }
    }
    #[doc = "See [`arch::_mm_cmp_ss`]."]
    #[inline(always)]
    pub fn _mm_cmp_ss<const IMM5: i32>(self, a: __m128, b: __m128) -> __m128 {
        unsafe { _mm_cmp_ss::<IMM5>(a, b) }
    }
    #[doc = "See [`arch::_mm256_cvtepi32_pd`]."]
    #[inline(always)]
    pub fn _mm256_cvtepi32_pd(self, a: __m128i) -> __m256d {
        unsafe { _mm256_cvtepi32_pd(a) }
    }
    #[doc = "See [`arch::_mm256_cvtepi32_ps`]."]
    #[inline(always)]
    pub fn _mm256_cvtepi32_ps(self, a: __m256i) -> __m256 {
        unsafe { _mm256_cvtepi32_ps(a) }
    }
    #[doc = "See [`arch::_mm256_cvtpd_ps`]."]
    #[inline(always)]
    pub fn _mm256_cvtpd_ps(self, a: __m256d) -> __m128 {
        unsafe { _mm256_cvtpd_ps(a) }
    }
    #[doc = "See [`arch::_mm256_cvtps_epi32`]."]
    #[inline(always)]
    pub fn _mm256_cvtps_epi32(self, a: __m256) -> __m256i {
        unsafe { _mm256_cvtps_epi32(a) }
    }
    #[doc = "See [`arch::_mm256_cvtps_pd`]."]
    #[inline(always)]
    pub fn _mm256_cvtps_pd(self, a: __m128) -> __m256d {
        unsafe { _mm256_cvtps_pd(a) }
    }
    #[doc = "See [`arch::_mm256_cvtsd_f64`]."]
    #[inline(always)]
    pub fn _mm256_cvtsd_f64(self, a: __m256d) -> f64 {
        unsafe { _mm256_cvtsd_f64(a) }
    }
    #[doc = "See [`arch::_mm256_cvttpd_epi32`]."]
    #[inline(always)]
    pub fn _mm256_cvttpd_epi32(self, a: __m256d) -> __m128i {
        unsafe { _mm256_cvttpd_epi32(a) }
    }
    #[doc = "See [`arch::_mm256_cvtpd_epi32`]."]
    #[inline(always)]
    pub fn _mm256_cvtpd_epi32(self, a: __m256d) -> __m128i {
        unsafe { _mm256_cvtpd_epi32(a) }
    }
    #[doc = "See [`arch::_mm256_cvttps_epi32`]."]
    #[inline(always)]
    pub fn _mm256_cvttps_epi32(self, a: __m256) -> __m256i {
        unsafe { _mm256_cvttps_epi32(a) }
    }
    #[doc = "See [`arch::_mm256_extractf128_ps`]."]
    #[inline(always)]
    pub fn _mm256_extractf128_ps<const IMM1: i32>(self, a: __m256) -> __m128 {
        unsafe { _mm256_extractf128_ps::<IMM1>(a) }
    }
    #[doc = "See [`arch::_mm256_extractf128_pd`]."]
    #[inline(always)]
    pub fn _mm256_extractf128_pd<const IMM1: i32>(self, a: __m256d) -> __m128d {
        unsafe { _mm256_extractf128_pd::<IMM1>(a) }
    }
    #[doc = "See [`arch::_mm256_extractf128_si256`]."]
    #[inline(always)]
    pub fn _mm256_extractf128_si256<const IMM1: i32>(self, a: __m256i) -> __m128i {
        unsafe { _mm256_extractf128_si256::<IMM1>(a) }
    }
    #[doc = "See [`arch::_mm256_extract_epi32`]."]
    #[inline(always)]
    pub fn _mm256_extract_epi32<const INDEX: i32>(self, a: __m256i) -> i32 {
        unsafe { _mm256_extract_epi32::<INDEX>(a) }
    }
    #[doc = "See [`arch::_mm256_cvtsi256_si32`]."]
    #[inline(always)]
    pub fn _mm256_cvtsi256_si32(self, a: __m256i) -> i32 {
        unsafe { _mm256_cvtsi256_si32(a) }
    }
    #[doc = "See [`arch::_mm256_zeroall`]."]
    #[inline(always)]
    pub fn _mm256_zeroall(self) {
        unsafe { _mm256_zeroall() }
    }
    #[doc = "See [`arch::_mm256_zeroupper`]."]
    #[inline(always)]
    pub fn _mm256_zeroupper(self) {
        unsafe { _mm256_zeroupper() }
    }
    #[doc = "See [`arch::_mm256_permutevar_ps`]."]
    #[inline(always)]
    pub fn _mm256_permutevar_ps(self, a: __m256, b: __m256i) -> __m256 {
        unsafe { _mm256_permutevar_ps(a, b) }
    }
    #[doc = "See [`arch::_mm_permutevar_ps`]."]
    #[inline(always)]
    pub fn _mm_permutevar_ps(self, a: __m128, b: __m128i) -> __m128 {
        unsafe { _mm_permutevar_ps(a, b) }
    }
    #[doc = "See [`arch::_mm256_permute_ps`]."]
    #[inline(always)]
    pub fn _mm256_permute_ps<const IMM8: i32>(self, a: __m256) -> __m256 {
        unsafe { _mm256_permute_ps::<IMM8>(a) }
    }
    #[doc = "See [`arch::_mm_permute_ps`]."]
    #[inline(always)]
    pub fn _mm_permute_ps<const IMM8: i32>(self, a: __m128) -> __m128 {
        unsafe { _mm_permute_ps::<IMM8>(a) }
    }
    #[doc = "See [`arch::_mm256_permutevar_pd`]."]
    #[inline(always)]
    pub fn _mm256_permutevar_pd(self, a: __m256d, b: __m256i) -> __m256d {
        unsafe { _mm256_permutevar_pd(a, b) }
    }
    #[doc = "See [`arch::_mm_permutevar_pd`]."]
    #[inline(always)]
    pub fn _mm_permutevar_pd(self, a: __m128d, b: __m128i) -> __m128d {
        unsafe { _mm_permutevar_pd(a, b) }
    }
    #[doc = "See [`arch::_mm256_permute_pd`]."]
    #[inline(always)]
    pub fn _mm256_permute_pd<const IMM4: i32>(self, a: __m256d) -> __m256d {
        unsafe { _mm256_permute_pd::<IMM4>(a) }
    }
    #[doc = "See [`arch::_mm_permute_pd`]."]
    #[inline(always)]
    pub fn _mm_permute_pd<const IMM2: i32>(self, a: __m128d) -> __m128d {
        unsafe { _mm_permute_pd::<IMM2>(a) }
    }
    #[doc = "See [`arch::_mm256_permute2f128_ps`]."]
    #[inline(always)]
    pub fn _mm256_permute2f128_ps<const IMM8: i32>(self, a: __m256, b: __m256) -> __m256 {
        unsafe { _mm256_permute2f128_ps::<IMM8>(a, b) }
    }
    #[doc = "See [`arch::_mm256_permute2f128_pd`]."]
    #[inline(always)]
    pub fn _mm256_permute2f128_pd<const IMM8: i32>(self, a: __m256d, b: __m256d) -> __m256d {
        unsafe { _mm256_permute2f128_pd::<IMM8>(a, b) }
    }
    #[doc = "See [`arch::_mm256_permute2f128_si256`]."]
    #[inline(always)]
    pub fn _mm256_permute2f128_si256<const IMM8: i32>(self, a: __m256i, b: __m256i) -> __m256i {
        unsafe { _mm256_permute2f128_si256::<IMM8>(a, b) }
    }
    #[doc = "See [`arch::_mm256_broadcast_ss`]."]
    #[allow(clippy::trivially_copy_pass_by_ref)]
    #[inline(always)]
    pub fn _mm256_broadcast_ss(self, f: &f32) -> __m256 {
        unsafe { _mm256_broadcast_ss(f) }
    }
    #[doc = "See [`arch::_mm_broadcast_ss`]."]
    #[allow(clippy::trivially_copy_pass_by_ref)]
    #[inline(always)]
    pub fn _mm_broadcast_ss(self, f: &f32) -> __m128 {
        unsafe { _mm_broadcast_ss(f) }
    }
    #[doc = "See [`arch::_mm256_broadcast_sd`]."]
    #[allow(clippy::trivially_copy_pass_by_ref)]
    #[inline(always)]
    pub fn _mm256_broadcast_sd(self, f: &f64) -> __m256d {
        unsafe { _mm256_broadcast_sd(f) }
    }
    #[doc = "See [`arch::_mm256_broadcast_ps`]."]
    #[inline(always)]
    pub fn _mm256_broadcast_ps(self, a: &__m128) -> __m256 {
        unsafe { _mm256_broadcast_ps(a) }
    }
    #[doc = "See [`arch::_mm256_broadcast_pd`]."]
    #[inline(always)]
    pub fn _mm256_broadcast_pd(self, a: &__m128d) -> __m256d {
        unsafe { _mm256_broadcast_pd(a) }
    }
    #[doc = "See [`arch::_mm256_insertf128_ps`]."]
    #[inline(always)]
    pub fn _mm256_insertf128_ps<const IMM1: i32>(self, a: __m256, b: __m128) -> __m256 {
        unsafe { _mm256_insertf128_ps::<IMM1>(a, b) }
    }
    #[doc = "See [`arch::_mm256_insertf128_pd`]."]
    #[inline(always)]
    pub fn _mm256_insertf128_pd<const IMM1: i32>(self, a: __m256d, b: __m128d) -> __m256d {
        unsafe { _mm256_insertf128_pd::<IMM1>(a, b) }
    }
    #[doc = "See [`arch::_mm256_insertf128_si256`]."]
    #[inline(always)]
    pub fn _mm256_insertf128_si256<const IMM1: i32>(self, a: __m256i, b: __m128i) -> __m256i {
        unsafe { _mm256_insertf128_si256::<IMM1>(a, b) }
    }
    #[doc = "See [`arch::_mm256_insert_epi8`]."]
    #[inline(always)]
    pub fn _mm256_insert_epi8<const INDEX: i32>(self, a: __m256i, i: i8) -> __m256i {
        unsafe { _mm256_insert_epi8::<INDEX>(a, i) }
    }
    #[doc = "See [`arch::_mm256_insert_epi16`]."]
    #[inline(always)]
    pub fn _mm256_insert_epi16<const INDEX: i32>(self, a: __m256i, i: i16) -> __m256i {
        unsafe { _mm256_insert_epi16::<INDEX>(a, i) }
    }
    #[doc = "See [`arch::_mm256_insert_epi32`]."]
    #[inline(always)]
    pub fn _mm256_insert_epi32<const INDEX: i32>(self, a: __m256i, i: i32) -> __m256i {
        unsafe { _mm256_insert_epi32::<INDEX>(a, i) }
    }
    #[doc = "See [`arch::_mm256_load_pd`]."]
    #[allow(clippy::cast_ptr_alignment)]
    #[inline(always)]
    pub unsafe fn _mm256_load_pd(self, mem_addr: *const f64) -> __m256d {
        unsafe { _mm256_load_pd(mem_addr) }
    }
    #[doc = "See [`arch::_mm256_store_pd`]."]
    #[allow(clippy::cast_ptr_alignment)]
    #[inline(always)]
    pub unsafe fn _mm256_store_pd(self, mem_addr: *mut f64, a: __m256d) {
        unsafe { _mm256_store_pd(mem_addr, a) }
    }
    #[doc = "See [`arch::_mm256_load_ps`]."]
    #[allow(clippy::cast_ptr_alignment)]
    #[inline(always)]
    pub unsafe fn _mm256_load_ps(self, mem_addr: *const f32) -> __m256 {
        unsafe { _mm256_load_ps(mem_addr) }
    }
    #[doc = "See [`arch::_mm256_store_ps`]."]
    #[allow(clippy::cast_ptr_alignment)]
    #[inline(always)]
    pub unsafe fn _mm256_store_ps(self, mem_addr: *mut f32, a: __m256) {
        unsafe { _mm256_store_ps(mem_addr, a) }
    }
    #[doc = "See [`arch::_mm256_loadu_pd`]."]
    #[inline(always)]
    pub unsafe fn _mm256_loadu_pd(self, mem_addr: *const f64) -> __m256d {
        unsafe { _mm256_loadu_pd(mem_addr) }
    }
    #[doc = "See [`arch::_mm256_storeu_pd`]."]
    #[inline(always)]
    pub unsafe fn _mm256_storeu_pd(self, mem_addr: *mut f64, a: __m256d) {
        unsafe { _mm256_storeu_pd(mem_addr, a) }
    }
    #[doc = "See [`arch::_mm256_loadu_ps`]."]
    #[inline(always)]
    pub unsafe fn _mm256_loadu_ps(self, mem_addr: *const f32) -> __m256 {
        unsafe { _mm256_loadu_ps(mem_addr) }
    }
    #[doc = "See [`arch::_mm256_storeu_ps`]."]
    #[inline(always)]
    pub unsafe fn _mm256_storeu_ps(self, mem_addr: *mut f32, a: __m256) {
        unsafe { _mm256_storeu_ps(mem_addr, a) }
    }
    #[doc = "See [`arch::_mm256_load_si256`]."]
    #[inline(always)]
    pub unsafe fn _mm256_load_si256(self, mem_addr: *const __m256i) -> __m256i {
        unsafe { _mm256_load_si256(mem_addr) }
    }
    #[doc = "See [`arch::_mm256_store_si256`]."]
    #[inline(always)]
    pub unsafe fn _mm256_store_si256(self, mem_addr: *mut __m256i, a: __m256i) {
        unsafe { _mm256_store_si256(mem_addr, a) }
    }
    #[doc = "See [`arch::_mm256_loadu_si256`]."]
    #[inline(always)]
    pub unsafe fn _mm256_loadu_si256(self, mem_addr: *const __m256i) -> __m256i {
        unsafe { _mm256_loadu_si256(mem_addr) }
    }
    #[doc = "See [`arch::_mm256_storeu_si256`]."]
    #[inline(always)]
    pub unsafe fn _mm256_storeu_si256(self, mem_addr: *mut __m256i, a: __m256i) {
        unsafe { _mm256_storeu_si256(mem_addr, a) }
    }
    #[doc = "See [`arch::_mm256_maskload_pd`]."]
    #[inline(always)]
    pub unsafe fn _mm256_maskload_pd(self, mem_addr: *const f64, mask: __m256i) -> __m256d {
        unsafe { _mm256_maskload_pd(mem_addr, mask) }
    }
    #[doc = "See [`arch::_mm256_maskstore_pd`]."]
    #[inline(always)]
    pub unsafe fn _mm256_maskstore_pd(self, mem_addr: *mut f64, mask: __m256i, a: __m256d) {
        unsafe { _mm256_maskstore_pd(mem_addr, mask, a) }
    }
    #[doc = "See [`arch::_mm_maskload_pd`]."]
    #[inline(always)]
    pub unsafe fn _mm_maskload_pd(self, mem_addr: *const f64, mask: __m128i) -> __m128d {
        unsafe { _mm_maskload_pd(mem_addr, mask) }
    }
    #[doc = "See [`arch::_mm_maskstore_pd`]."]
    #[inline(always)]
    pub unsafe fn _mm_maskstore_pd(self, mem_addr: *mut f64, mask: __m128i, a: __m128d) {
        unsafe { _mm_maskstore_pd(mem_addr, mask, a) }
    }
    #[doc = "See [`arch::_mm256_maskload_ps`]."]
    #[inline(always)]
    pub unsafe fn _mm256_maskload_ps(self, mem_addr: *const f32, mask: __m256i) -> __m256 {
        unsafe { _mm256_maskload_ps(mem_addr, mask) }
    }
    #[doc = "See [`arch::_mm256_maskstore_ps`]."]
    #[inline(always)]
    pub unsafe fn _mm256_maskstore_ps(self, mem_addr: *mut f32, mask: __m256i, a: __m256) {
        unsafe { _mm256_maskstore_ps(mem_addr, mask, a) }
    }
    #[doc = "See [`arch::_mm_maskload_ps`]."]
    #[inline(always)]
    pub unsafe fn _mm_maskload_ps(self, mem_addr: *const f32, mask: __m128i) -> __m128 {
        unsafe { _mm_maskload_ps(mem_addr, mask) }
    }
    #[doc = "See [`arch::_mm_maskstore_ps`]."]
    #[inline(always)]
    pub unsafe fn _mm_maskstore_ps(self, mem_addr: *mut f32, mask: __m128i, a: __m128) {
        unsafe { _mm_maskstore_ps(mem_addr, mask, a) }
    }
    #[doc = "See [`arch::_mm256_movehdup_ps`]."]
    #[inline(always)]
    pub fn _mm256_movehdup_ps(self, a: __m256) -> __m256 {
        unsafe { _mm256_movehdup_ps(a) }
    }
    #[doc = "See [`arch::_mm256_moveldup_ps`]."]
    #[inline(always)]
    pub fn _mm256_moveldup_ps(self, a: __m256) -> __m256 {
        unsafe { _mm256_moveldup_ps(a) }
    }
    #[doc = "See [`arch::_mm256_movedup_pd`]."]
    #[inline(always)]
    pub fn _mm256_movedup_pd(self, a: __m256d) -> __m256d {
        unsafe { _mm256_movedup_pd(a) }
    }
    #[doc = "See [`arch::_mm256_lddqu_si256`]."]
    #[inline(always)]
    pub unsafe fn _mm256_lddqu_si256(self, mem_addr: *const __m256i) -> __m256i {
        unsafe { _mm256_lddqu_si256(mem_addr) }
    }
    #[doc = "See [`arch::_mm256_stream_si256`]."]
    #[inline(always)]
    pub unsafe fn _mm256_stream_si256(self, mem_addr: *mut __m256i, a: __m256i) {
        unsafe { _mm256_stream_si256(mem_addr, a) }
    }
    #[doc = "See [`arch::_mm256_stream_pd`]."]
    #[allow(clippy::cast_ptr_alignment)]
    #[inline(always)]
    pub unsafe fn _mm256_stream_pd(self, mem_addr: *mut f64, a: __m256d) {
        unsafe { _mm256_stream_pd(mem_addr, a) }
    }
    #[doc = "See [`arch::_mm256_stream_ps`]."]
    #[allow(clippy::cast_ptr_alignment)]
    #[inline(always)]
    pub unsafe fn _mm256_stream_ps(self, mem_addr: *mut f32, a: __m256) {
        unsafe { _mm256_stream_ps(mem_addr, a) }
    }
    #[doc = "See [`arch::_mm256_rcp_ps`]."]
    #[inline(always)]
    pub fn _mm256_rcp_ps(self, a: __m256) -> __m256 {
        unsafe { _mm256_rcp_ps(a) }
    }
    #[doc = "See [`arch::_mm256_rsqrt_ps`]."]
    #[inline(always)]
    pub fn _mm256_rsqrt_ps(self, a: __m256) -> __m256 {
        unsafe { _mm256_rsqrt_ps(a) }
    }
    #[doc = "See [`arch::_mm256_unpackhi_pd`]."]
    #[inline(always)]
    pub fn _mm256_unpackhi_pd(self, a: __m256d, b: __m256d) -> __m256d {
        unsafe { _mm256_unpackhi_pd(a, b) }
    }
    #[doc = "See [`arch::_mm256_unpackhi_ps`]."]
    #[inline(always)]
    pub fn _mm256_unpackhi_ps(self, a: __m256, b: __m256) -> __m256 {
        unsafe { _mm256_unpackhi_ps(a, b) }
    }
    #[doc = "See [`arch::_mm256_unpacklo_pd`]."]
    #[inline(always)]
    pub fn _mm256_unpacklo_pd(self, a: __m256d, b: __m256d) -> __m256d {
        unsafe { _mm256_unpacklo_pd(a, b) }
    }
    #[doc = "See [`arch::_mm256_unpacklo_ps`]."]
    #[inline(always)]
    pub fn _mm256_unpacklo_ps(self, a: __m256, b: __m256) -> __m256 {
        unsafe { _mm256_unpacklo_ps(a, b) }
    }
    #[doc = "See [`arch::_mm256_testz_si256`]."]
    #[inline(always)]
    pub fn _mm256_testz_si256(self, a: __m256i, b: __m256i) -> i32 {
        unsafe { _mm256_testz_si256(a, b) }
    }
    #[doc = "See [`arch::_mm256_testc_si256`]."]
    #[inline(always)]
    pub fn _mm256_testc_si256(self, a: __m256i, b: __m256i) -> i32 {
        unsafe { _mm256_testc_si256(a, b) }
    }
    #[doc = "See [`arch::_mm256_testnzc_si256`]."]
    #[inline(always)]
    pub fn _mm256_testnzc_si256(self, a: __m256i, b: __m256i) -> i32 {
        unsafe { _mm256_testnzc_si256(a, b) }
    }
    #[doc = "See [`arch::_mm256_testz_pd`]."]
    #[inline(always)]
    pub fn _mm256_testz_pd(self, a: __m256d, b: __m256d) -> i32 {
        unsafe { _mm256_testz_pd(a, b) }
    }
    #[doc = "See [`arch::_mm256_testc_pd`]."]
    #[inline(always)]
    pub fn _mm256_testc_pd(self, a: __m256d, b: __m256d) -> i32 {
        unsafe { _mm256_testc_pd(a, b) }
    }
    #[doc = "See [`arch::_mm256_testnzc_pd`]."]
    #[inline(always)]
    pub fn _mm256_testnzc_pd(self, a: __m256d, b: __m256d) -> i32 {
        unsafe { _mm256_testnzc_pd(a, b) }
    }
    #[doc = "See [`arch::_mm_testz_pd`]."]
    #[inline(always)]
    pub fn _mm_testz_pd(self, a: __m128d, b: __m128d) -> i32 {
        unsafe { _mm_testz_pd(a, b) }
    }
    #[doc = "See [`arch::_mm_testc_pd`]."]
    #[inline(always)]
    pub fn _mm_testc_pd(self, a: __m128d, b: __m128d) -> i32 {
        unsafe { _mm_testc_pd(a, b) }
    }
    #[doc = "See [`arch::_mm_testnzc_pd`]."]
    #[inline(always)]
    pub fn _mm_testnzc_pd(self, a: __m128d, b: __m128d) -> i32 {
        unsafe { _mm_testnzc_pd(a, b) }
    }
    #[doc = "See [`arch::_mm256_testz_ps`]."]
    #[inline(always)]
    pub fn _mm256_testz_ps(self, a: __m256, b: __m256) -> i32 {
        unsafe { _mm256_testz_ps(a, b) }
    }
    #[doc = "See [`arch::_mm256_testc_ps`]."]
    #[inline(always)]
    pub fn _mm256_testc_ps(self, a: __m256, b: __m256) -> i32 {
        unsafe { _mm256_testc_ps(a, b) }
    }
    #[doc = "See [`arch::_mm256_testnzc_ps`]."]
    #[inline(always)]
    pub fn _mm256_testnzc_ps(self, a: __m256, b: __m256) -> i32 {
        unsafe { _mm256_testnzc_ps(a, b) }
    }
    #[doc = "See [`arch::_mm_testz_ps`]."]
    #[inline(always)]
    pub fn _mm_testz_ps(self, a: __m128, b: __m128) -> i32 {
        unsafe { _mm_testz_ps(a, b) }
    }
    #[doc = "See [`arch::_mm_testc_ps`]."]
    #[inline(always)]
    pub fn _mm_testc_ps(self, a: __m128, b: __m128) -> i32 {
        unsafe { _mm_testc_ps(a, b) }
    }
    #[doc = "See [`arch::_mm_testnzc_ps`]."]
    #[inline(always)]
    pub fn _mm_testnzc_ps(self, a: __m128, b: __m128) -> i32 {
        unsafe { _mm_testnzc_ps(a, b) }
    }
    #[doc = "See [`arch::_mm256_movemask_pd`]."]
    #[inline(always)]
    pub fn _mm256_movemask_pd(self, a: __m256d) -> i32 {
        unsafe { _mm256_movemask_pd(a) }
    }
    #[doc = "See [`arch::_mm256_movemask_ps`]."]
    #[inline(always)]
    pub fn _mm256_movemask_ps(self, a: __m256) -> i32 {
        unsafe { _mm256_movemask_ps(a) }
    }
    #[doc = "See [`arch::_mm256_setzero_pd`]."]
    #[inline(always)]
    pub fn _mm256_setzero_pd(self) -> __m256d {
        unsafe { _mm256_setzero_pd() }
    }
    #[doc = "See [`arch::_mm256_setzero_ps`]."]
    #[inline(always)]
    pub fn _mm256_setzero_ps(self) -> __m256 {
        unsafe { _mm256_setzero_ps() }
    }
    #[doc = "See [`arch::_mm256_setzero_si256`]."]
    #[inline(always)]
    pub fn _mm256_setzero_si256(self) -> __m256i {
        unsafe { _mm256_setzero_si256() }
    }
    #[doc = "See [`arch::_mm256_set_pd`]."]
    #[inline(always)]
    pub fn _mm256_set_pd(self, a: f64, b: f64, c: f64, d: f64) -> __m256d {
        unsafe { _mm256_set_pd(a, b, c, d) }
    }
    #[doc = "See [`arch::_mm256_set_ps`]."]
    #[inline(always)]
    pub fn _mm256_set_ps(
        self,
        a: f32,
        b: f32,
        c: f32,
        d: f32,
        e: f32,
        f: f32,
        g: f32,
        h: f32,
    ) -> __m256 {
        unsafe { _mm256_set_ps(a, b, c, d, e, f, g, h) }
    }
    #[doc = "See [`arch::_mm256_set_epi8`]."]
    #[inline(always)]
    pub fn _mm256_set_epi8(
        self,
        e00: i8,
        e01: i8,
        e02: i8,
        e03: i8,
        e04: i8,
        e05: i8,
        e06: i8,
        e07: i8,
        e08: i8,
        e09: i8,
        e10: i8,
        e11: i8,
        e12: i8,
        e13: i8,
        e14: i8,
        e15: i8,
        e16: i8,
        e17: i8,
        e18: i8,
        e19: i8,
        e20: i8,
        e21: i8,
        e22: i8,
        e23: i8,
        e24: i8,
        e25: i8,
        e26: i8,
        e27: i8,
        e28: i8,
        e29: i8,
        e30: i8,
        e31: i8,
    ) -> __m256i {
        unsafe {
            _mm256_set_epi8(
                e00, e01, e02, e03, e04, e05, e06, e07, e08, e09, e10, e11, e12, e13, e14, e15,
                e16, e17, e18, e19, e20, e21, e22, e23, e24, e25, e26, e27, e28, e29, e30, e31,
            )
        }
    }
    #[doc = "See [`arch::_mm256_set_epi16`]."]
    #[inline(always)]
    pub fn _mm256_set_epi16(
        self,
        e00: i16,
        e01: i16,
        e02: i16,
        e03: i16,
        e04: i16,
        e05: i16,
        e06: i16,
        e07: i16,
        e08: i16,
        e09: i16,
        e10: i16,
        e11: i16,
        e12: i16,
        e13: i16,
        e14: i16,
        e15: i16,
    ) -> __m256i {
        unsafe {
            _mm256_set_epi16(
                e00, e01, e02, e03, e04, e05, e06, e07, e08, e09, e10, e11, e12, e13, e14, e15,
            )
        }
    }
    #[doc = "See [`arch::_mm256_set_epi32`]."]
    #[inline(always)]
    pub fn _mm256_set_epi32(
        self,
        e0: i32,
        e1: i32,
        e2: i32,
        e3: i32,
        e4: i32,
        e5: i32,
        e6: i32,
        e7: i32,
    ) -> __m256i {
        unsafe { _mm256_set_epi32(e0, e1, e2, e3, e4, e5, e6, e7) }
    }
    #[doc = "See [`arch::_mm256_set_epi64x`]."]
    #[inline(always)]
    pub fn _mm256_set_epi64x(self, a: i64, b: i64, c: i64, d: i64) -> __m256i {
        unsafe { _mm256_set_epi64x(a, b, c, d) }
    }
    #[doc = "See [`arch::_mm256_setr_pd`]."]
    #[inline(always)]
    pub fn _mm256_setr_pd(self, a: f64, b: f64, c: f64, d: f64) -> __m256d {
        unsafe { _mm256_setr_pd(a, b, c, d) }
    }
    #[doc = "See [`arch::_mm256_setr_ps`]."]
    #[inline(always)]
    pub fn _mm256_setr_ps(
        self,
        a: f32,
        b: f32,
        c: f32,
        d: f32,
        e: f32,
        f: f32,
        g: f32,
        h: f32,
    ) -> __m256 {
        unsafe { _mm256_setr_ps(a, b, c, d, e, f, g, h) }
    }
    #[doc = "See [`arch::_mm256_setr_epi8`]."]
    #[inline(always)]
    pub fn _mm256_setr_epi8(
        self,
        e00: i8,
        e01: i8,
        e02: i8,
        e03: i8,
        e04: i8,
        e05: i8,
        e06: i8,
        e07: i8,
        e08: i8,
        e09: i8,
        e10: i8,
        e11: i8,
        e12: i8,
        e13: i8,
        e14: i8,
        e15: i8,
        e16: i8,
        e17: i8,
        e18: i8,
        e19: i8,
        e20: i8,
        e21: i8,
        e22: i8,
        e23: i8,
        e24: i8,
        e25: i8,
        e26: i8,
        e27: i8,
        e28: i8,
        e29: i8,
        e30: i8,
        e31: i8,
    ) -> __m256i {
        unsafe {
            _mm256_setr_epi8(
                e00, e01, e02, e03, e04, e05, e06, e07, e08, e09, e10, e11, e12, e13, e14, e15,
                e16, e17, e18, e19, e20, e21, e22, e23, e24, e25, e26, e27, e28, e29, e30, e31,
            )
        }
    }
    #[doc = "See [`arch::_mm256_setr_epi16`]."]
    #[inline(always)]
    pub fn _mm256_setr_epi16(
        self,
        e00: i16,
        e01: i16,
        e02: i16,
        e03: i16,
        e04: i16,
        e05: i16,
        e06: i16,
        e07: i16,
        e08: i16,
        e09: i16,
        e10: i16,
        e11: i16,
        e12: i16,
        e13: i16,
        e14: i16,
        e15: i16,
    ) -> __m256i {
        unsafe {
            _mm256_setr_epi16(
                e00, e01, e02, e03, e04, e05, e06, e07, e08, e09, e10, e11, e12, e13, e14, e15,
            )
        }
    }
    #[doc = "See [`arch::_mm256_setr_epi32`]."]
    #[inline(always)]
    pub fn _mm256_setr_epi32(
        self,
        e0: i32,
        e1: i32,
        e2: i32,
        e3: i32,
        e4: i32,
        e5: i32,
        e6: i32,
        e7: i32,
    ) -> __m256i {
        unsafe { _mm256_setr_epi32(e0, e1, e2, e3, e4, e5, e6, e7) }
    }
    #[doc = "See [`arch::_mm256_setr_epi64x`]."]
    #[inline(always)]
    pub fn _mm256_setr_epi64x(self, a: i64, b: i64, c: i64, d: i64) -> __m256i {
        unsafe { _mm256_setr_epi64x(a, b, c, d) }
    }
    #[doc = "See [`arch::_mm256_set1_pd`]."]
    #[inline(always)]
    pub fn _mm256_set1_pd(self, a: f64) -> __m256d {
        unsafe { _mm256_set1_pd(a) }
    }
    #[doc = "See [`arch::_mm256_set1_ps`]."]
    #[inline(always)]
    pub fn _mm256_set1_ps(self, a: f32) -> __m256 {
        unsafe { _mm256_set1_ps(a) }
    }
    #[doc = "See [`arch::_mm256_set1_epi8`]."]
    #[inline(always)]
    pub fn _mm256_set1_epi8(self, a: i8) -> __m256i {
        unsafe { _mm256_set1_epi8(a) }
    }
    #[doc = "See [`arch::_mm256_set1_epi16`]."]
    #[inline(always)]
    pub fn _mm256_set1_epi16(self, a: i16) -> __m256i {
        unsafe { _mm256_set1_epi16(a) }
    }
    #[doc = "See [`arch::_mm256_set1_epi32`]."]
    #[inline(always)]
    pub fn _mm256_set1_epi32(self, a: i32) -> __m256i {
        unsafe { _mm256_set1_epi32(a) }
    }
    #[doc = "See [`arch::_mm256_set1_epi64x`]."]
    #[inline(always)]
    pub fn _mm256_set1_epi64x(self, a: i64) -> __m256i {
        unsafe { _mm256_set1_epi64x(a) }
    }
    #[doc = "See [`arch::_mm256_castpd_ps`]."]
    #[inline(always)]
    pub fn _mm256_castpd_ps(self, a: __m256d) -> __m256 {
        unsafe { _mm256_castpd_ps(a) }
    }
    #[doc = "See [`arch::_mm256_castps_pd`]."]
    #[inline(always)]
    pub fn _mm256_castps_pd(self, a: __m256) -> __m256d {
        unsafe { _mm256_castps_pd(a) }
    }
    #[doc = "See [`arch::_mm256_castps_si256`]."]
    #[inline(always)]
    pub fn _mm256_castps_si256(self, a: __m256) -> __m256i {
        unsafe { _mm256_castps_si256(a) }
    }
    #[doc = "See [`arch::_mm256_castsi256_ps`]."]
    #[inline(always)]
    pub fn _mm256_castsi256_ps(self, a: __m256i) -> __m256 {
        unsafe { _mm256_castsi256_ps(a) }
    }
    #[doc = "See [`arch::_mm256_castpd_si256`]."]
    #[inline(always)]
    pub fn _mm256_castpd_si256(self, a: __m256d) -> __m256i {
        unsafe { _mm256_castpd_si256(a) }
    }
    #[doc = "See [`arch::_mm256_castsi256_pd`]."]
    #[inline(always)]
    pub fn _mm256_castsi256_pd(self, a: __m256i) -> __m256d {
        unsafe { _mm256_castsi256_pd(a) }
    }
    #[doc = "See [`arch::_mm256_castps256_ps128`]."]
    #[inline(always)]
    pub fn _mm256_castps256_ps128(self, a: __m256) -> __m128 {
        unsafe { _mm256_castps256_ps128(a) }
    }
    #[doc = "See [`arch::_mm256_castpd256_pd128`]."]
    #[inline(always)]
    pub fn _mm256_castpd256_pd128(self, a: __m256d) -> __m128d {
        unsafe { _mm256_castpd256_pd128(a) }
    }
    #[doc = "See [`arch::_mm256_castsi256_si128`]."]
    #[inline(always)]
    pub fn _mm256_castsi256_si128(self, a: __m256i) -> __m128i {
        unsafe { _mm256_castsi256_si128(a) }
    }
    #[doc = "See [`arch::_mm256_castps128_ps256`]."]
    #[inline(always)]
    pub fn _mm256_castps128_ps256(self, a: __m128) -> __m256 {
        unsafe { _mm256_castps128_ps256(a) }
    }
    #[doc = "See [`arch::_mm256_castpd128_pd256`]."]
    #[inline(always)]
    pub fn _mm256_castpd128_pd256(self, a: __m128d) -> __m256d {
        unsafe { _mm256_castpd128_pd256(a) }
    }
    #[doc = "See [`arch::_mm256_castsi128_si256`]."]
    #[inline(always)]
    pub fn _mm256_castsi128_si256(self, a: __m128i) -> __m256i {
        unsafe { _mm256_castsi128_si256(a) }
    }
    #[doc = "See [`arch::_mm256_zextps128_ps256`]."]
    #[inline(always)]
    pub fn _mm256_zextps128_ps256(self, a: __m128) -> __m256 {
        unsafe { _mm256_zextps128_ps256(a) }
    }
    #[doc = "See [`arch::_mm256_zextsi128_si256`]."]
    #[inline(always)]
    pub fn _mm256_zextsi128_si256(self, a: __m128i) -> __m256i {
        unsafe { _mm256_zextsi128_si256(a) }
    }
    #[doc = "See [`arch::_mm256_zextpd128_pd256`]."]
    #[inline(always)]
    pub fn _mm256_zextpd128_pd256(self, a: __m128d) -> __m256d {
        unsafe { _mm256_zextpd128_pd256(a) }
    }
    #[doc = "See [`arch::_mm256_undefined_ps`]."]
    #[inline(always)]
    pub fn _mm256_undefined_ps(self) -> __m256 {
        unsafe { _mm256_undefined_ps() }
    }
    #[doc = "See [`arch::_mm256_undefined_pd`]."]
    #[inline(always)]
    pub fn _mm256_undefined_pd(self) -> __m256d {
        unsafe { _mm256_undefined_pd() }
    }
    #[doc = "See [`arch::_mm256_undefined_si256`]."]
    #[inline(always)]
    pub fn _mm256_undefined_si256(self) -> __m256i {
        unsafe { _mm256_undefined_si256() }
    }
    #[doc = "See [`arch::_mm256_set_m128`]."]
    #[inline(always)]
    pub fn _mm256_set_m128(self, hi: __m128, lo: __m128) -> __m256 {
        unsafe { _mm256_set_m128(hi, lo) }
    }
    #[doc = "See [`arch::_mm256_set_m128d`]."]
    #[inline(always)]
    pub fn _mm256_set_m128d(self, hi: __m128d, lo: __m128d) -> __m256d {
        unsafe { _mm256_set_m128d(hi, lo) }
    }
    #[doc = "See [`arch::_mm256_set_m128i`]."]
    #[inline(always)]
    pub fn _mm256_set_m128i(self, hi: __m128i, lo: __m128i) -> __m256i {
        unsafe { _mm256_set_m128i(hi, lo) }
    }
    #[doc = "See [`arch::_mm256_setr_m128`]."]
    #[inline(always)]
    pub fn _mm256_setr_m128(self, lo: __m128, hi: __m128) -> __m256 {
        unsafe { _mm256_setr_m128(lo, hi) }
    }
    #[doc = "See [`arch::_mm256_setr_m128d`]."]
    #[inline(always)]
    pub fn _mm256_setr_m128d(self, lo: __m128d, hi: __m128d) -> __m256d {
        unsafe { _mm256_setr_m128d(lo, hi) }
    }
    #[doc = "See [`arch::_mm256_setr_m128i`]."]
    #[inline(always)]
    pub fn _mm256_setr_m128i(self, lo: __m128i, hi: __m128i) -> __m256i {
        unsafe { _mm256_setr_m128i(lo, hi) }
    }
    #[doc = "See [`arch::_mm256_loadu2_m128`]."]
    #[inline(always)]
    pub unsafe fn _mm256_loadu2_m128(self, hiaddr: *const f32, loaddr: *const f32) -> __m256 {
        unsafe { _mm256_loadu2_m128(hiaddr, loaddr) }
    }
    #[doc = "See [`arch::_mm256_loadu2_m128d`]."]
    #[inline(always)]
    pub unsafe fn _mm256_loadu2_m128d(self, hiaddr: *const f64, loaddr: *const f64) -> __m256d {
        unsafe { _mm256_loadu2_m128d(hiaddr, loaddr) }
    }
    #[doc = "See [`arch::_mm256_loadu2_m128i`]."]
    #[inline(always)]
    pub unsafe fn _mm256_loadu2_m128i(
        self,
        hiaddr: *const __m128i,
        loaddr: *const __m128i,
    ) -> __m256i {
        unsafe { _mm256_loadu2_m128i(hiaddr, loaddr) }
    }
    #[doc = "See [`arch::_mm256_storeu2_m128`]."]
    #[inline(always)]
    pub unsafe fn _mm256_storeu2_m128(self, hiaddr: *mut f32, loaddr: *mut f32, a: __m256) {
        unsafe { _mm256_storeu2_m128(hiaddr, loaddr, a) }
    }
    #[doc = "See [`arch::_mm256_storeu2_m128d`]."]
    #[inline(always)]
    pub unsafe fn _mm256_storeu2_m128d(self, hiaddr: *mut f64, loaddr: *mut f64, a: __m256d) {
        unsafe { _mm256_storeu2_m128d(hiaddr, loaddr, a) }
    }
    #[doc = "See [`arch::_mm256_storeu2_m128i`]."]
    #[inline(always)]
    pub unsafe fn _mm256_storeu2_m128i(
        self,
        hiaddr: *mut __m128i,
        loaddr: *mut __m128i,
        a: __m256i,
    ) {
        unsafe { _mm256_storeu2_m128i(hiaddr, loaddr, a) }
    }
    #[doc = "See [`arch::_mm256_cvtss_f32`]."]
    #[inline(always)]
    pub fn _mm256_cvtss_f32(self, a: __m256) -> f32 {
        unsafe { _mm256_cvtss_f32(a) }
    }
}
