// Copyright 2026 the Fearless_SIMD Authors
// SPDX-License-Identifier: Apache-2.0 OR MIT

// This file is autogenerated by fearless_simd_gen

use arch::*;
#[cfg(target_arch = "x86")]
use core::arch::x86 as arch;
#[cfg(target_arch = "x86_64")]
use core::arch::x86_64 as arch;
#[doc = "A token for `Fma` intrinsics on `x86` and `x86_64`."]
#[derive(Clone, Copy, Debug)]
pub struct Fma {
    _private: (),
}
#[allow(
    clippy::missing_safety_doc,
    reason = "The underlying functions have their own safety docs"
)]
impl Fma {
    #[doc = r" Create a SIMD token."]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" The required CPU features must be available."]
    #[inline]
    pub const unsafe fn new_unchecked() -> Self {
        Self { _private: () }
    }
    #[doc = "See [`arch::_mm_fmadd_pd`]."]
    #[inline(always)]
    pub fn _mm_fmadd_pd(self, a: __m128d, b: __m128d, c: __m128d) -> __m128d {
        unsafe { _mm_fmadd_pd(a, b, c) }
    }
    #[doc = "See [`arch::_mm256_fmadd_pd`]."]
    #[inline(always)]
    pub fn _mm256_fmadd_pd(self, a: __m256d, b: __m256d, c: __m256d) -> __m256d {
        unsafe { _mm256_fmadd_pd(a, b, c) }
    }
    #[doc = "See [`arch::_mm_fmadd_ps`]."]
    #[inline(always)]
    pub fn _mm_fmadd_ps(self, a: __m128, b: __m128, c: __m128) -> __m128 {
        unsafe { _mm_fmadd_ps(a, b, c) }
    }
    #[doc = "See [`arch::_mm256_fmadd_ps`]."]
    #[inline(always)]
    pub fn _mm256_fmadd_ps(self, a: __m256, b: __m256, c: __m256) -> __m256 {
        unsafe { _mm256_fmadd_ps(a, b, c) }
    }
    #[doc = "See [`arch::_mm_fmadd_sd`]."]
    #[inline(always)]
    pub fn _mm_fmadd_sd(self, a: __m128d, b: __m128d, c: __m128d) -> __m128d {
        unsafe { _mm_fmadd_sd(a, b, c) }
    }
    #[doc = "See [`arch::_mm_fmadd_ss`]."]
    #[inline(always)]
    pub fn _mm_fmadd_ss(self, a: __m128, b: __m128, c: __m128) -> __m128 {
        unsafe { _mm_fmadd_ss(a, b, c) }
    }
    #[doc = "See [`arch::_mm_fmaddsub_pd`]."]
    #[inline(always)]
    pub fn _mm_fmaddsub_pd(self, a: __m128d, b: __m128d, c: __m128d) -> __m128d {
        unsafe { _mm_fmaddsub_pd(a, b, c) }
    }
    #[doc = "See [`arch::_mm256_fmaddsub_pd`]."]
    #[inline(always)]
    pub fn _mm256_fmaddsub_pd(self, a: __m256d, b: __m256d, c: __m256d) -> __m256d {
        unsafe { _mm256_fmaddsub_pd(a, b, c) }
    }
    #[doc = "See [`arch::_mm_fmaddsub_ps`]."]
    #[inline(always)]
    pub fn _mm_fmaddsub_ps(self, a: __m128, b: __m128, c: __m128) -> __m128 {
        unsafe { _mm_fmaddsub_ps(a, b, c) }
    }
    #[doc = "See [`arch::_mm256_fmaddsub_ps`]."]
    #[inline(always)]
    pub fn _mm256_fmaddsub_ps(self, a: __m256, b: __m256, c: __m256) -> __m256 {
        unsafe { _mm256_fmaddsub_ps(a, b, c) }
    }
    #[doc = "See [`arch::_mm_fmsub_pd`]."]
    #[inline(always)]
    pub fn _mm_fmsub_pd(self, a: __m128d, b: __m128d, c: __m128d) -> __m128d {
        unsafe { _mm_fmsub_pd(a, b, c) }
    }
    #[doc = "See [`arch::_mm256_fmsub_pd`]."]
    #[inline(always)]
    pub fn _mm256_fmsub_pd(self, a: __m256d, b: __m256d, c: __m256d) -> __m256d {
        unsafe { _mm256_fmsub_pd(a, b, c) }
    }
    #[doc = "See [`arch::_mm_fmsub_ps`]."]
    #[inline(always)]
    pub fn _mm_fmsub_ps(self, a: __m128, b: __m128, c: __m128) -> __m128 {
        unsafe { _mm_fmsub_ps(a, b, c) }
    }
    #[doc = "See [`arch::_mm256_fmsub_ps`]."]
    #[inline(always)]
    pub fn _mm256_fmsub_ps(self, a: __m256, b: __m256, c: __m256) -> __m256 {
        unsafe { _mm256_fmsub_ps(a, b, c) }
    }
    #[doc = "See [`arch::_mm_fmsub_sd`]."]
    #[inline(always)]
    pub fn _mm_fmsub_sd(self, a: __m128d, b: __m128d, c: __m128d) -> __m128d {
        unsafe { _mm_fmsub_sd(a, b, c) }
    }
    #[doc = "See [`arch::_mm_fmsub_ss`]."]
    #[inline(always)]
    pub fn _mm_fmsub_ss(self, a: __m128, b: __m128, c: __m128) -> __m128 {
        unsafe { _mm_fmsub_ss(a, b, c) }
    }
    #[doc = "See [`arch::_mm_fmsubadd_pd`]."]
    #[inline(always)]
    pub fn _mm_fmsubadd_pd(self, a: __m128d, b: __m128d, c: __m128d) -> __m128d {
        unsafe { _mm_fmsubadd_pd(a, b, c) }
    }
    #[doc = "See [`arch::_mm256_fmsubadd_pd`]."]
    #[inline(always)]
    pub fn _mm256_fmsubadd_pd(self, a: __m256d, b: __m256d, c: __m256d) -> __m256d {
        unsafe { _mm256_fmsubadd_pd(a, b, c) }
    }
    #[doc = "See [`arch::_mm_fmsubadd_ps`]."]
    #[inline(always)]
    pub fn _mm_fmsubadd_ps(self, a: __m128, b: __m128, c: __m128) -> __m128 {
        unsafe { _mm_fmsubadd_ps(a, b, c) }
    }
    #[doc = "See [`arch::_mm256_fmsubadd_ps`]."]
    #[inline(always)]
    pub fn _mm256_fmsubadd_ps(self, a: __m256, b: __m256, c: __m256) -> __m256 {
        unsafe { _mm256_fmsubadd_ps(a, b, c) }
    }
    #[doc = "See [`arch::_mm_fnmadd_pd`]."]
    #[inline(always)]
    pub fn _mm_fnmadd_pd(self, a: __m128d, b: __m128d, c: __m128d) -> __m128d {
        unsafe { _mm_fnmadd_pd(a, b, c) }
    }
    #[doc = "See [`arch::_mm256_fnmadd_pd`]."]
    #[inline(always)]
    pub fn _mm256_fnmadd_pd(self, a: __m256d, b: __m256d, c: __m256d) -> __m256d {
        unsafe { _mm256_fnmadd_pd(a, b, c) }
    }
    #[doc = "See [`arch::_mm_fnmadd_ps`]."]
    #[inline(always)]
    pub fn _mm_fnmadd_ps(self, a: __m128, b: __m128, c: __m128) -> __m128 {
        unsafe { _mm_fnmadd_ps(a, b, c) }
    }
    #[doc = "See [`arch::_mm256_fnmadd_ps`]."]
    #[inline(always)]
    pub fn _mm256_fnmadd_ps(self, a: __m256, b: __m256, c: __m256) -> __m256 {
        unsafe { _mm256_fnmadd_ps(a, b, c) }
    }
    #[doc = "See [`arch::_mm_fnmadd_sd`]."]
    #[inline(always)]
    pub fn _mm_fnmadd_sd(self, a: __m128d, b: __m128d, c: __m128d) -> __m128d {
        unsafe { _mm_fnmadd_sd(a, b, c) }
    }
    #[doc = "See [`arch::_mm_fnmadd_ss`]."]
    #[inline(always)]
    pub fn _mm_fnmadd_ss(self, a: __m128, b: __m128, c: __m128) -> __m128 {
        unsafe { _mm_fnmadd_ss(a, b, c) }
    }
    #[doc = "See [`arch::_mm_fnmsub_pd`]."]
    #[inline(always)]
    pub fn _mm_fnmsub_pd(self, a: __m128d, b: __m128d, c: __m128d) -> __m128d {
        unsafe { _mm_fnmsub_pd(a, b, c) }
    }
    #[doc = "See [`arch::_mm256_fnmsub_pd`]."]
    #[inline(always)]
    pub fn _mm256_fnmsub_pd(self, a: __m256d, b: __m256d, c: __m256d) -> __m256d {
        unsafe { _mm256_fnmsub_pd(a, b, c) }
    }
    #[doc = "See [`arch::_mm_fnmsub_ps`]."]
    #[inline(always)]
    pub fn _mm_fnmsub_ps(self, a: __m128, b: __m128, c: __m128) -> __m128 {
        unsafe { _mm_fnmsub_ps(a, b, c) }
    }
    #[doc = "See [`arch::_mm256_fnmsub_ps`]."]
    #[inline(always)]
    pub fn _mm256_fnmsub_ps(self, a: __m256, b: __m256, c: __m256) -> __m256 {
        unsafe { _mm256_fnmsub_ps(a, b, c) }
    }
    #[doc = "See [`arch::_mm_fnmsub_sd`]."]
    #[inline(always)]
    pub fn _mm_fnmsub_sd(self, a: __m128d, b: __m128d, c: __m128d) -> __m128d {
        unsafe { _mm_fnmsub_sd(a, b, c) }
    }
    #[doc = "See [`arch::_mm_fnmsub_ss`]."]
    #[inline(always)]
    pub fn _mm_fnmsub_ss(self, a: __m128, b: __m128, c: __m128) -> __m128 {
        unsafe { _mm_fnmsub_ss(a, b, c) }
    }
}
