// Copyright 2026 the Fearless_SIMD Authors
// SPDX-License-Identifier: Apache-2.0 OR MIT

// This file is autogenerated by fearless_simd_gen

use arch::*;
#[cfg(target_arch = "x86")]
use core::arch::x86 as arch;
#[cfg(target_arch = "x86_64")]
use core::arch::x86_64 as arch;
#[doc = "A token for `Sse` intrinsics on `x86` and `x86_64`."]
#[derive(Clone, Copy, Debug)]
pub struct Sse {
    _private: (),
}
#[allow(
    clippy::missing_safety_doc,
    reason = "The underlying functions have their own safety docs"
)]
impl Sse {
    #[doc = r" Create a SIMD token."]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" The required CPU features must be available."]
    #[inline]
    pub const unsafe fn new_unchecked() -> Self {
        Self { _private: () }
    }
    #[doc = "See [`arch::_mm_add_ss`]."]
    #[inline(always)]
    pub fn _mm_add_ss(self, a: __m128, b: __m128) -> __m128 {
        unsafe { _mm_add_ss(a, b) }
    }
    #[doc = "See [`arch::_mm_add_ps`]."]
    #[inline(always)]
    pub fn _mm_add_ps(self, a: __m128, b: __m128) -> __m128 {
        unsafe { _mm_add_ps(a, b) }
    }
    #[doc = "See [`arch::_mm_sub_ss`]."]
    #[inline(always)]
    pub fn _mm_sub_ss(self, a: __m128, b: __m128) -> __m128 {
        unsafe { _mm_sub_ss(a, b) }
    }
    #[doc = "See [`arch::_mm_sub_ps`]."]
    #[inline(always)]
    pub fn _mm_sub_ps(self, a: __m128, b: __m128) -> __m128 {
        unsafe { _mm_sub_ps(a, b) }
    }
    #[doc = "See [`arch::_mm_mul_ss`]."]
    #[inline(always)]
    pub fn _mm_mul_ss(self, a: __m128, b: __m128) -> __m128 {
        unsafe { _mm_mul_ss(a, b) }
    }
    #[doc = "See [`arch::_mm_mul_ps`]."]
    #[inline(always)]
    pub fn _mm_mul_ps(self, a: __m128, b: __m128) -> __m128 {
        unsafe { _mm_mul_ps(a, b) }
    }
    #[doc = "See [`arch::_mm_div_ss`]."]
    #[inline(always)]
    pub fn _mm_div_ss(self, a: __m128, b: __m128) -> __m128 {
        unsafe { _mm_div_ss(a, b) }
    }
    #[doc = "See [`arch::_mm_div_ps`]."]
    #[inline(always)]
    pub fn _mm_div_ps(self, a: __m128, b: __m128) -> __m128 {
        unsafe { _mm_div_ps(a, b) }
    }
    #[doc = "See [`arch::_mm_sqrt_ss`]."]
    #[inline(always)]
    pub fn _mm_sqrt_ss(self, a: __m128) -> __m128 {
        unsafe { _mm_sqrt_ss(a) }
    }
    #[doc = "See [`arch::_mm_sqrt_ps`]."]
    #[inline(always)]
    pub fn _mm_sqrt_ps(self, a: __m128) -> __m128 {
        unsafe { _mm_sqrt_ps(a) }
    }
    #[doc = "See [`arch::_mm_rcp_ss`]."]
    #[inline(always)]
    pub fn _mm_rcp_ss(self, a: __m128) -> __m128 {
        unsafe { _mm_rcp_ss(a) }
    }
    #[doc = "See [`arch::_mm_rcp_ps`]."]
    #[inline(always)]
    pub fn _mm_rcp_ps(self, a: __m128) -> __m128 {
        unsafe { _mm_rcp_ps(a) }
    }
    #[doc = "See [`arch::_mm_rsqrt_ss`]."]
    #[inline(always)]
    pub fn _mm_rsqrt_ss(self, a: __m128) -> __m128 {
        unsafe { _mm_rsqrt_ss(a) }
    }
    #[doc = "See [`arch::_mm_rsqrt_ps`]."]
    #[inline(always)]
    pub fn _mm_rsqrt_ps(self, a: __m128) -> __m128 {
        unsafe { _mm_rsqrt_ps(a) }
    }
    #[doc = "See [`arch::_mm_min_ss`]."]
    #[inline(always)]
    pub fn _mm_min_ss(self, a: __m128, b: __m128) -> __m128 {
        unsafe { _mm_min_ss(a, b) }
    }
    #[doc = "See [`arch::_mm_min_ps`]."]
    #[inline(always)]
    pub fn _mm_min_ps(self, a: __m128, b: __m128) -> __m128 {
        unsafe { _mm_min_ps(a, b) }
    }
    #[doc = "See [`arch::_mm_max_ss`]."]
    #[inline(always)]
    pub fn _mm_max_ss(self, a: __m128, b: __m128) -> __m128 {
        unsafe { _mm_max_ss(a, b) }
    }
    #[doc = "See [`arch::_mm_max_ps`]."]
    #[inline(always)]
    pub fn _mm_max_ps(self, a: __m128, b: __m128) -> __m128 {
        unsafe { _mm_max_ps(a, b) }
    }
    #[doc = "See [`arch::_mm_and_ps`]."]
    #[inline(always)]
    pub fn _mm_and_ps(self, a: __m128, b: __m128) -> __m128 {
        unsafe { _mm_and_ps(a, b) }
    }
    #[doc = "See [`arch::_mm_andnot_ps`]."]
    #[inline(always)]
    pub fn _mm_andnot_ps(self, a: __m128, b: __m128) -> __m128 {
        unsafe { _mm_andnot_ps(a, b) }
    }
    #[doc = "See [`arch::_mm_or_ps`]."]
    #[inline(always)]
    pub fn _mm_or_ps(self, a: __m128, b: __m128) -> __m128 {
        unsafe { _mm_or_ps(a, b) }
    }
    #[doc = "See [`arch::_mm_xor_ps`]."]
    #[inline(always)]
    pub fn _mm_xor_ps(self, a: __m128, b: __m128) -> __m128 {
        unsafe { _mm_xor_ps(a, b) }
    }
    #[doc = "See [`arch::_mm_cmpeq_ss`]."]
    #[inline(always)]
    pub fn _mm_cmpeq_ss(self, a: __m128, b: __m128) -> __m128 {
        unsafe { _mm_cmpeq_ss(a, b) }
    }
    #[doc = "See [`arch::_mm_cmplt_ss`]."]
    #[inline(always)]
    pub fn _mm_cmplt_ss(self, a: __m128, b: __m128) -> __m128 {
        unsafe { _mm_cmplt_ss(a, b) }
    }
    #[doc = "See [`arch::_mm_cmple_ss`]."]
    #[inline(always)]
    pub fn _mm_cmple_ss(self, a: __m128, b: __m128) -> __m128 {
        unsafe { _mm_cmple_ss(a, b) }
    }
    #[doc = "See [`arch::_mm_cmpgt_ss`]."]
    #[inline(always)]
    pub fn _mm_cmpgt_ss(self, a: __m128, b: __m128) -> __m128 {
        unsafe { _mm_cmpgt_ss(a, b) }
    }
    #[doc = "See [`arch::_mm_cmpge_ss`]."]
    #[inline(always)]
    pub fn _mm_cmpge_ss(self, a: __m128, b: __m128) -> __m128 {
        unsafe { _mm_cmpge_ss(a, b) }
    }
    #[doc = "See [`arch::_mm_cmpneq_ss`]."]
    #[inline(always)]
    pub fn _mm_cmpneq_ss(self, a: __m128, b: __m128) -> __m128 {
        unsafe { _mm_cmpneq_ss(a, b) }
    }
    #[doc = "See [`arch::_mm_cmpnlt_ss`]."]
    #[inline(always)]
    pub fn _mm_cmpnlt_ss(self, a: __m128, b: __m128) -> __m128 {
        unsafe { _mm_cmpnlt_ss(a, b) }
    }
    #[doc = "See [`arch::_mm_cmpnle_ss`]."]
    #[inline(always)]
    pub fn _mm_cmpnle_ss(self, a: __m128, b: __m128) -> __m128 {
        unsafe { _mm_cmpnle_ss(a, b) }
    }
    #[doc = "See [`arch::_mm_cmpngt_ss`]."]
    #[inline(always)]
    pub fn _mm_cmpngt_ss(self, a: __m128, b: __m128) -> __m128 {
        unsafe { _mm_cmpngt_ss(a, b) }
    }
    #[doc = "See [`arch::_mm_cmpnge_ss`]."]
    #[inline(always)]
    pub fn _mm_cmpnge_ss(self, a: __m128, b: __m128) -> __m128 {
        unsafe { _mm_cmpnge_ss(a, b) }
    }
    #[doc = "See [`arch::_mm_cmpord_ss`]."]
    #[inline(always)]
    pub fn _mm_cmpord_ss(self, a: __m128, b: __m128) -> __m128 {
        unsafe { _mm_cmpord_ss(a, b) }
    }
    #[doc = "See [`arch::_mm_cmpunord_ss`]."]
    #[inline(always)]
    pub fn _mm_cmpunord_ss(self, a: __m128, b: __m128) -> __m128 {
        unsafe { _mm_cmpunord_ss(a, b) }
    }
    #[doc = "See [`arch::_mm_cmpeq_ps`]."]
    #[inline(always)]
    pub fn _mm_cmpeq_ps(self, a: __m128, b: __m128) -> __m128 {
        unsafe { _mm_cmpeq_ps(a, b) }
    }
    #[doc = "See [`arch::_mm_cmplt_ps`]."]
    #[inline(always)]
    pub fn _mm_cmplt_ps(self, a: __m128, b: __m128) -> __m128 {
        unsafe { _mm_cmplt_ps(a, b) }
    }
    #[doc = "See [`arch::_mm_cmple_ps`]."]
    #[inline(always)]
    pub fn _mm_cmple_ps(self, a: __m128, b: __m128) -> __m128 {
        unsafe { _mm_cmple_ps(a, b) }
    }
    #[doc = "See [`arch::_mm_cmpgt_ps`]."]
    #[inline(always)]
    pub fn _mm_cmpgt_ps(self, a: __m128, b: __m128) -> __m128 {
        unsafe { _mm_cmpgt_ps(a, b) }
    }
    #[doc = "See [`arch::_mm_cmpge_ps`]."]
    #[inline(always)]
    pub fn _mm_cmpge_ps(self, a: __m128, b: __m128) -> __m128 {
        unsafe { _mm_cmpge_ps(a, b) }
    }
    #[doc = "See [`arch::_mm_cmpneq_ps`]."]
    #[inline(always)]
    pub fn _mm_cmpneq_ps(self, a: __m128, b: __m128) -> __m128 {
        unsafe { _mm_cmpneq_ps(a, b) }
    }
    #[doc = "See [`arch::_mm_cmpnlt_ps`]."]
    #[inline(always)]
    pub fn _mm_cmpnlt_ps(self, a: __m128, b: __m128) -> __m128 {
        unsafe { _mm_cmpnlt_ps(a, b) }
    }
    #[doc = "See [`arch::_mm_cmpnle_ps`]."]
    #[inline(always)]
    pub fn _mm_cmpnle_ps(self, a: __m128, b: __m128) -> __m128 {
        unsafe { _mm_cmpnle_ps(a, b) }
    }
    #[doc = "See [`arch::_mm_cmpngt_ps`]."]
    #[inline(always)]
    pub fn _mm_cmpngt_ps(self, a: __m128, b: __m128) -> __m128 {
        unsafe { _mm_cmpngt_ps(a, b) }
    }
    #[doc = "See [`arch::_mm_cmpnge_ps`]."]
    #[inline(always)]
    pub fn _mm_cmpnge_ps(self, a: __m128, b: __m128) -> __m128 {
        unsafe { _mm_cmpnge_ps(a, b) }
    }
    #[doc = "See [`arch::_mm_cmpord_ps`]."]
    #[inline(always)]
    pub fn _mm_cmpord_ps(self, a: __m128, b: __m128) -> __m128 {
        unsafe { _mm_cmpord_ps(a, b) }
    }
    #[doc = "See [`arch::_mm_cmpunord_ps`]."]
    #[inline(always)]
    pub fn _mm_cmpunord_ps(self, a: __m128, b: __m128) -> __m128 {
        unsafe { _mm_cmpunord_ps(a, b) }
    }
    #[doc = "See [`arch::_mm_comieq_ss`]."]
    #[inline(always)]
    pub fn _mm_comieq_ss(self, a: __m128, b: __m128) -> i32 {
        unsafe { _mm_comieq_ss(a, b) }
    }
    #[doc = "See [`arch::_mm_comilt_ss`]."]
    #[inline(always)]
    pub fn _mm_comilt_ss(self, a: __m128, b: __m128) -> i32 {
        unsafe { _mm_comilt_ss(a, b) }
    }
    #[doc = "See [`arch::_mm_comile_ss`]."]
    #[inline(always)]
    pub fn _mm_comile_ss(self, a: __m128, b: __m128) -> i32 {
        unsafe { _mm_comile_ss(a, b) }
    }
    #[doc = "See [`arch::_mm_comigt_ss`]."]
    #[inline(always)]
    pub fn _mm_comigt_ss(self, a: __m128, b: __m128) -> i32 {
        unsafe { _mm_comigt_ss(a, b) }
    }
    #[doc = "See [`arch::_mm_comige_ss`]."]
    #[inline(always)]
    pub fn _mm_comige_ss(self, a: __m128, b: __m128) -> i32 {
        unsafe { _mm_comige_ss(a, b) }
    }
    #[doc = "See [`arch::_mm_comineq_ss`]."]
    #[inline(always)]
    pub fn _mm_comineq_ss(self, a: __m128, b: __m128) -> i32 {
        unsafe { _mm_comineq_ss(a, b) }
    }
    #[doc = "See [`arch::_mm_ucomieq_ss`]."]
    #[inline(always)]
    pub fn _mm_ucomieq_ss(self, a: __m128, b: __m128) -> i32 {
        unsafe { _mm_ucomieq_ss(a, b) }
    }
    #[doc = "See [`arch::_mm_ucomilt_ss`]."]
    #[inline(always)]
    pub fn _mm_ucomilt_ss(self, a: __m128, b: __m128) -> i32 {
        unsafe { _mm_ucomilt_ss(a, b) }
    }
    #[doc = "See [`arch::_mm_ucomile_ss`]."]
    #[inline(always)]
    pub fn _mm_ucomile_ss(self, a: __m128, b: __m128) -> i32 {
        unsafe { _mm_ucomile_ss(a, b) }
    }
    #[doc = "See [`arch::_mm_ucomigt_ss`]."]
    #[inline(always)]
    pub fn _mm_ucomigt_ss(self, a: __m128, b: __m128) -> i32 {
        unsafe { _mm_ucomigt_ss(a, b) }
    }
    #[doc = "See [`arch::_mm_ucomige_ss`]."]
    #[inline(always)]
    pub fn _mm_ucomige_ss(self, a: __m128, b: __m128) -> i32 {
        unsafe { _mm_ucomige_ss(a, b) }
    }
    #[doc = "See [`arch::_mm_ucomineq_ss`]."]
    #[inline(always)]
    pub fn _mm_ucomineq_ss(self, a: __m128, b: __m128) -> i32 {
        unsafe { _mm_ucomineq_ss(a, b) }
    }
    #[doc = "See [`arch::_mm_cvtss_si32`]."]
    #[inline(always)]
    pub fn _mm_cvtss_si32(self, a: __m128) -> i32 {
        unsafe { _mm_cvtss_si32(a) }
    }
    #[doc = "See [`arch::_mm_cvt_ss2si`]."]
    #[inline(always)]
    pub fn _mm_cvt_ss2si(self, a: __m128) -> i32 {
        unsafe { _mm_cvt_ss2si(a) }
    }
    #[doc = "See [`arch::_mm_cvttss_si32`]."]
    #[inline(always)]
    pub fn _mm_cvttss_si32(self, a: __m128) -> i32 {
        unsafe { _mm_cvttss_si32(a) }
    }
    #[doc = "See [`arch::_mm_cvtt_ss2si`]."]
    #[inline(always)]
    pub fn _mm_cvtt_ss2si(self, a: __m128) -> i32 {
        unsafe { _mm_cvtt_ss2si(a) }
    }
    #[doc = "See [`arch::_mm_cvtss_f32`]."]
    #[inline(always)]
    pub fn _mm_cvtss_f32(self, a: __m128) -> f32 {
        unsafe { _mm_cvtss_f32(a) }
    }
    #[doc = "See [`arch::_mm_cvtsi32_ss`]."]
    #[inline(always)]
    pub fn _mm_cvtsi32_ss(self, a: __m128, b: i32) -> __m128 {
        unsafe { _mm_cvtsi32_ss(a, b) }
    }
    #[doc = "See [`arch::_mm_cvt_si2ss`]."]
    #[inline(always)]
    pub fn _mm_cvt_si2ss(self, a: __m128, b: i32) -> __m128 {
        unsafe { _mm_cvt_si2ss(a, b) }
    }
    #[doc = "See [`arch::_mm_set_ss`]."]
    #[inline(always)]
    pub fn _mm_set_ss(self, a: f32) -> __m128 {
        unsafe { _mm_set_ss(a) }
    }
    #[doc = "See [`arch::_mm_set1_ps`]."]
    #[inline(always)]
    pub fn _mm_set1_ps(self, a: f32) -> __m128 {
        unsafe { _mm_set1_ps(a) }
    }
    #[doc = "See [`arch::_mm_set_ps1`]."]
    #[inline(always)]
    pub fn _mm_set_ps1(self, a: f32) -> __m128 {
        unsafe { _mm_set_ps1(a) }
    }
    #[doc = "See [`arch::_mm_set_ps`]."]
    #[inline(always)]
    pub fn _mm_set_ps(self, a: f32, b: f32, c: f32, d: f32) -> __m128 {
        unsafe { _mm_set_ps(a, b, c, d) }
    }
    #[doc = "See [`arch::_mm_setr_ps`]."]
    #[inline(always)]
    pub fn _mm_setr_ps(self, a: f32, b: f32, c: f32, d: f32) -> __m128 {
        unsafe { _mm_setr_ps(a, b, c, d) }
    }
    #[doc = "See [`arch::_mm_setzero_ps`]."]
    #[inline(always)]
    pub fn _mm_setzero_ps(self) -> __m128 {
        unsafe { _mm_setzero_ps() }
    }
    #[doc = "See [`arch::_mm_shuffle_ps`]."]
    #[inline(always)]
    pub fn _mm_shuffle_ps<const MASK: i32>(self, a: __m128, b: __m128) -> __m128 {
        unsafe { _mm_shuffle_ps::<MASK>(a, b) }
    }
    #[doc = "See [`arch::_mm_unpackhi_ps`]."]
    #[inline(always)]
    pub fn _mm_unpackhi_ps(self, a: __m128, b: __m128) -> __m128 {
        unsafe { _mm_unpackhi_ps(a, b) }
    }
    #[doc = "See [`arch::_mm_unpacklo_ps`]."]
    #[inline(always)]
    pub fn _mm_unpacklo_ps(self, a: __m128, b: __m128) -> __m128 {
        unsafe { _mm_unpacklo_ps(a, b) }
    }
    #[doc = "See [`arch::_mm_movehl_ps`]."]
    #[inline(always)]
    pub fn _mm_movehl_ps(self, a: __m128, b: __m128) -> __m128 {
        unsafe { _mm_movehl_ps(a, b) }
    }
    #[doc = "See [`arch::_mm_movelh_ps`]."]
    #[inline(always)]
    pub fn _mm_movelh_ps(self, a: __m128, b: __m128) -> __m128 {
        unsafe { _mm_movelh_ps(a, b) }
    }
    #[doc = "See [`arch::_mm_movemask_ps`]."]
    #[inline(always)]
    pub fn _mm_movemask_ps(self, a: __m128) -> i32 {
        unsafe { _mm_movemask_ps(a) }
    }
    #[doc = "See [`arch::_mm_load_ss`]."]
    #[inline(always)]
    pub unsafe fn _mm_load_ss(self, p: *const f32) -> __m128 {
        unsafe { _mm_load_ss(p) }
    }
    #[doc = "See [`arch::_mm_load1_ps`]."]
    #[inline(always)]
    pub unsafe fn _mm_load1_ps(self, p: *const f32) -> __m128 {
        unsafe { _mm_load1_ps(p) }
    }
    #[doc = "See [`arch::_mm_load_ps1`]."]
    #[inline(always)]
    pub unsafe fn _mm_load_ps1(self, p: *const f32) -> __m128 {
        unsafe { _mm_load_ps1(p) }
    }
    #[doc = "See [`arch::_mm_load_ps`]."]
    #[allow(clippy::cast_ptr_alignment)]
    #[inline(always)]
    pub unsafe fn _mm_load_ps(self, p: *const f32) -> __m128 {
        unsafe { _mm_load_ps(p) }
    }
    #[doc = "See [`arch::_mm_loadu_ps`]."]
    #[inline(always)]
    pub unsafe fn _mm_loadu_ps(self, p: *const f32) -> __m128 {
        unsafe { _mm_loadu_ps(p) }
    }
    #[doc = "See [`arch::_mm_loadr_ps`]."]
    #[inline(always)]
    pub unsafe fn _mm_loadr_ps(self, p: *const f32) -> __m128 {
        unsafe { _mm_loadr_ps(p) }
    }
    #[doc = "See [`arch::_mm_store_ss`]."]
    #[inline(always)]
    pub unsafe fn _mm_store_ss(self, p: *mut f32, a: __m128) {
        unsafe { _mm_store_ss(p, a) }
    }
    #[doc = "See [`arch::_mm_store1_ps`]."]
    #[allow(clippy::cast_ptr_alignment)]
    #[inline(always)]
    pub unsafe fn _mm_store1_ps(self, p: *mut f32, a: __m128) {
        unsafe { _mm_store1_ps(p, a) }
    }
    #[doc = "See [`arch::_mm_store_ps1`]."]
    #[inline(always)]
    pub unsafe fn _mm_store_ps1(self, p: *mut f32, a: __m128) {
        unsafe { _mm_store_ps1(p, a) }
    }
    #[doc = "See [`arch::_mm_store_ps`]."]
    #[allow(clippy::cast_ptr_alignment)]
    #[inline(always)]
    pub unsafe fn _mm_store_ps(self, p: *mut f32, a: __m128) {
        unsafe { _mm_store_ps(p, a) }
    }
    #[doc = "See [`arch::_mm_storeu_ps`]."]
    #[inline(always)]
    pub unsafe fn _mm_storeu_ps(self, p: *mut f32, a: __m128) {
        unsafe { _mm_storeu_ps(p, a) }
    }
    #[doc = "See [`arch::_mm_storer_ps`]."]
    #[allow(clippy::cast_ptr_alignment)]
    #[inline(always)]
    pub unsafe fn _mm_storer_ps(self, p: *mut f32, a: __m128) {
        unsafe { _mm_storer_ps(p, a) }
    }
    #[doc = "See [`arch::_mm_move_ss`]."]
    #[inline(always)]
    pub fn _mm_move_ss(self, a: __m128, b: __m128) -> __m128 {
        unsafe { _mm_move_ss(a, b) }
    }
    #[doc = "See [`arch::_mm_sfence`]."]
    #[inline(always)]
    pub fn _mm_sfence(self) {
        unsafe { _mm_sfence() }
    }
    #[doc = "See [`arch::_mm_getcsr`]."]
    #[deprecated(
        since = "1.75.0",
        note = "see `_mm_getcsr` documentation - use inline assembly instead"
    )]
    #[inline(always)]
    pub unsafe fn _mm_getcsr(self) -> u32 {
        unsafe { _mm_getcsr() }
    }
    #[doc = "See [`arch::_mm_setcsr`]."]
    #[deprecated(
        since = "1.75.0",
        note = "see `_mm_setcsr` documentation - use inline assembly instead"
    )]
    #[inline(always)]
    pub unsafe fn _mm_setcsr(self, val: u32) {
        unsafe { _mm_setcsr(val) }
    }
    #[doc = "See [`arch::_MM_GET_EXCEPTION_MASK`]."]
    #[allow(deprecated)]
    #[allow(non_snake_case)]
    #[deprecated(
        since = "1.75.0",
        note = "see `_mm_getcsr` documentation - use inline assembly instead"
    )]
    #[inline(always)]
    pub unsafe fn _MM_GET_EXCEPTION_MASK(self) -> u32 {
        unsafe { _MM_GET_EXCEPTION_MASK() }
    }
    #[doc = "See [`arch::_MM_GET_EXCEPTION_STATE`]."]
    #[allow(deprecated)]
    #[allow(non_snake_case)]
    #[deprecated(
        since = "1.75.0",
        note = "see `_mm_getcsr` documentation - use inline assembly instead"
    )]
    #[inline(always)]
    pub unsafe fn _MM_GET_EXCEPTION_STATE(self) -> u32 {
        unsafe { _MM_GET_EXCEPTION_STATE() }
    }
    #[doc = "See [`arch::_MM_GET_FLUSH_ZERO_MODE`]."]
    #[allow(deprecated)]
    #[allow(non_snake_case)]
    #[deprecated(
        since = "1.75.0",
        note = "see `_mm_getcsr` documentation - use inline assembly instead"
    )]
    #[inline(always)]
    pub unsafe fn _MM_GET_FLUSH_ZERO_MODE(self) -> u32 {
        unsafe { _MM_GET_FLUSH_ZERO_MODE() }
    }
    #[doc = "See [`arch::_MM_GET_ROUNDING_MODE`]."]
    #[allow(deprecated)]
    #[allow(non_snake_case)]
    #[deprecated(
        since = "1.75.0",
        note = "see `_mm_getcsr` documentation - use inline assembly instead"
    )]
    #[inline(always)]
    pub unsafe fn _MM_GET_ROUNDING_MODE(self) -> u32 {
        unsafe { _MM_GET_ROUNDING_MODE() }
    }
    #[doc = "See [`arch::_MM_SET_EXCEPTION_MASK`]."]
    #[allow(deprecated)]
    #[allow(non_snake_case)]
    #[deprecated(
        since = "1.75.0",
        note = "see `_mm_setcsr` documentation - use inline assembly instead"
    )]
    #[inline(always)]
    pub unsafe fn _MM_SET_EXCEPTION_MASK(self, x: u32) {
        unsafe { _MM_SET_EXCEPTION_MASK(x) }
    }
    #[doc = "See [`arch::_MM_SET_EXCEPTION_STATE`]."]
    #[allow(deprecated)]
    #[allow(non_snake_case)]
    #[deprecated(
        since = "1.75.0",
        note = "see `_mm_setcsr` documentation - use inline assembly instead"
    )]
    #[inline(always)]
    pub unsafe fn _MM_SET_EXCEPTION_STATE(self, x: u32) {
        unsafe { _MM_SET_EXCEPTION_STATE(x) }
    }
    #[doc = "See [`arch::_MM_SET_FLUSH_ZERO_MODE`]."]
    #[allow(deprecated)]
    #[allow(non_snake_case)]
    #[deprecated(
        since = "1.75.0",
        note = "see `_mm_setcsr` documentation - use inline assembly instead"
    )]
    #[inline(always)]
    pub unsafe fn _MM_SET_FLUSH_ZERO_MODE(self, x: u32) {
        unsafe { _MM_SET_FLUSH_ZERO_MODE(x) }
    }
    #[doc = "See [`arch::_MM_SET_ROUNDING_MODE`]."]
    #[allow(deprecated)]
    #[allow(non_snake_case)]
    #[deprecated(
        since = "1.75.0",
        note = "see `_mm_setcsr` documentation - use inline assembly instead"
    )]
    #[inline(always)]
    pub unsafe fn _MM_SET_ROUNDING_MODE(self, x: u32) {
        unsafe { _MM_SET_ROUNDING_MODE(x) }
    }
    #[doc = "See [`arch::_mm_prefetch`]."]
    #[inline(always)]
    pub fn _mm_prefetch<const STRATEGY: i32>(self, p: *const i8) {
        unsafe { _mm_prefetch::<STRATEGY>(p) }
    }
    #[doc = "See [`arch::_mm_undefined_ps`]."]
    #[inline(always)]
    pub fn _mm_undefined_ps(self) -> __m128 {
        unsafe { _mm_undefined_ps() }
    }
    #[doc = "See [`arch::_MM_TRANSPOSE4_PS`]."]
    #[allow(non_snake_case)]
    #[inline(always)]
    pub fn _MM_TRANSPOSE4_PS(
        self,
        row0: &mut __m128,
        row1: &mut __m128,
        row2: &mut __m128,
        row3: &mut __m128,
    ) {
        unsafe { _MM_TRANSPOSE4_PS(row0, row1, row2, row3) }
    }
    #[doc = "See [`arch::_mm_stream_ps`]."]
    #[allow(clippy::cast_ptr_alignment)]
    #[inline(always)]
    pub unsafe fn _mm_stream_ps(self, mem_addr: *mut f32, a: __m128) {
        unsafe { _mm_stream_ps(mem_addr, a) }
    }
}
