// Copyright 2026 the Fearless_SIMD Authors
// SPDX-License-Identifier: Apache-2.0 OR MIT

// This file is autogenerated by fearless_simd_gen

use arch::*;
#[cfg(target_arch = "x86")]
use core::arch::x86 as arch;
#[cfg(target_arch = "x86_64")]
use core::arch::x86_64 as arch;
#[doc = "A token for `Sse2` intrinsics on `x86` and `x86_64`."]
#[derive(Clone, Copy, Debug)]
pub struct Sse2 {
    _private: (),
}
#[allow(
    clippy::missing_safety_doc,
    reason = "The underlying functions have their own safety docs"
)]
impl Sse2 {
    #[doc = r" Create a SIMD token."]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" The required CPU features must be available."]
    #[inline]
    pub const unsafe fn new_unchecked() -> Self {
        Self { _private: () }
    }
    #[doc = "See [`arch::_mm_clflush`]."]
    #[inline(always)]
    pub unsafe fn _mm_clflush(self, p: *const u8) {
        unsafe { _mm_clflush(p) }
    }
    #[doc = "See [`arch::_mm_lfence`]."]
    #[inline(always)]
    pub fn _mm_lfence(self) {
        unsafe { _mm_lfence() }
    }
    #[doc = "See [`arch::_mm_mfence`]."]
    #[inline(always)]
    pub fn _mm_mfence(self) {
        unsafe { _mm_mfence() }
    }
    #[doc = "See [`arch::_mm_add_epi8`]."]
    #[inline(always)]
    pub fn _mm_add_epi8(self, a: __m128i, b: __m128i) -> __m128i {
        unsafe { _mm_add_epi8(a, b) }
    }
    #[doc = "See [`arch::_mm_add_epi16`]."]
    #[inline(always)]
    pub fn _mm_add_epi16(self, a: __m128i, b: __m128i) -> __m128i {
        unsafe { _mm_add_epi16(a, b) }
    }
    #[doc = "See [`arch::_mm_add_epi32`]."]
    #[inline(always)]
    pub fn _mm_add_epi32(self, a: __m128i, b: __m128i) -> __m128i {
        unsafe { _mm_add_epi32(a, b) }
    }
    #[doc = "See [`arch::_mm_add_epi64`]."]
    #[inline(always)]
    pub fn _mm_add_epi64(self, a: __m128i, b: __m128i) -> __m128i {
        unsafe { _mm_add_epi64(a, b) }
    }
    #[doc = "See [`arch::_mm_adds_epi8`]."]
    #[inline(always)]
    pub fn _mm_adds_epi8(self, a: __m128i, b: __m128i) -> __m128i {
        unsafe { _mm_adds_epi8(a, b) }
    }
    #[doc = "See [`arch::_mm_adds_epi16`]."]
    #[inline(always)]
    pub fn _mm_adds_epi16(self, a: __m128i, b: __m128i) -> __m128i {
        unsafe { _mm_adds_epi16(a, b) }
    }
    #[doc = "See [`arch::_mm_adds_epu8`]."]
    #[inline(always)]
    pub fn _mm_adds_epu8(self, a: __m128i, b: __m128i) -> __m128i {
        unsafe { _mm_adds_epu8(a, b) }
    }
    #[doc = "See [`arch::_mm_adds_epu16`]."]
    #[inline(always)]
    pub fn _mm_adds_epu16(self, a: __m128i, b: __m128i) -> __m128i {
        unsafe { _mm_adds_epu16(a, b) }
    }
    #[doc = "See [`arch::_mm_avg_epu8`]."]
    #[inline(always)]
    pub fn _mm_avg_epu8(self, a: __m128i, b: __m128i) -> __m128i {
        unsafe { _mm_avg_epu8(a, b) }
    }
    #[doc = "See [`arch::_mm_avg_epu16`]."]
    #[inline(always)]
    pub fn _mm_avg_epu16(self, a: __m128i, b: __m128i) -> __m128i {
        unsafe { _mm_avg_epu16(a, b) }
    }
    #[doc = "See [`arch::_mm_madd_epi16`]."]
    #[inline(always)]
    pub fn _mm_madd_epi16(self, a: __m128i, b: __m128i) -> __m128i {
        unsafe { _mm_madd_epi16(a, b) }
    }
    #[doc = "See [`arch::_mm_max_epi16`]."]
    #[inline(always)]
    pub fn _mm_max_epi16(self, a: __m128i, b: __m128i) -> __m128i {
        unsafe { _mm_max_epi16(a, b) }
    }
    #[doc = "See [`arch::_mm_max_epu8`]."]
    #[inline(always)]
    pub fn _mm_max_epu8(self, a: __m128i, b: __m128i) -> __m128i {
        unsafe { _mm_max_epu8(a, b) }
    }
    #[doc = "See [`arch::_mm_min_epi16`]."]
    #[inline(always)]
    pub fn _mm_min_epi16(self, a: __m128i, b: __m128i) -> __m128i {
        unsafe { _mm_min_epi16(a, b) }
    }
    #[doc = "See [`arch::_mm_min_epu8`]."]
    #[inline(always)]
    pub fn _mm_min_epu8(self, a: __m128i, b: __m128i) -> __m128i {
        unsafe { _mm_min_epu8(a, b) }
    }
    #[doc = "See [`arch::_mm_mulhi_epi16`]."]
    #[inline(always)]
    pub fn _mm_mulhi_epi16(self, a: __m128i, b: __m128i) -> __m128i {
        unsafe { _mm_mulhi_epi16(a, b) }
    }
    #[doc = "See [`arch::_mm_mulhi_epu16`]."]
    #[inline(always)]
    pub fn _mm_mulhi_epu16(self, a: __m128i, b: __m128i) -> __m128i {
        unsafe { _mm_mulhi_epu16(a, b) }
    }
    #[doc = "See [`arch::_mm_mullo_epi16`]."]
    #[inline(always)]
    pub fn _mm_mullo_epi16(self, a: __m128i, b: __m128i) -> __m128i {
        unsafe { _mm_mullo_epi16(a, b) }
    }
    #[doc = "See [`arch::_mm_mul_epu32`]."]
    #[inline(always)]
    pub fn _mm_mul_epu32(self, a: __m128i, b: __m128i) -> __m128i {
        unsafe { _mm_mul_epu32(a, b) }
    }
    #[doc = "See [`arch::_mm_sad_epu8`]."]
    #[inline(always)]
    pub fn _mm_sad_epu8(self, a: __m128i, b: __m128i) -> __m128i {
        unsafe { _mm_sad_epu8(a, b) }
    }
    #[doc = "See [`arch::_mm_sub_epi8`]."]
    #[inline(always)]
    pub fn _mm_sub_epi8(self, a: __m128i, b: __m128i) -> __m128i {
        unsafe { _mm_sub_epi8(a, b) }
    }
    #[doc = "See [`arch::_mm_sub_epi16`]."]
    #[inline(always)]
    pub fn _mm_sub_epi16(self, a: __m128i, b: __m128i) -> __m128i {
        unsafe { _mm_sub_epi16(a, b) }
    }
    #[doc = "See [`arch::_mm_sub_epi32`]."]
    #[inline(always)]
    pub fn _mm_sub_epi32(self, a: __m128i, b: __m128i) -> __m128i {
        unsafe { _mm_sub_epi32(a, b) }
    }
    #[doc = "See [`arch::_mm_sub_epi64`]."]
    #[inline(always)]
    pub fn _mm_sub_epi64(self, a: __m128i, b: __m128i) -> __m128i {
        unsafe { _mm_sub_epi64(a, b) }
    }
    #[doc = "See [`arch::_mm_subs_epi8`]."]
    #[inline(always)]
    pub fn _mm_subs_epi8(self, a: __m128i, b: __m128i) -> __m128i {
        unsafe { _mm_subs_epi8(a, b) }
    }
    #[doc = "See [`arch::_mm_subs_epi16`]."]
    #[inline(always)]
    pub fn _mm_subs_epi16(self, a: __m128i, b: __m128i) -> __m128i {
        unsafe { _mm_subs_epi16(a, b) }
    }
    #[doc = "See [`arch::_mm_subs_epu8`]."]
    #[inline(always)]
    pub fn _mm_subs_epu8(self, a: __m128i, b: __m128i) -> __m128i {
        unsafe { _mm_subs_epu8(a, b) }
    }
    #[doc = "See [`arch::_mm_subs_epu16`]."]
    #[inline(always)]
    pub fn _mm_subs_epu16(self, a: __m128i, b: __m128i) -> __m128i {
        unsafe { _mm_subs_epu16(a, b) }
    }
    #[doc = "See [`arch::_mm_slli_si128`]."]
    #[inline(always)]
    pub fn _mm_slli_si128<const IMM8: i32>(self, a: __m128i) -> __m128i {
        unsafe { _mm_slli_si128::<IMM8>(a) }
    }
    #[doc = "See [`arch::_mm_bslli_si128`]."]
    #[inline(always)]
    pub fn _mm_bslli_si128<const IMM8: i32>(self, a: __m128i) -> __m128i {
        unsafe { _mm_bslli_si128::<IMM8>(a) }
    }
    #[doc = "See [`arch::_mm_bsrli_si128`]."]
    #[inline(always)]
    pub fn _mm_bsrli_si128<const IMM8: i32>(self, a: __m128i) -> __m128i {
        unsafe { _mm_bsrli_si128::<IMM8>(a) }
    }
    #[doc = "See [`arch::_mm_slli_epi16`]."]
    #[inline(always)]
    pub fn _mm_slli_epi16<const IMM8: i32>(self, a: __m128i) -> __m128i {
        unsafe { _mm_slli_epi16::<IMM8>(a) }
    }
    #[doc = "See [`arch::_mm_sll_epi16`]."]
    #[inline(always)]
    pub fn _mm_sll_epi16(self, a: __m128i, count: __m128i) -> __m128i {
        unsafe { _mm_sll_epi16(a, count) }
    }
    #[doc = "See [`arch::_mm_slli_epi32`]."]
    #[inline(always)]
    pub fn _mm_slli_epi32<const IMM8: i32>(self, a: __m128i) -> __m128i {
        unsafe { _mm_slli_epi32::<IMM8>(a) }
    }
    #[doc = "See [`arch::_mm_sll_epi32`]."]
    #[inline(always)]
    pub fn _mm_sll_epi32(self, a: __m128i, count: __m128i) -> __m128i {
        unsafe { _mm_sll_epi32(a, count) }
    }
    #[doc = "See [`arch::_mm_slli_epi64`]."]
    #[inline(always)]
    pub fn _mm_slli_epi64<const IMM8: i32>(self, a: __m128i) -> __m128i {
        unsafe { _mm_slli_epi64::<IMM8>(a) }
    }
    #[doc = "See [`arch::_mm_sll_epi64`]."]
    #[inline(always)]
    pub fn _mm_sll_epi64(self, a: __m128i, count: __m128i) -> __m128i {
        unsafe { _mm_sll_epi64(a, count) }
    }
    #[doc = "See [`arch::_mm_srai_epi16`]."]
    #[inline(always)]
    pub fn _mm_srai_epi16<const IMM8: i32>(self, a: __m128i) -> __m128i {
        unsafe { _mm_srai_epi16::<IMM8>(a) }
    }
    #[doc = "See [`arch::_mm_sra_epi16`]."]
    #[inline(always)]
    pub fn _mm_sra_epi16(self, a: __m128i, count: __m128i) -> __m128i {
        unsafe { _mm_sra_epi16(a, count) }
    }
    #[doc = "See [`arch::_mm_srai_epi32`]."]
    #[inline(always)]
    pub fn _mm_srai_epi32<const IMM8: i32>(self, a: __m128i) -> __m128i {
        unsafe { _mm_srai_epi32::<IMM8>(a) }
    }
    #[doc = "See [`arch::_mm_sra_epi32`]."]
    #[inline(always)]
    pub fn _mm_sra_epi32(self, a: __m128i, count: __m128i) -> __m128i {
        unsafe { _mm_sra_epi32(a, count) }
    }
    #[doc = "See [`arch::_mm_srli_si128`]."]
    #[inline(always)]
    pub fn _mm_srli_si128<const IMM8: i32>(self, a: __m128i) -> __m128i {
        unsafe { _mm_srli_si128::<IMM8>(a) }
    }
    #[doc = "See [`arch::_mm_srli_epi16`]."]
    #[inline(always)]
    pub fn _mm_srli_epi16<const IMM8: i32>(self, a: __m128i) -> __m128i {
        unsafe { _mm_srli_epi16::<IMM8>(a) }
    }
    #[doc = "See [`arch::_mm_srl_epi16`]."]
    #[inline(always)]
    pub fn _mm_srl_epi16(self, a: __m128i, count: __m128i) -> __m128i {
        unsafe { _mm_srl_epi16(a, count) }
    }
    #[doc = "See [`arch::_mm_srli_epi32`]."]
    #[inline(always)]
    pub fn _mm_srli_epi32<const IMM8: i32>(self, a: __m128i) -> __m128i {
        unsafe { _mm_srli_epi32::<IMM8>(a) }
    }
    #[doc = "See [`arch::_mm_srl_epi32`]."]
    #[inline(always)]
    pub fn _mm_srl_epi32(self, a: __m128i, count: __m128i) -> __m128i {
        unsafe { _mm_srl_epi32(a, count) }
    }
    #[doc = "See [`arch::_mm_srli_epi64`]."]
    #[inline(always)]
    pub fn _mm_srli_epi64<const IMM8: i32>(self, a: __m128i) -> __m128i {
        unsafe { _mm_srli_epi64::<IMM8>(a) }
    }
    #[doc = "See [`arch::_mm_srl_epi64`]."]
    #[inline(always)]
    pub fn _mm_srl_epi64(self, a: __m128i, count: __m128i) -> __m128i {
        unsafe { _mm_srl_epi64(a, count) }
    }
    #[doc = "See [`arch::_mm_and_si128`]."]
    #[inline(always)]
    pub fn _mm_and_si128(self, a: __m128i, b: __m128i) -> __m128i {
        unsafe { _mm_and_si128(a, b) }
    }
    #[doc = "See [`arch::_mm_andnot_si128`]."]
    #[inline(always)]
    pub fn _mm_andnot_si128(self, a: __m128i, b: __m128i) -> __m128i {
        unsafe { _mm_andnot_si128(a, b) }
    }
    #[doc = "See [`arch::_mm_or_si128`]."]
    #[inline(always)]
    pub fn _mm_or_si128(self, a: __m128i, b: __m128i) -> __m128i {
        unsafe { _mm_or_si128(a, b) }
    }
    #[doc = "See [`arch::_mm_xor_si128`]."]
    #[inline(always)]
    pub fn _mm_xor_si128(self, a: __m128i, b: __m128i) -> __m128i {
        unsafe { _mm_xor_si128(a, b) }
    }
    #[doc = "See [`arch::_mm_cmpeq_epi8`]."]
    #[inline(always)]
    pub fn _mm_cmpeq_epi8(self, a: __m128i, b: __m128i) -> __m128i {
        unsafe { _mm_cmpeq_epi8(a, b) }
    }
    #[doc = "See [`arch::_mm_cmpeq_epi16`]."]
    #[inline(always)]
    pub fn _mm_cmpeq_epi16(self, a: __m128i, b: __m128i) -> __m128i {
        unsafe { _mm_cmpeq_epi16(a, b) }
    }
    #[doc = "See [`arch::_mm_cmpeq_epi32`]."]
    #[inline(always)]
    pub fn _mm_cmpeq_epi32(self, a: __m128i, b: __m128i) -> __m128i {
        unsafe { _mm_cmpeq_epi32(a, b) }
    }
    #[doc = "See [`arch::_mm_cmpgt_epi8`]."]
    #[inline(always)]
    pub fn _mm_cmpgt_epi8(self, a: __m128i, b: __m128i) -> __m128i {
        unsafe { _mm_cmpgt_epi8(a, b) }
    }
    #[doc = "See [`arch::_mm_cmpgt_epi16`]."]
    #[inline(always)]
    pub fn _mm_cmpgt_epi16(self, a: __m128i, b: __m128i) -> __m128i {
        unsafe { _mm_cmpgt_epi16(a, b) }
    }
    #[doc = "See [`arch::_mm_cmpgt_epi32`]."]
    #[inline(always)]
    pub fn _mm_cmpgt_epi32(self, a: __m128i, b: __m128i) -> __m128i {
        unsafe { _mm_cmpgt_epi32(a, b) }
    }
    #[doc = "See [`arch::_mm_cmplt_epi8`]."]
    #[inline(always)]
    pub fn _mm_cmplt_epi8(self, a: __m128i, b: __m128i) -> __m128i {
        unsafe { _mm_cmplt_epi8(a, b) }
    }
    #[doc = "See [`arch::_mm_cmplt_epi16`]."]
    #[inline(always)]
    pub fn _mm_cmplt_epi16(self, a: __m128i, b: __m128i) -> __m128i {
        unsafe { _mm_cmplt_epi16(a, b) }
    }
    #[doc = "See [`arch::_mm_cmplt_epi32`]."]
    #[inline(always)]
    pub fn _mm_cmplt_epi32(self, a: __m128i, b: __m128i) -> __m128i {
        unsafe { _mm_cmplt_epi32(a, b) }
    }
    #[doc = "See [`arch::_mm_cvtepi32_pd`]."]
    #[inline(always)]
    pub fn _mm_cvtepi32_pd(self, a: __m128i) -> __m128d {
        unsafe { _mm_cvtepi32_pd(a) }
    }
    #[doc = "See [`arch::_mm_cvtsi32_sd`]."]
    #[inline(always)]
    pub fn _mm_cvtsi32_sd(self, a: __m128d, b: i32) -> __m128d {
        unsafe { _mm_cvtsi32_sd(a, b) }
    }
    #[doc = "See [`arch::_mm_cvtepi32_ps`]."]
    #[inline(always)]
    pub fn _mm_cvtepi32_ps(self, a: __m128i) -> __m128 {
        unsafe { _mm_cvtepi32_ps(a) }
    }
    #[doc = "See [`arch::_mm_cvtps_epi32`]."]
    #[inline(always)]
    pub fn _mm_cvtps_epi32(self, a: __m128) -> __m128i {
        unsafe { _mm_cvtps_epi32(a) }
    }
    #[doc = "See [`arch::_mm_cvtsi32_si128`]."]
    #[inline(always)]
    pub fn _mm_cvtsi32_si128(self, a: i32) -> __m128i {
        unsafe { _mm_cvtsi32_si128(a) }
    }
    #[doc = "See [`arch::_mm_cvtsi128_si32`]."]
    #[inline(always)]
    pub fn _mm_cvtsi128_si32(self, a: __m128i) -> i32 {
        unsafe { _mm_cvtsi128_si32(a) }
    }
    #[doc = "See [`arch::_mm_set_epi64x`]."]
    #[inline(always)]
    pub fn _mm_set_epi64x(self, e1: i64, e0: i64) -> __m128i {
        unsafe { _mm_set_epi64x(e1, e0) }
    }
    #[doc = "See [`arch::_mm_set_epi32`]."]
    #[inline(always)]
    pub fn _mm_set_epi32(self, e3: i32, e2: i32, e1: i32, e0: i32) -> __m128i {
        unsafe { _mm_set_epi32(e3, e2, e1, e0) }
    }
    #[doc = "See [`arch::_mm_set_epi16`]."]
    #[inline(always)]
    pub fn _mm_set_epi16(
        self,
        e7: i16,
        e6: i16,
        e5: i16,
        e4: i16,
        e3: i16,
        e2: i16,
        e1: i16,
        e0: i16,
    ) -> __m128i {
        unsafe { _mm_set_epi16(e7, e6, e5, e4, e3, e2, e1, e0) }
    }
    #[doc = "See [`arch::_mm_set_epi8`]."]
    #[inline(always)]
    pub fn _mm_set_epi8(
        self,
        e15: i8,
        e14: i8,
        e13: i8,
        e12: i8,
        e11: i8,
        e10: i8,
        e9: i8,
        e8: i8,
        e7: i8,
        e6: i8,
        e5: i8,
        e4: i8,
        e3: i8,
        e2: i8,
        e1: i8,
        e0: i8,
    ) -> __m128i {
        unsafe {
            _mm_set_epi8(
                e15, e14, e13, e12, e11, e10, e9, e8, e7, e6, e5, e4, e3, e2, e1, e0,
            )
        }
    }
    #[doc = "See [`arch::_mm_set1_epi64x`]."]
    #[inline(always)]
    pub fn _mm_set1_epi64x(self, a: i64) -> __m128i {
        unsafe { _mm_set1_epi64x(a) }
    }
    #[doc = "See [`arch::_mm_set1_epi32`]."]
    #[inline(always)]
    pub fn _mm_set1_epi32(self, a: i32) -> __m128i {
        unsafe { _mm_set1_epi32(a) }
    }
    #[doc = "See [`arch::_mm_set1_epi16`]."]
    #[inline(always)]
    pub fn _mm_set1_epi16(self, a: i16) -> __m128i {
        unsafe { _mm_set1_epi16(a) }
    }
    #[doc = "See [`arch::_mm_set1_epi8`]."]
    #[inline(always)]
    pub fn _mm_set1_epi8(self, a: i8) -> __m128i {
        unsafe { _mm_set1_epi8(a) }
    }
    #[doc = "See [`arch::_mm_setr_epi32`]."]
    #[inline(always)]
    pub fn _mm_setr_epi32(self, e3: i32, e2: i32, e1: i32, e0: i32) -> __m128i {
        unsafe { _mm_setr_epi32(e3, e2, e1, e0) }
    }
    #[doc = "See [`arch::_mm_setr_epi16`]."]
    #[inline(always)]
    pub fn _mm_setr_epi16(
        self,
        e7: i16,
        e6: i16,
        e5: i16,
        e4: i16,
        e3: i16,
        e2: i16,
        e1: i16,
        e0: i16,
    ) -> __m128i {
        unsafe { _mm_setr_epi16(e7, e6, e5, e4, e3, e2, e1, e0) }
    }
    #[doc = "See [`arch::_mm_setr_epi8`]."]
    #[inline(always)]
    pub fn _mm_setr_epi8(
        self,
        e15: i8,
        e14: i8,
        e13: i8,
        e12: i8,
        e11: i8,
        e10: i8,
        e9: i8,
        e8: i8,
        e7: i8,
        e6: i8,
        e5: i8,
        e4: i8,
        e3: i8,
        e2: i8,
        e1: i8,
        e0: i8,
    ) -> __m128i {
        unsafe {
            _mm_setr_epi8(
                e15, e14, e13, e12, e11, e10, e9, e8, e7, e6, e5, e4, e3, e2, e1, e0,
            )
        }
    }
    #[doc = "See [`arch::_mm_setzero_si128`]."]
    #[inline(always)]
    pub fn _mm_setzero_si128(self) -> __m128i {
        unsafe { _mm_setzero_si128() }
    }
    #[doc = "See [`arch::_mm_loadl_epi64`]."]
    #[inline(always)]
    pub unsafe fn _mm_loadl_epi64(self, mem_addr: *const __m128i) -> __m128i {
        unsafe { _mm_loadl_epi64(mem_addr) }
    }
    #[doc = "See [`arch::_mm_load_si128`]."]
    #[inline(always)]
    pub unsafe fn _mm_load_si128(self, mem_addr: *const __m128i) -> __m128i {
        unsafe { _mm_load_si128(mem_addr) }
    }
    #[doc = "See [`arch::_mm_loadu_si128`]."]
    #[inline(always)]
    pub unsafe fn _mm_loadu_si128(self, mem_addr: *const __m128i) -> __m128i {
        unsafe { _mm_loadu_si128(mem_addr) }
    }
    #[doc = "See [`arch::_mm_maskmoveu_si128`]."]
    #[inline(always)]
    pub unsafe fn _mm_maskmoveu_si128(self, a: __m128i, mask: __m128i, mem_addr: *mut i8) {
        unsafe { _mm_maskmoveu_si128(a, mask, mem_addr) }
    }
    #[doc = "See [`arch::_mm_store_si128`]."]
    #[inline(always)]
    pub unsafe fn _mm_store_si128(self, mem_addr: *mut __m128i, a: __m128i) {
        unsafe { _mm_store_si128(mem_addr, a) }
    }
    #[doc = "See [`arch::_mm_storeu_si128`]."]
    #[inline(always)]
    pub unsafe fn _mm_storeu_si128(self, mem_addr: *mut __m128i, a: __m128i) {
        unsafe { _mm_storeu_si128(mem_addr, a) }
    }
    #[doc = "See [`arch::_mm_storel_epi64`]."]
    #[inline(always)]
    pub unsafe fn _mm_storel_epi64(self, mem_addr: *mut __m128i, a: __m128i) {
        unsafe { _mm_storel_epi64(mem_addr, a) }
    }
    #[doc = "See [`arch::_mm_stream_si128`]."]
    #[inline(always)]
    pub unsafe fn _mm_stream_si128(self, mem_addr: *mut __m128i, a: __m128i) {
        unsafe { _mm_stream_si128(mem_addr, a) }
    }
    #[doc = "See [`arch::_mm_stream_si32`]."]
    #[inline(always)]
    pub unsafe fn _mm_stream_si32(self, mem_addr: *mut i32, a: i32) {
        unsafe { _mm_stream_si32(mem_addr, a) }
    }
    #[doc = "See [`arch::_mm_move_epi64`]."]
    #[inline(always)]
    pub fn _mm_move_epi64(self, a: __m128i) -> __m128i {
        unsafe { _mm_move_epi64(a) }
    }
    #[doc = "See [`arch::_mm_packs_epi16`]."]
    #[inline(always)]
    pub fn _mm_packs_epi16(self, a: __m128i, b: __m128i) -> __m128i {
        unsafe { _mm_packs_epi16(a, b) }
    }
    #[doc = "See [`arch::_mm_packs_epi32`]."]
    #[inline(always)]
    pub fn _mm_packs_epi32(self, a: __m128i, b: __m128i) -> __m128i {
        unsafe { _mm_packs_epi32(a, b) }
    }
    #[doc = "See [`arch::_mm_packus_epi16`]."]
    #[inline(always)]
    pub fn _mm_packus_epi16(self, a: __m128i, b: __m128i) -> __m128i {
        unsafe { _mm_packus_epi16(a, b) }
    }
    #[doc = "See [`arch::_mm_extract_epi16`]."]
    #[inline(always)]
    pub fn _mm_extract_epi16<const IMM8: i32>(self, a: __m128i) -> i32 {
        unsafe { _mm_extract_epi16::<IMM8>(a) }
    }
    #[doc = "See [`arch::_mm_insert_epi16`]."]
    #[inline(always)]
    pub fn _mm_insert_epi16<const IMM8: i32>(self, a: __m128i, i: i32) -> __m128i {
        unsafe { _mm_insert_epi16::<IMM8>(a, i) }
    }
    #[doc = "See [`arch::_mm_movemask_epi8`]."]
    #[inline(always)]
    pub fn _mm_movemask_epi8(self, a: __m128i) -> i32 {
        unsafe { _mm_movemask_epi8(a) }
    }
    #[doc = "See [`arch::_mm_shuffle_epi32`]."]
    #[inline(always)]
    pub fn _mm_shuffle_epi32<const IMM8: i32>(self, a: __m128i) -> __m128i {
        unsafe { _mm_shuffle_epi32::<IMM8>(a) }
    }
    #[doc = "See [`arch::_mm_shufflehi_epi16`]."]
    #[inline(always)]
    pub fn _mm_shufflehi_epi16<const IMM8: i32>(self, a: __m128i) -> __m128i {
        unsafe { _mm_shufflehi_epi16::<IMM8>(a) }
    }
    #[doc = "See [`arch::_mm_shufflelo_epi16`]."]
    #[inline(always)]
    pub fn _mm_shufflelo_epi16<const IMM8: i32>(self, a: __m128i) -> __m128i {
        unsafe { _mm_shufflelo_epi16::<IMM8>(a) }
    }
    #[doc = "See [`arch::_mm_unpackhi_epi8`]."]
    #[inline(always)]
    pub fn _mm_unpackhi_epi8(self, a: __m128i, b: __m128i) -> __m128i {
        unsafe { _mm_unpackhi_epi8(a, b) }
    }
    #[doc = "See [`arch::_mm_unpackhi_epi16`]."]
    #[inline(always)]
    pub fn _mm_unpackhi_epi16(self, a: __m128i, b: __m128i) -> __m128i {
        unsafe { _mm_unpackhi_epi16(a, b) }
    }
    #[doc = "See [`arch::_mm_unpackhi_epi32`]."]
    #[inline(always)]
    pub fn _mm_unpackhi_epi32(self, a: __m128i, b: __m128i) -> __m128i {
        unsafe { _mm_unpackhi_epi32(a, b) }
    }
    #[doc = "See [`arch::_mm_unpackhi_epi64`]."]
    #[inline(always)]
    pub fn _mm_unpackhi_epi64(self, a: __m128i, b: __m128i) -> __m128i {
        unsafe { _mm_unpackhi_epi64(a, b) }
    }
    #[doc = "See [`arch::_mm_unpacklo_epi8`]."]
    #[inline(always)]
    pub fn _mm_unpacklo_epi8(self, a: __m128i, b: __m128i) -> __m128i {
        unsafe { _mm_unpacklo_epi8(a, b) }
    }
    #[doc = "See [`arch::_mm_unpacklo_epi16`]."]
    #[inline(always)]
    pub fn _mm_unpacklo_epi16(self, a: __m128i, b: __m128i) -> __m128i {
        unsafe { _mm_unpacklo_epi16(a, b) }
    }
    #[doc = "See [`arch::_mm_unpacklo_epi32`]."]
    #[inline(always)]
    pub fn _mm_unpacklo_epi32(self, a: __m128i, b: __m128i) -> __m128i {
        unsafe { _mm_unpacklo_epi32(a, b) }
    }
    #[doc = "See [`arch::_mm_unpacklo_epi64`]."]
    #[inline(always)]
    pub fn _mm_unpacklo_epi64(self, a: __m128i, b: __m128i) -> __m128i {
        unsafe { _mm_unpacklo_epi64(a, b) }
    }
    #[doc = "See [`arch::_mm_add_sd`]."]
    #[inline(always)]
    pub fn _mm_add_sd(self, a: __m128d, b: __m128d) -> __m128d {
        unsafe { _mm_add_sd(a, b) }
    }
    #[doc = "See [`arch::_mm_add_pd`]."]
    #[inline(always)]
    pub fn _mm_add_pd(self, a: __m128d, b: __m128d) -> __m128d {
        unsafe { _mm_add_pd(a, b) }
    }
    #[doc = "See [`arch::_mm_div_sd`]."]
    #[inline(always)]
    pub fn _mm_div_sd(self, a: __m128d, b: __m128d) -> __m128d {
        unsafe { _mm_div_sd(a, b) }
    }
    #[doc = "See [`arch::_mm_div_pd`]."]
    #[inline(always)]
    pub fn _mm_div_pd(self, a: __m128d, b: __m128d) -> __m128d {
        unsafe { _mm_div_pd(a, b) }
    }
    #[doc = "See [`arch::_mm_max_sd`]."]
    #[inline(always)]
    pub fn _mm_max_sd(self, a: __m128d, b: __m128d) -> __m128d {
        unsafe { _mm_max_sd(a, b) }
    }
    #[doc = "See [`arch::_mm_max_pd`]."]
    #[inline(always)]
    pub fn _mm_max_pd(self, a: __m128d, b: __m128d) -> __m128d {
        unsafe { _mm_max_pd(a, b) }
    }
    #[doc = "See [`arch::_mm_min_sd`]."]
    #[inline(always)]
    pub fn _mm_min_sd(self, a: __m128d, b: __m128d) -> __m128d {
        unsafe { _mm_min_sd(a, b) }
    }
    #[doc = "See [`arch::_mm_min_pd`]."]
    #[inline(always)]
    pub fn _mm_min_pd(self, a: __m128d, b: __m128d) -> __m128d {
        unsafe { _mm_min_pd(a, b) }
    }
    #[doc = "See [`arch::_mm_mul_sd`]."]
    #[inline(always)]
    pub fn _mm_mul_sd(self, a: __m128d, b: __m128d) -> __m128d {
        unsafe { _mm_mul_sd(a, b) }
    }
    #[doc = "See [`arch::_mm_mul_pd`]."]
    #[inline(always)]
    pub fn _mm_mul_pd(self, a: __m128d, b: __m128d) -> __m128d {
        unsafe { _mm_mul_pd(a, b) }
    }
    #[doc = "See [`arch::_mm_sqrt_sd`]."]
    #[inline(always)]
    pub fn _mm_sqrt_sd(self, a: __m128d, b: __m128d) -> __m128d {
        unsafe { _mm_sqrt_sd(a, b) }
    }
    #[doc = "See [`arch::_mm_sqrt_pd`]."]
    #[inline(always)]
    pub fn _mm_sqrt_pd(self, a: __m128d) -> __m128d {
        unsafe { _mm_sqrt_pd(a) }
    }
    #[doc = "See [`arch::_mm_sub_sd`]."]
    #[inline(always)]
    pub fn _mm_sub_sd(self, a: __m128d, b: __m128d) -> __m128d {
        unsafe { _mm_sub_sd(a, b) }
    }
    #[doc = "See [`arch::_mm_sub_pd`]."]
    #[inline(always)]
    pub fn _mm_sub_pd(self, a: __m128d, b: __m128d) -> __m128d {
        unsafe { _mm_sub_pd(a, b) }
    }
    #[doc = "See [`arch::_mm_and_pd`]."]
    #[inline(always)]
    pub fn _mm_and_pd(self, a: __m128d, b: __m128d) -> __m128d {
        unsafe { _mm_and_pd(a, b) }
    }
    #[doc = "See [`arch::_mm_andnot_pd`]."]
    #[inline(always)]
    pub fn _mm_andnot_pd(self, a: __m128d, b: __m128d) -> __m128d {
        unsafe { _mm_andnot_pd(a, b) }
    }
    #[doc = "See [`arch::_mm_or_pd`]."]
    #[inline(always)]
    pub fn _mm_or_pd(self, a: __m128d, b: __m128d) -> __m128d {
        unsafe { _mm_or_pd(a, b) }
    }
    #[doc = "See [`arch::_mm_xor_pd`]."]
    #[inline(always)]
    pub fn _mm_xor_pd(self, a: __m128d, b: __m128d) -> __m128d {
        unsafe { _mm_xor_pd(a, b) }
    }
    #[doc = "See [`arch::_mm_cmpeq_sd`]."]
    #[inline(always)]
    pub fn _mm_cmpeq_sd(self, a: __m128d, b: __m128d) -> __m128d {
        unsafe { _mm_cmpeq_sd(a, b) }
    }
    #[doc = "See [`arch::_mm_cmplt_sd`]."]
    #[inline(always)]
    pub fn _mm_cmplt_sd(self, a: __m128d, b: __m128d) -> __m128d {
        unsafe { _mm_cmplt_sd(a, b) }
    }
    #[doc = "See [`arch::_mm_cmple_sd`]."]
    #[inline(always)]
    pub fn _mm_cmple_sd(self, a: __m128d, b: __m128d) -> __m128d {
        unsafe { _mm_cmple_sd(a, b) }
    }
    #[doc = "See [`arch::_mm_cmpgt_sd`]."]
    #[inline(always)]
    pub fn _mm_cmpgt_sd(self, a: __m128d, b: __m128d) -> __m128d {
        unsafe { _mm_cmpgt_sd(a, b) }
    }
    #[doc = "See [`arch::_mm_cmpge_sd`]."]
    #[inline(always)]
    pub fn _mm_cmpge_sd(self, a: __m128d, b: __m128d) -> __m128d {
        unsafe { _mm_cmpge_sd(a, b) }
    }
    #[doc = "See [`arch::_mm_cmpord_sd`]."]
    #[inline(always)]
    pub fn _mm_cmpord_sd(self, a: __m128d, b: __m128d) -> __m128d {
        unsafe { _mm_cmpord_sd(a, b) }
    }
    #[doc = "See [`arch::_mm_cmpunord_sd`]."]
    #[inline(always)]
    pub fn _mm_cmpunord_sd(self, a: __m128d, b: __m128d) -> __m128d {
        unsafe { _mm_cmpunord_sd(a, b) }
    }
    #[doc = "See [`arch::_mm_cmpneq_sd`]."]
    #[inline(always)]
    pub fn _mm_cmpneq_sd(self, a: __m128d, b: __m128d) -> __m128d {
        unsafe { _mm_cmpneq_sd(a, b) }
    }
    #[doc = "See [`arch::_mm_cmpnlt_sd`]."]
    #[inline(always)]
    pub fn _mm_cmpnlt_sd(self, a: __m128d, b: __m128d) -> __m128d {
        unsafe { _mm_cmpnlt_sd(a, b) }
    }
    #[doc = "See [`arch::_mm_cmpnle_sd`]."]
    #[inline(always)]
    pub fn _mm_cmpnle_sd(self, a: __m128d, b: __m128d) -> __m128d {
        unsafe { _mm_cmpnle_sd(a, b) }
    }
    #[doc = "See [`arch::_mm_cmpngt_sd`]."]
    #[inline(always)]
    pub fn _mm_cmpngt_sd(self, a: __m128d, b: __m128d) -> __m128d {
        unsafe { _mm_cmpngt_sd(a, b) }
    }
    #[doc = "See [`arch::_mm_cmpnge_sd`]."]
    #[inline(always)]
    pub fn _mm_cmpnge_sd(self, a: __m128d, b: __m128d) -> __m128d {
        unsafe { _mm_cmpnge_sd(a, b) }
    }
    #[doc = "See [`arch::_mm_cmpeq_pd`]."]
    #[inline(always)]
    pub fn _mm_cmpeq_pd(self, a: __m128d, b: __m128d) -> __m128d {
        unsafe { _mm_cmpeq_pd(a, b) }
    }
    #[doc = "See [`arch::_mm_cmplt_pd`]."]
    #[inline(always)]
    pub fn _mm_cmplt_pd(self, a: __m128d, b: __m128d) -> __m128d {
        unsafe { _mm_cmplt_pd(a, b) }
    }
    #[doc = "See [`arch::_mm_cmple_pd`]."]
    #[inline(always)]
    pub fn _mm_cmple_pd(self, a: __m128d, b: __m128d) -> __m128d {
        unsafe { _mm_cmple_pd(a, b) }
    }
    #[doc = "See [`arch::_mm_cmpgt_pd`]."]
    #[inline(always)]
    pub fn _mm_cmpgt_pd(self, a: __m128d, b: __m128d) -> __m128d {
        unsafe { _mm_cmpgt_pd(a, b) }
    }
    #[doc = "See [`arch::_mm_cmpge_pd`]."]
    #[inline(always)]
    pub fn _mm_cmpge_pd(self, a: __m128d, b: __m128d) -> __m128d {
        unsafe { _mm_cmpge_pd(a, b) }
    }
    #[doc = "See [`arch::_mm_cmpord_pd`]."]
    #[inline(always)]
    pub fn _mm_cmpord_pd(self, a: __m128d, b: __m128d) -> __m128d {
        unsafe { _mm_cmpord_pd(a, b) }
    }
    #[doc = "See [`arch::_mm_cmpunord_pd`]."]
    #[inline(always)]
    pub fn _mm_cmpunord_pd(self, a: __m128d, b: __m128d) -> __m128d {
        unsafe { _mm_cmpunord_pd(a, b) }
    }
    #[doc = "See [`arch::_mm_cmpneq_pd`]."]
    #[inline(always)]
    pub fn _mm_cmpneq_pd(self, a: __m128d, b: __m128d) -> __m128d {
        unsafe { _mm_cmpneq_pd(a, b) }
    }
    #[doc = "See [`arch::_mm_cmpnlt_pd`]."]
    #[inline(always)]
    pub fn _mm_cmpnlt_pd(self, a: __m128d, b: __m128d) -> __m128d {
        unsafe { _mm_cmpnlt_pd(a, b) }
    }
    #[doc = "See [`arch::_mm_cmpnle_pd`]."]
    #[inline(always)]
    pub fn _mm_cmpnle_pd(self, a: __m128d, b: __m128d) -> __m128d {
        unsafe { _mm_cmpnle_pd(a, b) }
    }
    #[doc = "See [`arch::_mm_cmpngt_pd`]."]
    #[inline(always)]
    pub fn _mm_cmpngt_pd(self, a: __m128d, b: __m128d) -> __m128d {
        unsafe { _mm_cmpngt_pd(a, b) }
    }
    #[doc = "See [`arch::_mm_cmpnge_pd`]."]
    #[inline(always)]
    pub fn _mm_cmpnge_pd(self, a: __m128d, b: __m128d) -> __m128d {
        unsafe { _mm_cmpnge_pd(a, b) }
    }
    #[doc = "See [`arch::_mm_comieq_sd`]."]
    #[inline(always)]
    pub fn _mm_comieq_sd(self, a: __m128d, b: __m128d) -> i32 {
        unsafe { _mm_comieq_sd(a, b) }
    }
    #[doc = "See [`arch::_mm_comilt_sd`]."]
    #[inline(always)]
    pub fn _mm_comilt_sd(self, a: __m128d, b: __m128d) -> i32 {
        unsafe { _mm_comilt_sd(a, b) }
    }
    #[doc = "See [`arch::_mm_comile_sd`]."]
    #[inline(always)]
    pub fn _mm_comile_sd(self, a: __m128d, b: __m128d) -> i32 {
        unsafe { _mm_comile_sd(a, b) }
    }
    #[doc = "See [`arch::_mm_comigt_sd`]."]
    #[inline(always)]
    pub fn _mm_comigt_sd(self, a: __m128d, b: __m128d) -> i32 {
        unsafe { _mm_comigt_sd(a, b) }
    }
    #[doc = "See [`arch::_mm_comige_sd`]."]
    #[inline(always)]
    pub fn _mm_comige_sd(self, a: __m128d, b: __m128d) -> i32 {
        unsafe { _mm_comige_sd(a, b) }
    }
    #[doc = "See [`arch::_mm_comineq_sd`]."]
    #[inline(always)]
    pub fn _mm_comineq_sd(self, a: __m128d, b: __m128d) -> i32 {
        unsafe { _mm_comineq_sd(a, b) }
    }
    #[doc = "See [`arch::_mm_ucomieq_sd`]."]
    #[inline(always)]
    pub fn _mm_ucomieq_sd(self, a: __m128d, b: __m128d) -> i32 {
        unsafe { _mm_ucomieq_sd(a, b) }
    }
    #[doc = "See [`arch::_mm_ucomilt_sd`]."]
    #[inline(always)]
    pub fn _mm_ucomilt_sd(self, a: __m128d, b: __m128d) -> i32 {
        unsafe { _mm_ucomilt_sd(a, b) }
    }
    #[doc = "See [`arch::_mm_ucomile_sd`]."]
    #[inline(always)]
    pub fn _mm_ucomile_sd(self, a: __m128d, b: __m128d) -> i32 {
        unsafe { _mm_ucomile_sd(a, b) }
    }
    #[doc = "See [`arch::_mm_ucomigt_sd`]."]
    #[inline(always)]
    pub fn _mm_ucomigt_sd(self, a: __m128d, b: __m128d) -> i32 {
        unsafe { _mm_ucomigt_sd(a, b) }
    }
    #[doc = "See [`arch::_mm_ucomige_sd`]."]
    #[inline(always)]
    pub fn _mm_ucomige_sd(self, a: __m128d, b: __m128d) -> i32 {
        unsafe { _mm_ucomige_sd(a, b) }
    }
    #[doc = "See [`arch::_mm_ucomineq_sd`]."]
    #[inline(always)]
    pub fn _mm_ucomineq_sd(self, a: __m128d, b: __m128d) -> i32 {
        unsafe { _mm_ucomineq_sd(a, b) }
    }
    #[doc = "See [`arch::_mm_cvtpd_ps`]."]
    #[inline(always)]
    pub fn _mm_cvtpd_ps(self, a: __m128d) -> __m128 {
        unsafe { _mm_cvtpd_ps(a) }
    }
    #[doc = "See [`arch::_mm_cvtps_pd`]."]
    #[inline(always)]
    pub fn _mm_cvtps_pd(self, a: __m128) -> __m128d {
        unsafe { _mm_cvtps_pd(a) }
    }
    #[doc = "See [`arch::_mm_cvtpd_epi32`]."]
    #[inline(always)]
    pub fn _mm_cvtpd_epi32(self, a: __m128d) -> __m128i {
        unsafe { _mm_cvtpd_epi32(a) }
    }
    #[doc = "See [`arch::_mm_cvtsd_si32`]."]
    #[inline(always)]
    pub fn _mm_cvtsd_si32(self, a: __m128d) -> i32 {
        unsafe { _mm_cvtsd_si32(a) }
    }
    #[doc = "See [`arch::_mm_cvtsd_ss`]."]
    #[inline(always)]
    pub fn _mm_cvtsd_ss(self, a: __m128, b: __m128d) -> __m128 {
        unsafe { _mm_cvtsd_ss(a, b) }
    }
    #[doc = "See [`arch::_mm_cvtsd_f64`]."]
    #[inline(always)]
    pub fn _mm_cvtsd_f64(self, a: __m128d) -> f64 {
        unsafe { _mm_cvtsd_f64(a) }
    }
    #[doc = "See [`arch::_mm_cvtss_sd`]."]
    #[inline(always)]
    pub fn _mm_cvtss_sd(self, a: __m128d, b: __m128) -> __m128d {
        unsafe { _mm_cvtss_sd(a, b) }
    }
    #[doc = "See [`arch::_mm_cvttpd_epi32`]."]
    #[inline(always)]
    pub fn _mm_cvttpd_epi32(self, a: __m128d) -> __m128i {
        unsafe { _mm_cvttpd_epi32(a) }
    }
    #[doc = "See [`arch::_mm_cvttsd_si32`]."]
    #[inline(always)]
    pub fn _mm_cvttsd_si32(self, a: __m128d) -> i32 {
        unsafe { _mm_cvttsd_si32(a) }
    }
    #[doc = "See [`arch::_mm_cvttps_epi32`]."]
    #[inline(always)]
    pub fn _mm_cvttps_epi32(self, a: __m128) -> __m128i {
        unsafe { _mm_cvttps_epi32(a) }
    }
    #[doc = "See [`arch::_mm_set_sd`]."]
    #[inline(always)]
    pub fn _mm_set_sd(self, a: f64) -> __m128d {
        unsafe { _mm_set_sd(a) }
    }
    #[doc = "See [`arch::_mm_set1_pd`]."]
    #[inline(always)]
    pub fn _mm_set1_pd(self, a: f64) -> __m128d {
        unsafe { _mm_set1_pd(a) }
    }
    #[doc = "See [`arch::_mm_set_pd1`]."]
    #[inline(always)]
    pub fn _mm_set_pd1(self, a: f64) -> __m128d {
        unsafe { _mm_set_pd1(a) }
    }
    #[doc = "See [`arch::_mm_set_pd`]."]
    #[inline(always)]
    pub fn _mm_set_pd(self, a: f64, b: f64) -> __m128d {
        unsafe { _mm_set_pd(a, b) }
    }
    #[doc = "See [`arch::_mm_setr_pd`]."]
    #[inline(always)]
    pub fn _mm_setr_pd(self, a: f64, b: f64) -> __m128d {
        unsafe { _mm_setr_pd(a, b) }
    }
    #[doc = "See [`arch::_mm_setzero_pd`]."]
    #[inline(always)]
    pub fn _mm_setzero_pd(self) -> __m128d {
        unsafe { _mm_setzero_pd() }
    }
    #[doc = "See [`arch::_mm_movemask_pd`]."]
    #[inline(always)]
    pub fn _mm_movemask_pd(self, a: __m128d) -> i32 {
        unsafe { _mm_movemask_pd(a) }
    }
    #[doc = "See [`arch::_mm_load_pd`]."]
    #[allow(clippy::cast_ptr_alignment)]
    #[inline(always)]
    pub unsafe fn _mm_load_pd(self, mem_addr: *const f64) -> __m128d {
        unsafe { _mm_load_pd(mem_addr) }
    }
    #[doc = "See [`arch::_mm_load_sd`]."]
    #[inline(always)]
    pub unsafe fn _mm_load_sd(self, mem_addr: *const f64) -> __m128d {
        unsafe { _mm_load_sd(mem_addr) }
    }
    #[doc = "See [`arch::_mm_loadh_pd`]."]
    #[inline(always)]
    pub unsafe fn _mm_loadh_pd(self, a: __m128d, mem_addr: *const f64) -> __m128d {
        unsafe { _mm_loadh_pd(a, mem_addr) }
    }
    #[doc = "See [`arch::_mm_loadl_pd`]."]
    #[inline(always)]
    pub unsafe fn _mm_loadl_pd(self, a: __m128d, mem_addr: *const f64) -> __m128d {
        unsafe { _mm_loadl_pd(a, mem_addr) }
    }
    #[doc = "See [`arch::_mm_stream_pd`]."]
    #[allow(clippy::cast_ptr_alignment)]
    #[inline(always)]
    pub unsafe fn _mm_stream_pd(self, mem_addr: *mut f64, a: __m128d) {
        unsafe { _mm_stream_pd(mem_addr, a) }
    }
    #[doc = "See [`arch::_mm_store_sd`]."]
    #[inline(always)]
    pub unsafe fn _mm_store_sd(self, mem_addr: *mut f64, a: __m128d) {
        unsafe { _mm_store_sd(mem_addr, a) }
    }
    #[doc = "See [`arch::_mm_store_pd`]."]
    #[allow(clippy::cast_ptr_alignment)]
    #[inline(always)]
    pub unsafe fn _mm_store_pd(self, mem_addr: *mut f64, a: __m128d) {
        unsafe { _mm_store_pd(mem_addr, a) }
    }
    #[doc = "See [`arch::_mm_storeu_pd`]."]
    #[inline(always)]
    pub unsafe fn _mm_storeu_pd(self, mem_addr: *mut f64, a: __m128d) {
        unsafe { _mm_storeu_pd(mem_addr, a) }
    }
    #[doc = "See [`arch::_mm_storeu_si16`]."]
    #[inline(always)]
    pub unsafe fn _mm_storeu_si16(self, mem_addr: *mut u8, a: __m128i) {
        unsafe { _mm_storeu_si16(mem_addr, a) }
    }
    #[doc = "See [`arch::_mm_storeu_si32`]."]
    #[inline(always)]
    pub unsafe fn _mm_storeu_si32(self, mem_addr: *mut u8, a: __m128i) {
        unsafe { _mm_storeu_si32(mem_addr, a) }
    }
    #[doc = "See [`arch::_mm_storeu_si64`]."]
    #[inline(always)]
    pub unsafe fn _mm_storeu_si64(self, mem_addr: *mut u8, a: __m128i) {
        unsafe { _mm_storeu_si64(mem_addr, a) }
    }
    #[doc = "See [`arch::_mm_store1_pd`]."]
    #[allow(clippy::cast_ptr_alignment)]
    #[inline(always)]
    pub unsafe fn _mm_store1_pd(self, mem_addr: *mut f64, a: __m128d) {
        unsafe { _mm_store1_pd(mem_addr, a) }
    }
    #[doc = "See [`arch::_mm_store_pd1`]."]
    #[allow(clippy::cast_ptr_alignment)]
    #[inline(always)]
    pub unsafe fn _mm_store_pd1(self, mem_addr: *mut f64, a: __m128d) {
        unsafe { _mm_store_pd1(mem_addr, a) }
    }
    #[doc = "See [`arch::_mm_storer_pd`]."]
    #[allow(clippy::cast_ptr_alignment)]
    #[inline(always)]
    pub unsafe fn _mm_storer_pd(self, mem_addr: *mut f64, a: __m128d) {
        unsafe { _mm_storer_pd(mem_addr, a) }
    }
    #[doc = "See [`arch::_mm_storeh_pd`]."]
    #[inline(always)]
    pub unsafe fn _mm_storeh_pd(self, mem_addr: *mut f64, a: __m128d) {
        unsafe { _mm_storeh_pd(mem_addr, a) }
    }
    #[doc = "See [`arch::_mm_storel_pd`]."]
    #[inline(always)]
    pub unsafe fn _mm_storel_pd(self, mem_addr: *mut f64, a: __m128d) {
        unsafe { _mm_storel_pd(mem_addr, a) }
    }
    #[doc = "See [`arch::_mm_load1_pd`]."]
    #[inline(always)]
    pub unsafe fn _mm_load1_pd(self, mem_addr: *const f64) -> __m128d {
        unsafe { _mm_load1_pd(mem_addr) }
    }
    #[doc = "See [`arch::_mm_load_pd1`]."]
    #[inline(always)]
    pub unsafe fn _mm_load_pd1(self, mem_addr: *const f64) -> __m128d {
        unsafe { _mm_load_pd1(mem_addr) }
    }
    #[doc = "See [`arch::_mm_loadr_pd`]."]
    #[inline(always)]
    pub unsafe fn _mm_loadr_pd(self, mem_addr: *const f64) -> __m128d {
        unsafe { _mm_loadr_pd(mem_addr) }
    }
    #[doc = "See [`arch::_mm_loadu_pd`]."]
    #[inline(always)]
    pub unsafe fn _mm_loadu_pd(self, mem_addr: *const f64) -> __m128d {
        unsafe { _mm_loadu_pd(mem_addr) }
    }
    #[doc = "See [`arch::_mm_loadu_si16`]."]
    #[inline(always)]
    pub unsafe fn _mm_loadu_si16(self, mem_addr: *const u8) -> __m128i {
        unsafe { _mm_loadu_si16(mem_addr) }
    }
    #[doc = "See [`arch::_mm_loadu_si32`]."]
    #[inline(always)]
    pub unsafe fn _mm_loadu_si32(self, mem_addr: *const u8) -> __m128i {
        unsafe { _mm_loadu_si32(mem_addr) }
    }
    #[doc = "See [`arch::_mm_loadu_si64`]."]
    #[inline(always)]
    pub unsafe fn _mm_loadu_si64(self, mem_addr: *const u8) -> __m128i {
        unsafe { _mm_loadu_si64(mem_addr) }
    }
    #[doc = "See [`arch::_mm_shuffle_pd`]."]
    #[inline(always)]
    pub fn _mm_shuffle_pd<const MASK: i32>(self, a: __m128d, b: __m128d) -> __m128d {
        unsafe { _mm_shuffle_pd::<MASK>(a, b) }
    }
    #[doc = "See [`arch::_mm_move_sd`]."]
    #[inline(always)]
    pub fn _mm_move_sd(self, a: __m128d, b: __m128d) -> __m128d {
        unsafe { _mm_move_sd(a, b) }
    }
    #[doc = "See [`arch::_mm_castpd_ps`]."]
    #[inline(always)]
    pub fn _mm_castpd_ps(self, a: __m128d) -> __m128 {
        unsafe { _mm_castpd_ps(a) }
    }
    #[doc = "See [`arch::_mm_castpd_si128`]."]
    #[inline(always)]
    pub fn _mm_castpd_si128(self, a: __m128d) -> __m128i {
        unsafe { _mm_castpd_si128(a) }
    }
    #[doc = "See [`arch::_mm_castps_pd`]."]
    #[inline(always)]
    pub fn _mm_castps_pd(self, a: __m128) -> __m128d {
        unsafe { _mm_castps_pd(a) }
    }
    #[doc = "See [`arch::_mm_castps_si128`]."]
    #[inline(always)]
    pub fn _mm_castps_si128(self, a: __m128) -> __m128i {
        unsafe { _mm_castps_si128(a) }
    }
    #[doc = "See [`arch::_mm_castsi128_pd`]."]
    #[inline(always)]
    pub fn _mm_castsi128_pd(self, a: __m128i) -> __m128d {
        unsafe { _mm_castsi128_pd(a) }
    }
    #[doc = "See [`arch::_mm_castsi128_ps`]."]
    #[inline(always)]
    pub fn _mm_castsi128_ps(self, a: __m128i) -> __m128 {
        unsafe { _mm_castsi128_ps(a) }
    }
    #[doc = "See [`arch::_mm_undefined_pd`]."]
    #[inline(always)]
    pub fn _mm_undefined_pd(self) -> __m128d {
        unsafe { _mm_undefined_pd() }
    }
    #[doc = "See [`arch::_mm_undefined_si128`]."]
    #[inline(always)]
    pub fn _mm_undefined_si128(self) -> __m128i {
        unsafe { _mm_undefined_si128() }
    }
    #[doc = "See [`arch::_mm_unpackhi_pd`]."]
    #[inline(always)]
    pub fn _mm_unpackhi_pd(self, a: __m128d, b: __m128d) -> __m128d {
        unsafe { _mm_unpackhi_pd(a, b) }
    }
    #[doc = "See [`arch::_mm_unpacklo_pd`]."]
    #[inline(always)]
    pub fn _mm_unpacklo_pd(self, a: __m128d, b: __m128d) -> __m128d {
        unsafe { _mm_unpacklo_pd(a, b) }
    }
}
