// Copyright 2026 the Fearless_SIMD Authors
// SPDX-License-Identifier: Apache-2.0 OR MIT

// This file is autogenerated by fearless_simd_gen

use arch::*;
#[cfg(target_arch = "x86")]
use core::arch::x86 as arch;
#[cfg(target_arch = "x86_64")]
use core::arch::x86_64 as arch;
#[doc = "A token for `Sse3` intrinsics on `x86` and `x86_64`."]
#[derive(Clone, Copy, Debug)]
pub struct Sse3 {
    _private: (),
}
#[allow(
    clippy::missing_safety_doc,
    reason = "The underlying functions have their own safety docs"
)]
impl Sse3 {
    #[doc = r" Create a SIMD token."]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" The required CPU features must be available."]
    #[inline]
    pub const unsafe fn new_unchecked() -> Self {
        Self { _private: () }
    }
    #[doc = "See [`arch::_mm_addsub_ps`]."]
    #[inline(always)]
    pub fn _mm_addsub_ps(self, a: __m128, b: __m128) -> __m128 {
        unsafe { _mm_addsub_ps(a, b) }
    }
    #[doc = "See [`arch::_mm_addsub_pd`]."]
    #[inline(always)]
    pub fn _mm_addsub_pd(self, a: __m128d, b: __m128d) -> __m128d {
        unsafe { _mm_addsub_pd(a, b) }
    }
    #[doc = "See [`arch::_mm_hadd_pd`]."]
    #[inline(always)]
    pub fn _mm_hadd_pd(self, a: __m128d, b: __m128d) -> __m128d {
        unsafe { _mm_hadd_pd(a, b) }
    }
    #[doc = "See [`arch::_mm_hadd_ps`]."]
    #[inline(always)]
    pub fn _mm_hadd_ps(self, a: __m128, b: __m128) -> __m128 {
        unsafe { _mm_hadd_ps(a, b) }
    }
    #[doc = "See [`arch::_mm_hsub_pd`]."]
    #[inline(always)]
    pub fn _mm_hsub_pd(self, a: __m128d, b: __m128d) -> __m128d {
        unsafe { _mm_hsub_pd(a, b) }
    }
    #[doc = "See [`arch::_mm_hsub_ps`]."]
    #[inline(always)]
    pub fn _mm_hsub_ps(self, a: __m128, b: __m128) -> __m128 {
        unsafe { _mm_hsub_ps(a, b) }
    }
    #[doc = "See [`arch::_mm_lddqu_si128`]."]
    #[inline(always)]
    pub unsafe fn _mm_lddqu_si128(self, mem_addr: *const __m128i) -> __m128i {
        unsafe { _mm_lddqu_si128(mem_addr) }
    }
    #[doc = "See [`arch::_mm_movedup_pd`]."]
    #[inline(always)]
    pub fn _mm_movedup_pd(self, a: __m128d) -> __m128d {
        unsafe { _mm_movedup_pd(a) }
    }
    #[doc = "See [`arch::_mm_loaddup_pd`]."]
    #[inline(always)]
    pub unsafe fn _mm_loaddup_pd(self, mem_addr: *const f64) -> __m128d {
        unsafe { _mm_loaddup_pd(mem_addr) }
    }
    #[doc = "See [`arch::_mm_movehdup_ps`]."]
    #[inline(always)]
    pub fn _mm_movehdup_ps(self, a: __m128) -> __m128 {
        unsafe { _mm_movehdup_ps(a) }
    }
    #[doc = "See [`arch::_mm_moveldup_ps`]."]
    #[inline(always)]
    pub fn _mm_moveldup_ps(self, a: __m128) -> __m128 {
        unsafe { _mm_moveldup_ps(a) }
    }
}
