// Copyright 2026 the Fearless_SIMD Authors
// SPDX-License-Identifier: Apache-2.0 OR MIT

// This file is autogenerated by fearless_simd_gen

use arch::*;
#[cfg(target_arch = "x86")]
use core::arch::x86 as arch;
#[cfg(target_arch = "x86_64")]
use core::arch::x86_64 as arch;
#[doc = "A token for `Sse4_2` intrinsics on `x86` and `x86_64`."]
#[derive(Clone, Copy, Debug)]
pub struct Sse4_2 {
    _private: (),
}
#[allow(
    clippy::missing_safety_doc,
    reason = "The underlying functions have their own safety docs"
)]
impl Sse4_2 {
    #[doc = r" Create a SIMD token."]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" The required CPU features must be available."]
    #[inline]
    pub const unsafe fn new_unchecked() -> Self {
        Self { _private: () }
    }
    #[doc = "See [`arch::_mm_cmpistrm`]."]
    #[inline(always)]
    pub fn _mm_cmpistrm<const IMM8: i32>(self, a: __m128i, b: __m128i) -> __m128i {
        unsafe { _mm_cmpistrm::<IMM8>(a, b) }
    }
    #[doc = "See [`arch::_mm_cmpistri`]."]
    #[inline(always)]
    pub fn _mm_cmpistri<const IMM8: i32>(self, a: __m128i, b: __m128i) -> i32 {
        unsafe { _mm_cmpistri::<IMM8>(a, b) }
    }
    #[doc = "See [`arch::_mm_cmpistrz`]."]
    #[inline(always)]
    pub fn _mm_cmpistrz<const IMM8: i32>(self, a: __m128i, b: __m128i) -> i32 {
        unsafe { _mm_cmpistrz::<IMM8>(a, b) }
    }
    #[doc = "See [`arch::_mm_cmpistrc`]."]
    #[inline(always)]
    pub fn _mm_cmpistrc<const IMM8: i32>(self, a: __m128i, b: __m128i) -> i32 {
        unsafe { _mm_cmpistrc::<IMM8>(a, b) }
    }
    #[doc = "See [`arch::_mm_cmpistrs`]."]
    #[inline(always)]
    pub fn _mm_cmpistrs<const IMM8: i32>(self, a: __m128i, b: __m128i) -> i32 {
        unsafe { _mm_cmpistrs::<IMM8>(a, b) }
    }
    #[doc = "See [`arch::_mm_cmpistro`]."]
    #[inline(always)]
    pub fn _mm_cmpistro<const IMM8: i32>(self, a: __m128i, b: __m128i) -> i32 {
        unsafe { _mm_cmpistro::<IMM8>(a, b) }
    }
    #[doc = "See [`arch::_mm_cmpistra`]."]
    #[inline(always)]
    pub fn _mm_cmpistra<const IMM8: i32>(self, a: __m128i, b: __m128i) -> i32 {
        unsafe { _mm_cmpistra::<IMM8>(a, b) }
    }
    #[doc = "See [`arch::_mm_cmpestrm`]."]
    #[inline(always)]
    pub fn _mm_cmpestrm<const IMM8: i32>(
        self,
        a: __m128i,
        la: i32,
        b: __m128i,
        lb: i32,
    ) -> __m128i {
        unsafe { _mm_cmpestrm::<IMM8>(a, la, b, lb) }
    }
    #[doc = "See [`arch::_mm_cmpestri`]."]
    #[inline(always)]
    pub fn _mm_cmpestri<const IMM8: i32>(self, a: __m128i, la: i32, b: __m128i, lb: i32) -> i32 {
        unsafe { _mm_cmpestri::<IMM8>(a, la, b, lb) }
    }
    #[doc = "See [`arch::_mm_cmpestrz`]."]
    #[inline(always)]
    pub fn _mm_cmpestrz<const IMM8: i32>(self, a: __m128i, la: i32, b: __m128i, lb: i32) -> i32 {
        unsafe { _mm_cmpestrz::<IMM8>(a, la, b, lb) }
    }
    #[doc = "See [`arch::_mm_cmpestrc`]."]
    #[inline(always)]
    pub fn _mm_cmpestrc<const IMM8: i32>(self, a: __m128i, la: i32, b: __m128i, lb: i32) -> i32 {
        unsafe { _mm_cmpestrc::<IMM8>(a, la, b, lb) }
    }
    #[doc = "See [`arch::_mm_cmpestrs`]."]
    #[inline(always)]
    pub fn _mm_cmpestrs<const IMM8: i32>(self, a: __m128i, la: i32, b: __m128i, lb: i32) -> i32 {
        unsafe { _mm_cmpestrs::<IMM8>(a, la, b, lb) }
    }
    #[doc = "See [`arch::_mm_cmpestro`]."]
    #[inline(always)]
    pub fn _mm_cmpestro<const IMM8: i32>(self, a: __m128i, la: i32, b: __m128i, lb: i32) -> i32 {
        unsafe { _mm_cmpestro::<IMM8>(a, la, b, lb) }
    }
    #[doc = "See [`arch::_mm_cmpestra`]."]
    #[inline(always)]
    pub fn _mm_cmpestra<const IMM8: i32>(self, a: __m128i, la: i32, b: __m128i, lb: i32) -> i32 {
        unsafe { _mm_cmpestra::<IMM8>(a, la, b, lb) }
    }
    #[doc = "See [`arch::_mm_crc32_u8`]."]
    #[inline(always)]
    pub fn _mm_crc32_u8(self, crc: u32, v: u8) -> u32 {
        unsafe { _mm_crc32_u8(crc, v) }
    }
    #[doc = "See [`arch::_mm_crc32_u16`]."]
    #[inline(always)]
    pub fn _mm_crc32_u16(self, crc: u32, v: u16) -> u32 {
        unsafe { _mm_crc32_u16(crc, v) }
    }
    #[doc = "See [`arch::_mm_crc32_u32`]."]
    #[inline(always)]
    pub fn _mm_crc32_u32(self, crc: u32, v: u32) -> u32 {
        unsafe { _mm_crc32_u32(crc, v) }
    }
    #[doc = "See [`arch::_mm_cmpgt_epi64`]."]
    #[inline(always)]
    pub fn _mm_cmpgt_epi64(self, a: __m128i, b: __m128i) -> __m128i {
        unsafe { _mm_cmpgt_epi64(a, b) }
    }
}
