// Copyright 2026 the Fearless_SIMD Authors
// SPDX-License-Identifier: Apache-2.0 OR MIT

// This file is autogenerated by fearless_simd_gen

use arch::*;
#[cfg(target_arch = "x86")]
use core::arch::x86 as arch;
#[cfg(target_arch = "x86_64")]
use core::arch::x86_64 as arch;
#[doc = "A token for `Sse4_1` intrinsics on `x86` and `x86_64`."]
#[derive(Clone, Copy, Debug)]
pub struct Sse4_1 {
    _private: (),
}
#[allow(
    clippy::missing_safety_doc,
    reason = "The underlying functions have their own safety docs"
)]
impl Sse4_1 {
    #[doc = r" Create a SIMD token."]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" The required CPU features must be available."]
    #[inline]
    pub const unsafe fn new_unchecked() -> Self {
        Self { _private: () }
    }
    #[doc = "See [`arch::_mm_blendv_epi8`]."]
    #[inline(always)]
    pub fn _mm_blendv_epi8(self, a: __m128i, b: __m128i, mask: __m128i) -> __m128i {
        unsafe { _mm_blendv_epi8(a, b, mask) }
    }
    #[doc = "See [`arch::_mm_blend_epi16`]."]
    #[inline(always)]
    pub fn _mm_blend_epi16<const IMM8: i32>(self, a: __m128i, b: __m128i) -> __m128i {
        unsafe { _mm_blend_epi16::<IMM8>(a, b) }
    }
    #[doc = "See [`arch::_mm_blendv_pd`]."]
    #[inline(always)]
    pub fn _mm_blendv_pd(self, a: __m128d, b: __m128d, mask: __m128d) -> __m128d {
        unsafe { _mm_blendv_pd(a, b, mask) }
    }
    #[doc = "See [`arch::_mm_blendv_ps`]."]
    #[inline(always)]
    pub fn _mm_blendv_ps(self, a: __m128, b: __m128, mask: __m128) -> __m128 {
        unsafe { _mm_blendv_ps(a, b, mask) }
    }
    #[doc = "See [`arch::_mm_blend_pd`]."]
    #[inline(always)]
    pub fn _mm_blend_pd<const IMM2: i32>(self, a: __m128d, b: __m128d) -> __m128d {
        unsafe { _mm_blend_pd::<IMM2>(a, b) }
    }
    #[doc = "See [`arch::_mm_blend_ps`]."]
    #[inline(always)]
    pub fn _mm_blend_ps<const IMM4: i32>(self, a: __m128, b: __m128) -> __m128 {
        unsafe { _mm_blend_ps::<IMM4>(a, b) }
    }
    #[doc = "See [`arch::_mm_extract_ps`]."]
    #[inline(always)]
    pub fn _mm_extract_ps<const IMM8: i32>(self, a: __m128) -> i32 {
        unsafe { _mm_extract_ps::<IMM8>(a) }
    }
    #[doc = "See [`arch::_mm_extract_epi8`]."]
    #[inline(always)]
    pub fn _mm_extract_epi8<const IMM8: i32>(self, a: __m128i) -> i32 {
        unsafe { _mm_extract_epi8::<IMM8>(a) }
    }
    #[doc = "See [`arch::_mm_extract_epi32`]."]
    #[inline(always)]
    pub fn _mm_extract_epi32<const IMM8: i32>(self, a: __m128i) -> i32 {
        unsafe { _mm_extract_epi32::<IMM8>(a) }
    }
    #[doc = "See [`arch::_mm_insert_ps`]."]
    #[inline(always)]
    pub fn _mm_insert_ps<const IMM8: i32>(self, a: __m128, b: __m128) -> __m128 {
        unsafe { _mm_insert_ps::<IMM8>(a, b) }
    }
    #[doc = "See [`arch::_mm_insert_epi8`]."]
    #[inline(always)]
    pub fn _mm_insert_epi8<const IMM8: i32>(self, a: __m128i, i: i32) -> __m128i {
        unsafe { _mm_insert_epi8::<IMM8>(a, i) }
    }
    #[doc = "See [`arch::_mm_insert_epi32`]."]
    #[inline(always)]
    pub fn _mm_insert_epi32<const IMM8: i32>(self, a: __m128i, i: i32) -> __m128i {
        unsafe { _mm_insert_epi32::<IMM8>(a, i) }
    }
    #[doc = "See [`arch::_mm_max_epi8`]."]
    #[inline(always)]
    pub fn _mm_max_epi8(self, a: __m128i, b: __m128i) -> __m128i {
        unsafe { _mm_max_epi8(a, b) }
    }
    #[doc = "See [`arch::_mm_max_epu16`]."]
    #[inline(always)]
    pub fn _mm_max_epu16(self, a: __m128i, b: __m128i) -> __m128i {
        unsafe { _mm_max_epu16(a, b) }
    }
    #[doc = "See [`arch::_mm_max_epi32`]."]
    #[inline(always)]
    pub fn _mm_max_epi32(self, a: __m128i, b: __m128i) -> __m128i {
        unsafe { _mm_max_epi32(a, b) }
    }
    #[doc = "See [`arch::_mm_max_epu32`]."]
    #[inline(always)]
    pub fn _mm_max_epu32(self, a: __m128i, b: __m128i) -> __m128i {
        unsafe { _mm_max_epu32(a, b) }
    }
    #[doc = "See [`arch::_mm_min_epi8`]."]
    #[inline(always)]
    pub fn _mm_min_epi8(self, a: __m128i, b: __m128i) -> __m128i {
        unsafe { _mm_min_epi8(a, b) }
    }
    #[doc = "See [`arch::_mm_min_epu16`]."]
    #[inline(always)]
    pub fn _mm_min_epu16(self, a: __m128i, b: __m128i) -> __m128i {
        unsafe { _mm_min_epu16(a, b) }
    }
    #[doc = "See [`arch::_mm_min_epi32`]."]
    #[inline(always)]
    pub fn _mm_min_epi32(self, a: __m128i, b: __m128i) -> __m128i {
        unsafe { _mm_min_epi32(a, b) }
    }
    #[doc = "See [`arch::_mm_min_epu32`]."]
    #[inline(always)]
    pub fn _mm_min_epu32(self, a: __m128i, b: __m128i) -> __m128i {
        unsafe { _mm_min_epu32(a, b) }
    }
    #[doc = "See [`arch::_mm_packus_epi32`]."]
    #[inline(always)]
    pub fn _mm_packus_epi32(self, a: __m128i, b: __m128i) -> __m128i {
        unsafe { _mm_packus_epi32(a, b) }
    }
    #[doc = "See [`arch::_mm_cmpeq_epi64`]."]
    #[inline(always)]
    pub fn _mm_cmpeq_epi64(self, a: __m128i, b: __m128i) -> __m128i {
        unsafe { _mm_cmpeq_epi64(a, b) }
    }
    #[doc = "See [`arch::_mm_cvtepi8_epi16`]."]
    #[inline(always)]
    pub fn _mm_cvtepi8_epi16(self, a: __m128i) -> __m128i {
        unsafe { _mm_cvtepi8_epi16(a) }
    }
    #[doc = "See [`arch::_mm_cvtepi8_epi32`]."]
    #[inline(always)]
    pub fn _mm_cvtepi8_epi32(self, a: __m128i) -> __m128i {
        unsafe { _mm_cvtepi8_epi32(a) }
    }
    #[doc = "See [`arch::_mm_cvtepi8_epi64`]."]
    #[inline(always)]
    pub fn _mm_cvtepi8_epi64(self, a: __m128i) -> __m128i {
        unsafe { _mm_cvtepi8_epi64(a) }
    }
    #[doc = "See [`arch::_mm_cvtepi16_epi32`]."]
    #[inline(always)]
    pub fn _mm_cvtepi16_epi32(self, a: __m128i) -> __m128i {
        unsafe { _mm_cvtepi16_epi32(a) }
    }
    #[doc = "See [`arch::_mm_cvtepi16_epi64`]."]
    #[inline(always)]
    pub fn _mm_cvtepi16_epi64(self, a: __m128i) -> __m128i {
        unsafe { _mm_cvtepi16_epi64(a) }
    }
    #[doc = "See [`arch::_mm_cvtepi32_epi64`]."]
    #[inline(always)]
    pub fn _mm_cvtepi32_epi64(self, a: __m128i) -> __m128i {
        unsafe { _mm_cvtepi32_epi64(a) }
    }
    #[doc = "See [`arch::_mm_cvtepu8_epi16`]."]
    #[inline(always)]
    pub fn _mm_cvtepu8_epi16(self, a: __m128i) -> __m128i {
        unsafe { _mm_cvtepu8_epi16(a) }
    }
    #[doc = "See [`arch::_mm_cvtepu8_epi32`]."]
    #[inline(always)]
    pub fn _mm_cvtepu8_epi32(self, a: __m128i) -> __m128i {
        unsafe { _mm_cvtepu8_epi32(a) }
    }
    #[doc = "See [`arch::_mm_cvtepu8_epi64`]."]
    #[inline(always)]
    pub fn _mm_cvtepu8_epi64(self, a: __m128i) -> __m128i {
        unsafe { _mm_cvtepu8_epi64(a) }
    }
    #[doc = "See [`arch::_mm_cvtepu16_epi32`]."]
    #[inline(always)]
    pub fn _mm_cvtepu16_epi32(self, a: __m128i) -> __m128i {
        unsafe { _mm_cvtepu16_epi32(a) }
    }
    #[doc = "See [`arch::_mm_cvtepu16_epi64`]."]
    #[inline(always)]
    pub fn _mm_cvtepu16_epi64(self, a: __m128i) -> __m128i {
        unsafe { _mm_cvtepu16_epi64(a) }
    }
    #[doc = "See [`arch::_mm_cvtepu32_epi64`]."]
    #[inline(always)]
    pub fn _mm_cvtepu32_epi64(self, a: __m128i) -> __m128i {
        unsafe { _mm_cvtepu32_epi64(a) }
    }
    #[doc = "See [`arch::_mm_dp_pd`]."]
    #[inline(always)]
    pub fn _mm_dp_pd<const IMM8: i32>(self, a: __m128d, b: __m128d) -> __m128d {
        unsafe { _mm_dp_pd::<IMM8>(a, b) }
    }
    #[doc = "See [`arch::_mm_dp_ps`]."]
    #[inline(always)]
    pub fn _mm_dp_ps<const IMM8: i32>(self, a: __m128, b: __m128) -> __m128 {
        unsafe { _mm_dp_ps::<IMM8>(a, b) }
    }
    #[doc = "See [`arch::_mm_floor_pd`]."]
    #[inline(always)]
    pub fn _mm_floor_pd(self, a: __m128d) -> __m128d {
        unsafe { _mm_floor_pd(a) }
    }
    #[doc = "See [`arch::_mm_floor_ps`]."]
    #[inline(always)]
    pub fn _mm_floor_ps(self, a: __m128) -> __m128 {
        unsafe { _mm_floor_ps(a) }
    }
    #[doc = "See [`arch::_mm_floor_sd`]."]
    #[inline(always)]
    pub fn _mm_floor_sd(self, a: __m128d, b: __m128d) -> __m128d {
        unsafe { _mm_floor_sd(a, b) }
    }
    #[doc = "See [`arch::_mm_floor_ss`]."]
    #[inline(always)]
    pub fn _mm_floor_ss(self, a: __m128, b: __m128) -> __m128 {
        unsafe { _mm_floor_ss(a, b) }
    }
    #[doc = "See [`arch::_mm_ceil_pd`]."]
    #[inline(always)]
    pub fn _mm_ceil_pd(self, a: __m128d) -> __m128d {
        unsafe { _mm_ceil_pd(a) }
    }
    #[doc = "See [`arch::_mm_ceil_ps`]."]
    #[inline(always)]
    pub fn _mm_ceil_ps(self, a: __m128) -> __m128 {
        unsafe { _mm_ceil_ps(a) }
    }
    #[doc = "See [`arch::_mm_ceil_sd`]."]
    #[inline(always)]
    pub fn _mm_ceil_sd(self, a: __m128d, b: __m128d) -> __m128d {
        unsafe { _mm_ceil_sd(a, b) }
    }
    #[doc = "See [`arch::_mm_ceil_ss`]."]
    #[inline(always)]
    pub fn _mm_ceil_ss(self, a: __m128, b: __m128) -> __m128 {
        unsafe { _mm_ceil_ss(a, b) }
    }
    #[doc = "See [`arch::_mm_round_pd`]."]
    #[inline(always)]
    pub fn _mm_round_pd<const ROUNDING: i32>(self, a: __m128d) -> __m128d {
        unsafe { _mm_round_pd::<ROUNDING>(a) }
    }
    #[doc = "See [`arch::_mm_round_ps`]."]
    #[inline(always)]
    pub fn _mm_round_ps<const ROUNDING: i32>(self, a: __m128) -> __m128 {
        unsafe { _mm_round_ps::<ROUNDING>(a) }
    }
    #[doc = "See [`arch::_mm_round_sd`]."]
    #[inline(always)]
    pub fn _mm_round_sd<const ROUNDING: i32>(self, a: __m128d, b: __m128d) -> __m128d {
        unsafe { _mm_round_sd::<ROUNDING>(a, b) }
    }
    #[doc = "See [`arch::_mm_round_ss`]."]
    #[inline(always)]
    pub fn _mm_round_ss<const ROUNDING: i32>(self, a: __m128, b: __m128) -> __m128 {
        unsafe { _mm_round_ss::<ROUNDING>(a, b) }
    }
    #[doc = "See [`arch::_mm_minpos_epu16`]."]
    #[inline(always)]
    pub fn _mm_minpos_epu16(self, a: __m128i) -> __m128i {
        unsafe { _mm_minpos_epu16(a) }
    }
    #[doc = "See [`arch::_mm_mul_epi32`]."]
    #[inline(always)]
    pub fn _mm_mul_epi32(self, a: __m128i, b: __m128i) -> __m128i {
        unsafe { _mm_mul_epi32(a, b) }
    }
    #[doc = "See [`arch::_mm_mullo_epi32`]."]
    #[inline(always)]
    pub fn _mm_mullo_epi32(self, a: __m128i, b: __m128i) -> __m128i {
        unsafe { _mm_mullo_epi32(a, b) }
    }
    #[doc = "See [`arch::_mm_mpsadbw_epu8`]."]
    #[inline(always)]
    pub fn _mm_mpsadbw_epu8<const IMM8: i32>(self, a: __m128i, b: __m128i) -> __m128i {
        unsafe { _mm_mpsadbw_epu8::<IMM8>(a, b) }
    }
    #[doc = "See [`arch::_mm_testz_si128`]."]
    #[inline(always)]
    pub fn _mm_testz_si128(self, a: __m128i, mask: __m128i) -> i32 {
        unsafe { _mm_testz_si128(a, mask) }
    }
    #[doc = "See [`arch::_mm_testc_si128`]."]
    #[inline(always)]
    pub fn _mm_testc_si128(self, a: __m128i, mask: __m128i) -> i32 {
        unsafe { _mm_testc_si128(a, mask) }
    }
    #[doc = "See [`arch::_mm_testnzc_si128`]."]
    #[inline(always)]
    pub fn _mm_testnzc_si128(self, a: __m128i, mask: __m128i) -> i32 {
        unsafe { _mm_testnzc_si128(a, mask) }
    }
    #[doc = "See [`arch::_mm_test_all_zeros`]."]
    #[inline(always)]
    pub fn _mm_test_all_zeros(self, a: __m128i, mask: __m128i) -> i32 {
        unsafe { _mm_test_all_zeros(a, mask) }
    }
    #[doc = "See [`arch::_mm_test_all_ones`]."]
    #[inline(always)]
    pub fn _mm_test_all_ones(self, a: __m128i) -> i32 {
        unsafe { _mm_test_all_ones(a) }
    }
    #[doc = "See [`arch::_mm_test_mix_ones_zeros`]."]
    #[inline(always)]
    pub fn _mm_test_mix_ones_zeros(self, a: __m128i, mask: __m128i) -> i32 {
        unsafe { _mm_test_mix_ones_zeros(a, mask) }
    }
    #[doc = "See [`arch::_mm_stream_load_si128`]."]
    #[inline(always)]
    pub unsafe fn _mm_stream_load_si128(self, mem_addr: *const __m128i) -> __m128i {
        unsafe { _mm_stream_load_si128(mem_addr) }
    }
}
