// Copyright 2026 the Fearless_SIMD Authors
// SPDX-License-Identifier: Apache-2.0 OR MIT

// This file is autogenerated by fearless_simd_gen

use arch::*;
#[cfg(target_arch = "x86")]
use core::arch::x86 as arch;
#[cfg(target_arch = "x86_64")]
use core::arch::x86_64 as arch;
#[doc = "A token for `Ssse3` intrinsics on `x86` and `x86_64`."]
#[derive(Clone, Copy, Debug)]
pub struct Ssse3 {
    _private: (),
}
#[allow(
    clippy::missing_safety_doc,
    reason = "The underlying functions have their own safety docs"
)]
impl Ssse3 {
    #[doc = r" Create a SIMD token."]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" The required CPU features must be available."]
    #[inline]
    pub const unsafe fn new_unchecked() -> Self {
        Self { _private: () }
    }
    #[doc = "See [`arch::_mm_abs_epi8`]."]
    #[inline(always)]
    pub fn _mm_abs_epi8(self, a: __m128i) -> __m128i {
        unsafe { _mm_abs_epi8(a) }
    }
    #[doc = "See [`arch::_mm_abs_epi16`]."]
    #[inline(always)]
    pub fn _mm_abs_epi16(self, a: __m128i) -> __m128i {
        unsafe { _mm_abs_epi16(a) }
    }
    #[doc = "See [`arch::_mm_abs_epi32`]."]
    #[inline(always)]
    pub fn _mm_abs_epi32(self, a: __m128i) -> __m128i {
        unsafe { _mm_abs_epi32(a) }
    }
    #[doc = "See [`arch::_mm_shuffle_epi8`]."]
    #[inline(always)]
    pub fn _mm_shuffle_epi8(self, a: __m128i, b: __m128i) -> __m128i {
        unsafe { _mm_shuffle_epi8(a, b) }
    }
    #[doc = "See [`arch::_mm_alignr_epi8`]."]
    #[inline(always)]
    pub fn _mm_alignr_epi8<const IMM8: i32>(self, a: __m128i, b: __m128i) -> __m128i {
        unsafe { _mm_alignr_epi8::<IMM8>(a, b) }
    }
    #[doc = "See [`arch::_mm_hadd_epi16`]."]
    #[inline(always)]
    pub fn _mm_hadd_epi16(self, a: __m128i, b: __m128i) -> __m128i {
        unsafe { _mm_hadd_epi16(a, b) }
    }
    #[doc = "See [`arch::_mm_hadds_epi16`]."]
    #[inline(always)]
    pub fn _mm_hadds_epi16(self, a: __m128i, b: __m128i) -> __m128i {
        unsafe { _mm_hadds_epi16(a, b) }
    }
    #[doc = "See [`arch::_mm_hadd_epi32`]."]
    #[inline(always)]
    pub fn _mm_hadd_epi32(self, a: __m128i, b: __m128i) -> __m128i {
        unsafe { _mm_hadd_epi32(a, b) }
    }
    #[doc = "See [`arch::_mm_hsub_epi16`]."]
    #[inline(always)]
    pub fn _mm_hsub_epi16(self, a: __m128i, b: __m128i) -> __m128i {
        unsafe { _mm_hsub_epi16(a, b) }
    }
    #[doc = "See [`arch::_mm_hsubs_epi16`]."]
    #[inline(always)]
    pub fn _mm_hsubs_epi16(self, a: __m128i, b: __m128i) -> __m128i {
        unsafe { _mm_hsubs_epi16(a, b) }
    }
    #[doc = "See [`arch::_mm_hsub_epi32`]."]
    #[inline(always)]
    pub fn _mm_hsub_epi32(self, a: __m128i, b: __m128i) -> __m128i {
        unsafe { _mm_hsub_epi32(a, b) }
    }
    #[doc = "See [`arch::_mm_maddubs_epi16`]."]
    #[inline(always)]
    pub fn _mm_maddubs_epi16(self, a: __m128i, b: __m128i) -> __m128i {
        unsafe { _mm_maddubs_epi16(a, b) }
    }
    #[doc = "See [`arch::_mm_mulhrs_epi16`]."]
    #[inline(always)]
    pub fn _mm_mulhrs_epi16(self, a: __m128i, b: __m128i) -> __m128i {
        unsafe { _mm_mulhrs_epi16(a, b) }
    }
    #[doc = "See [`arch::_mm_sign_epi8`]."]
    #[inline(always)]
    pub fn _mm_sign_epi8(self, a: __m128i, b: __m128i) -> __m128i {
        unsafe { _mm_sign_epi8(a, b) }
    }
    #[doc = "See [`arch::_mm_sign_epi16`]."]
    #[inline(always)]
    pub fn _mm_sign_epi16(self, a: __m128i, b: __m128i) -> __m128i {
        unsafe { _mm_sign_epi16(a, b) }
    }
    #[doc = "See [`arch::_mm_sign_epi32`]."]
    #[inline(always)]
    pub fn _mm_sign_epi32(self, a: __m128i, b: __m128i) -> __m128i {
        unsafe { _mm_sign_epi32(a, b) }
    }
}
