// This file is automatically generated by `fearless_simd_core_gen`.
// Its template can be found in `fearless_simd_core/gen/templates`.

//! The AVX-IFMA target feature.

use crate::{TargetFeatureToken, trampoline};

use core::fmt::Debug;

/// [AVX-IFMA] --- Advanced Vector Extensions - Integer Fused Multiply Add
///
/// [AVX-IFMA]: https://en.wikipedia.org/wiki/Advanced_Vector_Extensions#AVX-VNNI,_AVX-IFMA
///
/// A token indicating that the current CPU has the `avxifma` target feature.
///
/// # Example
///
/// This can be used to [`trampoline!`] into functions like:
///
/// ```rust
/// #[cfg(any(target_arch = "x86", target_arch = "x86_64"))]
/// #[target_feature(enable = "avxifma")]
/// fn uses_avxifma() {
///     // ...
/// }
/// ```
#[derive(Copy, Clone, Hash, PartialEq, Eq)]
pub struct Avxifma {
    // We don't use non_exhaustive because we don't want this struct to be constructible.
    // in different modules in this crate.
    _private: (),
}

impl Debug for Avxifma {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, r#""avxifma" enabled."#)
    }
}

unsafe impl TargetFeatureToken for Avxifma {
    const FEATURES: &[&str] = &[
        "avxifma", "avx", "avx2", "sse", "sse2", "sse3", "sse4.1", "sse4.2", "ssse3",
    ];

    #[inline(always)]
    fn vectorize<R>(self, f: impl FnOnce() -> R) -> R {
        // Because we want this constant to be eagerly evaluated.
        trampoline!([Avxifma = self] => "avxifma", <(R)> fn<(R)>(f: impl FnOnce() -> R = f) -> R { f() })
    }
}

impl Avxifma {
    #[cfg(feature = "std")]
    /// Create a new token if the `"avxifma"` target feature is detected as enabled.
    ///
    /// This does not do any caching internally, although note that the standard
    /// library does internally cache the features it detects.
    // TODO: Consider a manual override feature/env var?
    pub fn try_new() -> Option<Self> {
        // Feature flag required to make docs compile.
        // TODO: Extract into a (private) crate::x86::is_x86_feature_detected?
        #[cfg(any(target_arch = "x86", target_arch = "x86_64"))]
        if std::arch::is_x86_feature_detected!("avxifma") {
            // Safety: The required CPU feature was detected.
            unsafe { Some(Self::new()) }
        } else {
            None
        }
    }

    #[target_feature(enable = "avxifma")]
    /// Create a new token for the "avxifma" target feature.
    ///
    /// This method is useful to get a new token if you have an external proof that
    /// AVX-IFMA is available. This could happen if you are in a target feature
    /// function called by an external library user.
    ///
    /// # Safety
    ///
    /// No conditions other than those inherited from the target feature attribute,
    /// i.e. that the "avxifma" target feature is available.
    ///
    /// [implicitly enables]: https://doc.rust-lang.org/beta/reference/attributes/codegen.html?highlight=implicitly%20enabled#r-attributes.codegen.target_feature.safety-restrictions
    pub fn new() -> Self {
        Self { _private: () }
    }
}

impl From<Avxifma> for crate::x86::avx::Avx {
    fn from(value: Avxifma) -> Self {
        // This also serves as a correctness check of the implicitly enabled features.
        trampoline!([Avxifma = value] => "avxifma", fn() -> crate::x86::avx::Avx { crate::x86::avx::Avx::new() })
    }
}

impl From<Avxifma> for crate::x86::avx::Avx2 {
    fn from(value: Avxifma) -> Self {
        // This also serves as a correctness check of the implicitly enabled features.
        trampoline!([Avxifma = value] => "avxifma", fn() -> crate::x86::avx::Avx2 { crate::x86::avx::Avx2::new() })
    }
}

impl From<Avxifma> for crate::x86::sse::Sse {
    fn from(value: Avxifma) -> Self {
        // This also serves as a correctness check of the implicitly enabled features.
        trampoline!([Avxifma = value] => "avxifma", fn() -> crate::x86::sse::Sse { crate::x86::sse::Sse::new() })
    }
}

impl From<Avxifma> for crate::x86::sse::Sse2 {
    fn from(value: Avxifma) -> Self {
        // This also serves as a correctness check of the implicitly enabled features.
        trampoline!([Avxifma = value] => "avxifma", fn() -> crate::x86::sse::Sse2 { crate::x86::sse::Sse2::new() })
    }
}

impl From<Avxifma> for crate::x86::sse::Sse3 {
    fn from(value: Avxifma) -> Self {
        // This also serves as a correctness check of the implicitly enabled features.
        trampoline!([Avxifma = value] => "avxifma", fn() -> crate::x86::sse::Sse3 { crate::x86::sse::Sse3::new() })
    }
}

impl From<Avxifma> for crate::x86::sse::Sse4_1 {
    fn from(value: Avxifma) -> Self {
        // This also serves as a correctness check of the implicitly enabled features.
        trampoline!([Avxifma = value] => "avxifma", fn() -> crate::x86::sse::Sse4_1 { crate::x86::sse::Sse4_1::new() })
    }
}

impl From<Avxifma> for crate::x86::sse::Sse4_2 {
    fn from(value: Avxifma) -> Self {
        // This also serves as a correctness check of the implicitly enabled features.
        trampoline!([Avxifma = value] => "avxifma", fn() -> crate::x86::sse::Sse4_2 { crate::x86::sse::Sse4_2::new() })
    }
}

impl From<Avxifma> for crate::x86::sse::SupplementalSse3 {
    fn from(value: Avxifma) -> Self {
        // This also serves as a correctness check of the implicitly enabled features.
        trampoline!([Avxifma = value] => "avxifma", fn() -> crate::x86::sse::SupplementalSse3 { crate::x86::sse::SupplementalSse3::new() })
    }
}

const _: () = {
    assert!(
        core::mem::size_of::<Avxifma>() == 0,
        "Target feature tokens should be zero sized."
    );
};
