// Copyright 2026 the Fearless_SIMD Authors
// SPDX-License-Identifier: Apache-2.0 OR MIT

// This file is autogenerated by fearless_simd_gen

use arch::*;
use core::arch::wasm32 as arch;
#[doc = "A token for `WasmSimd128` intrinsics on `wasm32`."]
#[derive(Clone, Copy, Debug)]
pub struct WasmSimd128 {
    _private: (),
}
#[allow(
    clippy::missing_safety_doc,
    reason = "The underlying functions have their own safety docs"
)]
impl WasmSimd128 {
    #[doc = r" Create a SIMD token."]
    #[inline]
    #[expect(
        clippy::new_without_default,
        reason = "other architectures have unsafe `new_unchecked` constructors and cannot implement `Default`; for symmetry, we do not do so either"
    )]
    pub const fn new() -> Self {
        Self { _private: () }
    }
    #[doc = "See [`arch::v128_load`]."]
    #[inline(always)]
    pub unsafe fn v128_load(self, m: *const v128) -> v128 {
        unsafe { v128_load(m) }
    }
    #[doc = "See [`arch::i16x8_load_extend_i8x8`]."]
    #[inline(always)]
    pub unsafe fn i16x8_load_extend_i8x8(self, m: *const i8) -> v128 {
        unsafe { i16x8_load_extend_i8x8(m) }
    }
    #[doc = "See [`arch::i16x8_load_extend_u8x8`]."]
    #[inline(always)]
    pub unsafe fn i16x8_load_extend_u8x8(self, m: *const u8) -> v128 {
        unsafe { i16x8_load_extend_u8x8(m) }
    }
    #[doc = "See [`arch::i32x4_load_extend_i16x4`]."]
    #[inline(always)]
    pub unsafe fn i32x4_load_extend_i16x4(self, m: *const i16) -> v128 {
        unsafe { i32x4_load_extend_i16x4(m) }
    }
    #[doc = "See [`arch::i32x4_load_extend_u16x4`]."]
    #[inline(always)]
    pub unsafe fn i32x4_load_extend_u16x4(self, m: *const u16) -> v128 {
        unsafe { i32x4_load_extend_u16x4(m) }
    }
    #[doc = "See [`arch::i64x2_load_extend_i32x2`]."]
    #[inline(always)]
    pub unsafe fn i64x2_load_extend_i32x2(self, m: *const i32) -> v128 {
        unsafe { i64x2_load_extend_i32x2(m) }
    }
    #[doc = "See [`arch::i64x2_load_extend_u32x2`]."]
    #[inline(always)]
    pub unsafe fn i64x2_load_extend_u32x2(self, m: *const u32) -> v128 {
        unsafe { i64x2_load_extend_u32x2(m) }
    }
    #[doc = "See [`arch::v128_load8_splat`]."]
    #[inline(always)]
    pub unsafe fn v128_load8_splat(self, m: *const u8) -> v128 {
        unsafe { v128_load8_splat(m) }
    }
    #[doc = "See [`arch::v128_load16_splat`]."]
    #[inline(always)]
    pub unsafe fn v128_load16_splat(self, m: *const u16) -> v128 {
        unsafe { v128_load16_splat(m) }
    }
    #[doc = "See [`arch::v128_load32_splat`]."]
    #[inline(always)]
    pub unsafe fn v128_load32_splat(self, m: *const u32) -> v128 {
        unsafe { v128_load32_splat(m) }
    }
    #[doc = "See [`arch::v128_load64_splat`]."]
    #[inline(always)]
    pub unsafe fn v128_load64_splat(self, m: *const u64) -> v128 {
        unsafe { v128_load64_splat(m) }
    }
    #[doc = "See [`arch::v128_load32_zero`]."]
    #[inline(always)]
    pub unsafe fn v128_load32_zero(self, m: *const u32) -> v128 {
        unsafe { v128_load32_zero(m) }
    }
    #[doc = "See [`arch::v128_load64_zero`]."]
    #[inline(always)]
    pub unsafe fn v128_load64_zero(self, m: *const u64) -> v128 {
        unsafe { v128_load64_zero(m) }
    }
    #[doc = "See [`arch::v128_store`]."]
    #[inline(always)]
    pub unsafe fn v128_store(self, m: *mut v128, a: v128) {
        unsafe { v128_store(m, a) }
    }
    #[doc = "See [`arch::v128_load8_lane`]."]
    #[inline(always)]
    pub unsafe fn v128_load8_lane<const L: usize>(self, v: v128, m: *const u8) -> v128 {
        unsafe { v128_load8_lane::<L>(v, m) }
    }
    #[doc = "See [`arch::v128_load16_lane`]."]
    #[inline(always)]
    pub unsafe fn v128_load16_lane<const L: usize>(self, v: v128, m: *const u16) -> v128 {
        unsafe { v128_load16_lane::<L>(v, m) }
    }
    #[doc = "See [`arch::v128_load32_lane`]."]
    #[inline(always)]
    pub unsafe fn v128_load32_lane<const L: usize>(self, v: v128, m: *const u32) -> v128 {
        unsafe { v128_load32_lane::<L>(v, m) }
    }
    #[doc = "See [`arch::v128_load64_lane`]."]
    #[inline(always)]
    pub unsafe fn v128_load64_lane<const L: usize>(self, v: v128, m: *const u64) -> v128 {
        unsafe { v128_load64_lane::<L>(v, m) }
    }
    #[doc = "See [`arch::v128_store8_lane`]."]
    #[inline(always)]
    pub unsafe fn v128_store8_lane<const L: usize>(self, v: v128, m: *mut u8) {
        unsafe { v128_store8_lane::<L>(v, m) }
    }
    #[doc = "See [`arch::v128_store16_lane`]."]
    #[inline(always)]
    pub unsafe fn v128_store16_lane<const L: usize>(self, v: v128, m: *mut u16) {
        unsafe { v128_store16_lane::<L>(v, m) }
    }
    #[doc = "See [`arch::v128_store32_lane`]."]
    #[inline(always)]
    pub unsafe fn v128_store32_lane<const L: usize>(self, v: v128, m: *mut u32) {
        unsafe { v128_store32_lane::<L>(v, m) }
    }
    #[doc = "See [`arch::v128_store64_lane`]."]
    #[inline(always)]
    pub unsafe fn v128_store64_lane<const L: usize>(self, v: v128, m: *mut u64) {
        unsafe { v128_store64_lane::<L>(v, m) }
    }
    #[doc = "See [`arch::i8x16`]."]
    #[inline(always)]
    pub fn i8x16(
        self,
        a0: i8,
        a1: i8,
        a2: i8,
        a3: i8,
        a4: i8,
        a5: i8,
        a6: i8,
        a7: i8,
        a8: i8,
        a9: i8,
        a10: i8,
        a11: i8,
        a12: i8,
        a13: i8,
        a14: i8,
        a15: i8,
    ) -> v128 {
        unsafe {
            i8x16(
                a0, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15,
            )
        }
    }
    #[doc = "See [`arch::u8x16`]."]
    #[inline(always)]
    pub fn u8x16(
        self,
        a0: u8,
        a1: u8,
        a2: u8,
        a3: u8,
        a4: u8,
        a5: u8,
        a6: u8,
        a7: u8,
        a8: u8,
        a9: u8,
        a10: u8,
        a11: u8,
        a12: u8,
        a13: u8,
        a14: u8,
        a15: u8,
    ) -> v128 {
        unsafe {
            u8x16(
                a0, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15,
            )
        }
    }
    #[doc = "See [`arch::i16x8`]."]
    #[inline(always)]
    pub fn i16x8(
        self,
        a0: i16,
        a1: i16,
        a2: i16,
        a3: i16,
        a4: i16,
        a5: i16,
        a6: i16,
        a7: i16,
    ) -> v128 {
        unsafe { i16x8(a0, a1, a2, a3, a4, a5, a6, a7) }
    }
    #[doc = "See [`arch::u16x8`]."]
    #[inline(always)]
    pub fn u16x8(
        self,
        a0: u16,
        a1: u16,
        a2: u16,
        a3: u16,
        a4: u16,
        a5: u16,
        a6: u16,
        a7: u16,
    ) -> v128 {
        unsafe { u16x8(a0, a1, a2, a3, a4, a5, a6, a7) }
    }
    #[doc = "See [`arch::i32x4`]."]
    #[inline(always)]
    pub fn i32x4(self, a0: i32, a1: i32, a2: i32, a3: i32) -> v128 {
        unsafe { i32x4(a0, a1, a2, a3) }
    }
    #[doc = "See [`arch::u32x4`]."]
    #[inline(always)]
    pub fn u32x4(self, a0: u32, a1: u32, a2: u32, a3: u32) -> v128 {
        unsafe { u32x4(a0, a1, a2, a3) }
    }
    #[doc = "See [`arch::i64x2`]."]
    #[inline(always)]
    pub fn i64x2(self, a0: i64, a1: i64) -> v128 {
        unsafe { i64x2(a0, a1) }
    }
    #[doc = "See [`arch::u64x2`]."]
    #[inline(always)]
    pub fn u64x2(self, a0: u64, a1: u64) -> v128 {
        unsafe { u64x2(a0, a1) }
    }
    #[doc = "See [`arch::f32x4`]."]
    #[inline(always)]
    pub fn f32x4(self, a0: f32, a1: f32, a2: f32, a3: f32) -> v128 {
        unsafe { f32x4(a0, a1, a2, a3) }
    }
    #[doc = "See [`arch::f64x2`]."]
    #[inline(always)]
    pub fn f64x2(self, a0: f64, a1: f64) -> v128 {
        unsafe { f64x2(a0, a1) }
    }
    #[doc = "See [`arch::i8x16_shuffle`]."]
    #[inline(always)]
    pub fn i8x16_shuffle<
        const I0: usize,
        const I1: usize,
        const I2: usize,
        const I3: usize,
        const I4: usize,
        const I5: usize,
        const I6: usize,
        const I7: usize,
        const I8: usize,
        const I9: usize,
        const I10: usize,
        const I11: usize,
        const I12: usize,
        const I13: usize,
        const I14: usize,
        const I15: usize,
    >(
        self,
        a: v128,
        b: v128,
    ) -> v128 {
        unsafe {
            i8x16_shuffle::<I0, I1, I2, I3, I4, I5, I6, I7, I8, I9, I10, I11, I12, I13, I14, I15>(
                a, b,
            )
        }
    }
    #[doc = "See [`arch::i16x8_shuffle`]."]
    #[inline(always)]
    pub fn i16x8_shuffle<
        const I0: usize,
        const I1: usize,
        const I2: usize,
        const I3: usize,
        const I4: usize,
        const I5: usize,
        const I6: usize,
        const I7: usize,
    >(
        self,
        a: v128,
        b: v128,
    ) -> v128 {
        unsafe { i16x8_shuffle::<I0, I1, I2, I3, I4, I5, I6, I7>(a, b) }
    }
    #[doc = "See [`arch::i32x4_shuffle`]."]
    #[inline(always)]
    pub fn i32x4_shuffle<const I0: usize, const I1: usize, const I2: usize, const I3: usize>(
        self,
        a: v128,
        b: v128,
    ) -> v128 {
        unsafe { i32x4_shuffle::<I0, I1, I2, I3>(a, b) }
    }
    #[doc = "See [`arch::i64x2_shuffle`]."]
    #[inline(always)]
    pub fn i64x2_shuffle<const I0: usize, const I1: usize>(self, a: v128, b: v128) -> v128 {
        unsafe { i64x2_shuffle::<I0, I1>(a, b) }
    }
    #[doc = "See [`arch::i8x16_extract_lane`]."]
    #[inline(always)]
    pub fn i8x16_extract_lane<const N: usize>(self, a: v128) -> i8 {
        unsafe { i8x16_extract_lane::<N>(a) }
    }
    #[doc = "See [`arch::u8x16_extract_lane`]."]
    #[inline(always)]
    pub fn u8x16_extract_lane<const N: usize>(self, a: v128) -> u8 {
        unsafe { u8x16_extract_lane::<N>(a) }
    }
    #[doc = "See [`arch::i8x16_replace_lane`]."]
    #[inline(always)]
    pub fn i8x16_replace_lane<const N: usize>(self, a: v128, val: i8) -> v128 {
        unsafe { i8x16_replace_lane::<N>(a, val) }
    }
    #[doc = "See [`arch::u8x16_replace_lane`]."]
    #[inline(always)]
    pub fn u8x16_replace_lane<const N: usize>(self, a: v128, val: u8) -> v128 {
        unsafe { u8x16_replace_lane::<N>(a, val) }
    }
    #[doc = "See [`arch::i16x8_extract_lane`]."]
    #[inline(always)]
    pub fn i16x8_extract_lane<const N: usize>(self, a: v128) -> i16 {
        unsafe { i16x8_extract_lane::<N>(a) }
    }
    #[doc = "See [`arch::u16x8_extract_lane`]."]
    #[inline(always)]
    pub fn u16x8_extract_lane<const N: usize>(self, a: v128) -> u16 {
        unsafe { u16x8_extract_lane::<N>(a) }
    }
    #[doc = "See [`arch::i16x8_replace_lane`]."]
    #[inline(always)]
    pub fn i16x8_replace_lane<const N: usize>(self, a: v128, val: i16) -> v128 {
        unsafe { i16x8_replace_lane::<N>(a, val) }
    }
    #[doc = "See [`arch::u16x8_replace_lane`]."]
    #[inline(always)]
    pub fn u16x8_replace_lane<const N: usize>(self, a: v128, val: u16) -> v128 {
        unsafe { u16x8_replace_lane::<N>(a, val) }
    }
    #[doc = "See [`arch::i32x4_extract_lane`]."]
    #[inline(always)]
    pub fn i32x4_extract_lane<const N: usize>(self, a: v128) -> i32 {
        unsafe { i32x4_extract_lane::<N>(a) }
    }
    #[doc = "See [`arch::u32x4_extract_lane`]."]
    #[inline(always)]
    pub fn u32x4_extract_lane<const N: usize>(self, a: v128) -> u32 {
        unsafe { u32x4_extract_lane::<N>(a) }
    }
    #[doc = "See [`arch::i32x4_replace_lane`]."]
    #[inline(always)]
    pub fn i32x4_replace_lane<const N: usize>(self, a: v128, val: i32) -> v128 {
        unsafe { i32x4_replace_lane::<N>(a, val) }
    }
    #[doc = "See [`arch::u32x4_replace_lane`]."]
    #[inline(always)]
    pub fn u32x4_replace_lane<const N: usize>(self, a: v128, val: u32) -> v128 {
        unsafe { u32x4_replace_lane::<N>(a, val) }
    }
    #[doc = "See [`arch::i64x2_extract_lane`]."]
    #[inline(always)]
    pub fn i64x2_extract_lane<const N: usize>(self, a: v128) -> i64 {
        unsafe { i64x2_extract_lane::<N>(a) }
    }
    #[doc = "See [`arch::u64x2_extract_lane`]."]
    #[inline(always)]
    pub fn u64x2_extract_lane<const N: usize>(self, a: v128) -> u64 {
        unsafe { u64x2_extract_lane::<N>(a) }
    }
    #[doc = "See [`arch::i64x2_replace_lane`]."]
    #[inline(always)]
    pub fn i64x2_replace_lane<const N: usize>(self, a: v128, val: i64) -> v128 {
        unsafe { i64x2_replace_lane::<N>(a, val) }
    }
    #[doc = "See [`arch::u64x2_replace_lane`]."]
    #[inline(always)]
    pub fn u64x2_replace_lane<const N: usize>(self, a: v128, val: u64) -> v128 {
        unsafe { u64x2_replace_lane::<N>(a, val) }
    }
    #[doc = "See [`arch::f32x4_extract_lane`]."]
    #[inline(always)]
    pub fn f32x4_extract_lane<const N: usize>(self, a: v128) -> f32 {
        unsafe { f32x4_extract_lane::<N>(a) }
    }
    #[doc = "See [`arch::f32x4_replace_lane`]."]
    #[inline(always)]
    pub fn f32x4_replace_lane<const N: usize>(self, a: v128, val: f32) -> v128 {
        unsafe { f32x4_replace_lane::<N>(a, val) }
    }
    #[doc = "See [`arch::f64x2_extract_lane`]."]
    #[inline(always)]
    pub fn f64x2_extract_lane<const N: usize>(self, a: v128) -> f64 {
        unsafe { f64x2_extract_lane::<N>(a) }
    }
    #[doc = "See [`arch::f64x2_replace_lane`]."]
    #[inline(always)]
    pub fn f64x2_replace_lane<const N: usize>(self, a: v128, val: f64) -> v128 {
        unsafe { f64x2_replace_lane::<N>(a, val) }
    }
    #[doc = "See [`arch::i8x16_swizzle`]."]
    #[inline(always)]
    pub fn i8x16_swizzle(self, a: v128, s: v128) -> v128 {
        unsafe { i8x16_swizzle(a, s) }
    }
    #[doc = "See [`arch::i8x16_splat`]."]
    #[inline(always)]
    pub fn i8x16_splat(self, a: i8) -> v128 {
        unsafe { i8x16_splat(a) }
    }
    #[doc = "See [`arch::u8x16_splat`]."]
    #[inline(always)]
    pub fn u8x16_splat(self, a: u8) -> v128 {
        unsafe { u8x16_splat(a) }
    }
    #[doc = "See [`arch::i16x8_splat`]."]
    #[inline(always)]
    pub fn i16x8_splat(self, a: i16) -> v128 {
        unsafe { i16x8_splat(a) }
    }
    #[doc = "See [`arch::u16x8_splat`]."]
    #[inline(always)]
    pub fn u16x8_splat(self, a: u16) -> v128 {
        unsafe { u16x8_splat(a) }
    }
    #[doc = "See [`arch::i32x4_splat`]."]
    #[inline(always)]
    pub fn i32x4_splat(self, a: i32) -> v128 {
        unsafe { i32x4_splat(a) }
    }
    #[doc = "See [`arch::u32x4_splat`]."]
    #[inline(always)]
    pub fn u32x4_splat(self, a: u32) -> v128 {
        unsafe { u32x4_splat(a) }
    }
    #[doc = "See [`arch::i64x2_splat`]."]
    #[inline(always)]
    pub fn i64x2_splat(self, a: i64) -> v128 {
        unsafe { i64x2_splat(a) }
    }
    #[doc = "See [`arch::u64x2_splat`]."]
    #[inline(always)]
    pub fn u64x2_splat(self, a: u64) -> v128 {
        unsafe { u64x2_splat(a) }
    }
    #[doc = "See [`arch::f32x4_splat`]."]
    #[inline(always)]
    pub fn f32x4_splat(self, a: f32) -> v128 {
        unsafe { f32x4_splat(a) }
    }
    #[doc = "See [`arch::f64x2_splat`]."]
    #[inline(always)]
    pub fn f64x2_splat(self, a: f64) -> v128 {
        unsafe { f64x2_splat(a) }
    }
    #[doc = "See [`arch::i8x16_eq`]."]
    #[inline(always)]
    pub fn i8x16_eq(self, a: v128, b: v128) -> v128 {
        unsafe { i8x16_eq(a, b) }
    }
    #[doc = "See [`arch::i8x16_ne`]."]
    #[inline(always)]
    pub fn i8x16_ne(self, a: v128, b: v128) -> v128 {
        unsafe { i8x16_ne(a, b) }
    }
    #[doc = "See [`arch::i8x16_lt`]."]
    #[inline(always)]
    pub fn i8x16_lt(self, a: v128, b: v128) -> v128 {
        unsafe { i8x16_lt(a, b) }
    }
    #[doc = "See [`arch::u8x16_lt`]."]
    #[inline(always)]
    pub fn u8x16_lt(self, a: v128, b: v128) -> v128 {
        unsafe { u8x16_lt(a, b) }
    }
    #[doc = "See [`arch::i8x16_gt`]."]
    #[inline(always)]
    pub fn i8x16_gt(self, a: v128, b: v128) -> v128 {
        unsafe { i8x16_gt(a, b) }
    }
    #[doc = "See [`arch::u8x16_gt`]."]
    #[inline(always)]
    pub fn u8x16_gt(self, a: v128, b: v128) -> v128 {
        unsafe { u8x16_gt(a, b) }
    }
    #[doc = "See [`arch::i8x16_le`]."]
    #[inline(always)]
    pub fn i8x16_le(self, a: v128, b: v128) -> v128 {
        unsafe { i8x16_le(a, b) }
    }
    #[doc = "See [`arch::u8x16_le`]."]
    #[inline(always)]
    pub fn u8x16_le(self, a: v128, b: v128) -> v128 {
        unsafe { u8x16_le(a, b) }
    }
    #[doc = "See [`arch::i8x16_ge`]."]
    #[inline(always)]
    pub fn i8x16_ge(self, a: v128, b: v128) -> v128 {
        unsafe { i8x16_ge(a, b) }
    }
    #[doc = "See [`arch::u8x16_ge`]."]
    #[inline(always)]
    pub fn u8x16_ge(self, a: v128, b: v128) -> v128 {
        unsafe { u8x16_ge(a, b) }
    }
    #[doc = "See [`arch::i16x8_eq`]."]
    #[inline(always)]
    pub fn i16x8_eq(self, a: v128, b: v128) -> v128 {
        unsafe { i16x8_eq(a, b) }
    }
    #[doc = "See [`arch::i16x8_ne`]."]
    #[inline(always)]
    pub fn i16x8_ne(self, a: v128, b: v128) -> v128 {
        unsafe { i16x8_ne(a, b) }
    }
    #[doc = "See [`arch::i16x8_lt`]."]
    #[inline(always)]
    pub fn i16x8_lt(self, a: v128, b: v128) -> v128 {
        unsafe { i16x8_lt(a, b) }
    }
    #[doc = "See [`arch::u16x8_lt`]."]
    #[inline(always)]
    pub fn u16x8_lt(self, a: v128, b: v128) -> v128 {
        unsafe { u16x8_lt(a, b) }
    }
    #[doc = "See [`arch::i16x8_gt`]."]
    #[inline(always)]
    pub fn i16x8_gt(self, a: v128, b: v128) -> v128 {
        unsafe { i16x8_gt(a, b) }
    }
    #[doc = "See [`arch::u16x8_gt`]."]
    #[inline(always)]
    pub fn u16x8_gt(self, a: v128, b: v128) -> v128 {
        unsafe { u16x8_gt(a, b) }
    }
    #[doc = "See [`arch::i16x8_le`]."]
    #[inline(always)]
    pub fn i16x8_le(self, a: v128, b: v128) -> v128 {
        unsafe { i16x8_le(a, b) }
    }
    #[doc = "See [`arch::u16x8_le`]."]
    #[inline(always)]
    pub fn u16x8_le(self, a: v128, b: v128) -> v128 {
        unsafe { u16x8_le(a, b) }
    }
    #[doc = "See [`arch::i16x8_ge`]."]
    #[inline(always)]
    pub fn i16x8_ge(self, a: v128, b: v128) -> v128 {
        unsafe { i16x8_ge(a, b) }
    }
    #[doc = "See [`arch::u16x8_ge`]."]
    #[inline(always)]
    pub fn u16x8_ge(self, a: v128, b: v128) -> v128 {
        unsafe { u16x8_ge(a, b) }
    }
    #[doc = "See [`arch::i32x4_eq`]."]
    #[inline(always)]
    pub fn i32x4_eq(self, a: v128, b: v128) -> v128 {
        unsafe { i32x4_eq(a, b) }
    }
    #[doc = "See [`arch::i32x4_ne`]."]
    #[inline(always)]
    pub fn i32x4_ne(self, a: v128, b: v128) -> v128 {
        unsafe { i32x4_ne(a, b) }
    }
    #[doc = "See [`arch::i32x4_lt`]."]
    #[inline(always)]
    pub fn i32x4_lt(self, a: v128, b: v128) -> v128 {
        unsafe { i32x4_lt(a, b) }
    }
    #[doc = "See [`arch::u32x4_lt`]."]
    #[inline(always)]
    pub fn u32x4_lt(self, a: v128, b: v128) -> v128 {
        unsafe { u32x4_lt(a, b) }
    }
    #[doc = "See [`arch::i32x4_gt`]."]
    #[inline(always)]
    pub fn i32x4_gt(self, a: v128, b: v128) -> v128 {
        unsafe { i32x4_gt(a, b) }
    }
    #[doc = "See [`arch::u32x4_gt`]."]
    #[inline(always)]
    pub fn u32x4_gt(self, a: v128, b: v128) -> v128 {
        unsafe { u32x4_gt(a, b) }
    }
    #[doc = "See [`arch::i32x4_le`]."]
    #[inline(always)]
    pub fn i32x4_le(self, a: v128, b: v128) -> v128 {
        unsafe { i32x4_le(a, b) }
    }
    #[doc = "See [`arch::u32x4_le`]."]
    #[inline(always)]
    pub fn u32x4_le(self, a: v128, b: v128) -> v128 {
        unsafe { u32x4_le(a, b) }
    }
    #[doc = "See [`arch::i32x4_ge`]."]
    #[inline(always)]
    pub fn i32x4_ge(self, a: v128, b: v128) -> v128 {
        unsafe { i32x4_ge(a, b) }
    }
    #[doc = "See [`arch::u32x4_ge`]."]
    #[inline(always)]
    pub fn u32x4_ge(self, a: v128, b: v128) -> v128 {
        unsafe { u32x4_ge(a, b) }
    }
    #[doc = "See [`arch::i64x2_eq`]."]
    #[inline(always)]
    pub fn i64x2_eq(self, a: v128, b: v128) -> v128 {
        unsafe { i64x2_eq(a, b) }
    }
    #[doc = "See [`arch::i64x2_ne`]."]
    #[inline(always)]
    pub fn i64x2_ne(self, a: v128, b: v128) -> v128 {
        unsafe { i64x2_ne(a, b) }
    }
    #[doc = "See [`arch::i64x2_lt`]."]
    #[inline(always)]
    pub fn i64x2_lt(self, a: v128, b: v128) -> v128 {
        unsafe { i64x2_lt(a, b) }
    }
    #[doc = "See [`arch::i64x2_gt`]."]
    #[inline(always)]
    pub fn i64x2_gt(self, a: v128, b: v128) -> v128 {
        unsafe { i64x2_gt(a, b) }
    }
    #[doc = "See [`arch::i64x2_le`]."]
    #[inline(always)]
    pub fn i64x2_le(self, a: v128, b: v128) -> v128 {
        unsafe { i64x2_le(a, b) }
    }
    #[doc = "See [`arch::i64x2_ge`]."]
    #[inline(always)]
    pub fn i64x2_ge(self, a: v128, b: v128) -> v128 {
        unsafe { i64x2_ge(a, b) }
    }
    #[doc = "See [`arch::f32x4_eq`]."]
    #[inline(always)]
    pub fn f32x4_eq(self, a: v128, b: v128) -> v128 {
        unsafe { f32x4_eq(a, b) }
    }
    #[doc = "See [`arch::f32x4_ne`]."]
    #[inline(always)]
    pub fn f32x4_ne(self, a: v128, b: v128) -> v128 {
        unsafe { f32x4_ne(a, b) }
    }
    #[doc = "See [`arch::f32x4_lt`]."]
    #[inline(always)]
    pub fn f32x4_lt(self, a: v128, b: v128) -> v128 {
        unsafe { f32x4_lt(a, b) }
    }
    #[doc = "See [`arch::f32x4_gt`]."]
    #[inline(always)]
    pub fn f32x4_gt(self, a: v128, b: v128) -> v128 {
        unsafe { f32x4_gt(a, b) }
    }
    #[doc = "See [`arch::f32x4_le`]."]
    #[inline(always)]
    pub fn f32x4_le(self, a: v128, b: v128) -> v128 {
        unsafe { f32x4_le(a, b) }
    }
    #[doc = "See [`arch::f32x4_ge`]."]
    #[inline(always)]
    pub fn f32x4_ge(self, a: v128, b: v128) -> v128 {
        unsafe { f32x4_ge(a, b) }
    }
    #[doc = "See [`arch::f64x2_eq`]."]
    #[inline(always)]
    pub fn f64x2_eq(self, a: v128, b: v128) -> v128 {
        unsafe { f64x2_eq(a, b) }
    }
    #[doc = "See [`arch::f64x2_ne`]."]
    #[inline(always)]
    pub fn f64x2_ne(self, a: v128, b: v128) -> v128 {
        unsafe { f64x2_ne(a, b) }
    }
    #[doc = "See [`arch::f64x2_lt`]."]
    #[inline(always)]
    pub fn f64x2_lt(self, a: v128, b: v128) -> v128 {
        unsafe { f64x2_lt(a, b) }
    }
    #[doc = "See [`arch::f64x2_gt`]."]
    #[inline(always)]
    pub fn f64x2_gt(self, a: v128, b: v128) -> v128 {
        unsafe { f64x2_gt(a, b) }
    }
    #[doc = "See [`arch::f64x2_le`]."]
    #[inline(always)]
    pub fn f64x2_le(self, a: v128, b: v128) -> v128 {
        unsafe { f64x2_le(a, b) }
    }
    #[doc = "See [`arch::f64x2_ge`]."]
    #[inline(always)]
    pub fn f64x2_ge(self, a: v128, b: v128) -> v128 {
        unsafe { f64x2_ge(a, b) }
    }
    #[doc = "See [`arch::v128_not`]."]
    #[inline(always)]
    pub fn v128_not(self, a: v128) -> v128 {
        unsafe { v128_not(a) }
    }
    #[doc = "See [`arch::v128_and`]."]
    #[inline(always)]
    pub fn v128_and(self, a: v128, b: v128) -> v128 {
        unsafe { v128_and(a, b) }
    }
    #[doc = "See [`arch::v128_andnot`]."]
    #[inline(always)]
    pub fn v128_andnot(self, a: v128, b: v128) -> v128 {
        unsafe { v128_andnot(a, b) }
    }
    #[doc = "See [`arch::v128_or`]."]
    #[inline(always)]
    pub fn v128_or(self, a: v128, b: v128) -> v128 {
        unsafe { v128_or(a, b) }
    }
    #[doc = "See [`arch::v128_xor`]."]
    #[inline(always)]
    pub fn v128_xor(self, a: v128, b: v128) -> v128 {
        unsafe { v128_xor(a, b) }
    }
    #[doc = "See [`arch::v128_bitselect`]."]
    #[inline(always)]
    pub fn v128_bitselect(self, v1: v128, v2: v128, c: v128) -> v128 {
        unsafe { v128_bitselect(v1, v2, c) }
    }
    #[doc = "See [`arch::v128_any_true`]."]
    #[inline(always)]
    pub fn v128_any_true(self, a: v128) -> bool {
        unsafe { v128_any_true(a) }
    }
    #[doc = "See [`arch::i8x16_abs`]."]
    #[inline(always)]
    pub fn i8x16_abs(self, a: v128) -> v128 {
        unsafe { i8x16_abs(a) }
    }
    #[doc = "See [`arch::i8x16_neg`]."]
    #[inline(always)]
    pub fn i8x16_neg(self, a: v128) -> v128 {
        unsafe { i8x16_neg(a) }
    }
    #[doc = "See [`arch::i8x16_popcnt`]."]
    #[inline(always)]
    pub fn i8x16_popcnt(self, v: v128) -> v128 {
        unsafe { i8x16_popcnt(v) }
    }
    #[doc = "See [`arch::i8x16_all_true`]."]
    #[inline(always)]
    pub fn i8x16_all_true(self, a: v128) -> bool {
        unsafe { i8x16_all_true(a) }
    }
    #[doc = "See [`arch::i8x16_bitmask`]."]
    #[inline(always)]
    pub fn i8x16_bitmask(self, a: v128) -> u16 {
        unsafe { i8x16_bitmask(a) }
    }
    #[doc = "See [`arch::i8x16_narrow_i16x8`]."]
    #[inline(always)]
    pub fn i8x16_narrow_i16x8(self, a: v128, b: v128) -> v128 {
        unsafe { i8x16_narrow_i16x8(a, b) }
    }
    #[doc = "See [`arch::u8x16_narrow_i16x8`]."]
    #[inline(always)]
    pub fn u8x16_narrow_i16x8(self, a: v128, b: v128) -> v128 {
        unsafe { u8x16_narrow_i16x8(a, b) }
    }
    #[doc = "See [`arch::i8x16_shl`]."]
    #[inline(always)]
    pub fn i8x16_shl(self, a: v128, amt: u32) -> v128 {
        unsafe { i8x16_shl(a, amt) }
    }
    #[doc = "See [`arch::i8x16_shr`]."]
    #[inline(always)]
    pub fn i8x16_shr(self, a: v128, amt: u32) -> v128 {
        unsafe { i8x16_shr(a, amt) }
    }
    #[doc = "See [`arch::u8x16_shr`]."]
    #[inline(always)]
    pub fn u8x16_shr(self, a: v128, amt: u32) -> v128 {
        unsafe { u8x16_shr(a, amt) }
    }
    #[doc = "See [`arch::i8x16_add`]."]
    #[inline(always)]
    pub fn i8x16_add(self, a: v128, b: v128) -> v128 {
        unsafe { i8x16_add(a, b) }
    }
    #[doc = "See [`arch::i8x16_add_sat`]."]
    #[inline(always)]
    pub fn i8x16_add_sat(self, a: v128, b: v128) -> v128 {
        unsafe { i8x16_add_sat(a, b) }
    }
    #[doc = "See [`arch::u8x16_add_sat`]."]
    #[inline(always)]
    pub fn u8x16_add_sat(self, a: v128, b: v128) -> v128 {
        unsafe { u8x16_add_sat(a, b) }
    }
    #[doc = "See [`arch::i8x16_sub`]."]
    #[inline(always)]
    pub fn i8x16_sub(self, a: v128, b: v128) -> v128 {
        unsafe { i8x16_sub(a, b) }
    }
    #[doc = "See [`arch::i8x16_sub_sat`]."]
    #[inline(always)]
    pub fn i8x16_sub_sat(self, a: v128, b: v128) -> v128 {
        unsafe { i8x16_sub_sat(a, b) }
    }
    #[doc = "See [`arch::u8x16_sub_sat`]."]
    #[inline(always)]
    pub fn u8x16_sub_sat(self, a: v128, b: v128) -> v128 {
        unsafe { u8x16_sub_sat(a, b) }
    }
    #[doc = "See [`arch::i8x16_min`]."]
    #[inline(always)]
    pub fn i8x16_min(self, a: v128, b: v128) -> v128 {
        unsafe { i8x16_min(a, b) }
    }
    #[doc = "See [`arch::u8x16_min`]."]
    #[inline(always)]
    pub fn u8x16_min(self, a: v128, b: v128) -> v128 {
        unsafe { u8x16_min(a, b) }
    }
    #[doc = "See [`arch::i8x16_max`]."]
    #[inline(always)]
    pub fn i8x16_max(self, a: v128, b: v128) -> v128 {
        unsafe { i8x16_max(a, b) }
    }
    #[doc = "See [`arch::u8x16_max`]."]
    #[inline(always)]
    pub fn u8x16_max(self, a: v128, b: v128) -> v128 {
        unsafe { u8x16_max(a, b) }
    }
    #[doc = "See [`arch::u8x16_avgr`]."]
    #[inline(always)]
    pub fn u8x16_avgr(self, a: v128, b: v128) -> v128 {
        unsafe { u8x16_avgr(a, b) }
    }
    #[doc = "See [`arch::i16x8_extadd_pairwise_i8x16`]."]
    #[inline(always)]
    pub fn i16x8_extadd_pairwise_i8x16(self, a: v128) -> v128 {
        unsafe { i16x8_extadd_pairwise_i8x16(a) }
    }
    #[doc = "See [`arch::i16x8_extadd_pairwise_u8x16`]."]
    #[inline(always)]
    pub fn i16x8_extadd_pairwise_u8x16(self, a: v128) -> v128 {
        unsafe { i16x8_extadd_pairwise_u8x16(a) }
    }
    #[doc = "See [`arch::i16x8_abs`]."]
    #[inline(always)]
    pub fn i16x8_abs(self, a: v128) -> v128 {
        unsafe { i16x8_abs(a) }
    }
    #[doc = "See [`arch::i16x8_neg`]."]
    #[inline(always)]
    pub fn i16x8_neg(self, a: v128) -> v128 {
        unsafe { i16x8_neg(a) }
    }
    #[doc = "See [`arch::i16x8_q15mulr_sat`]."]
    #[inline(always)]
    pub fn i16x8_q15mulr_sat(self, a: v128, b: v128) -> v128 {
        unsafe { i16x8_q15mulr_sat(a, b) }
    }
    #[doc = "See [`arch::i16x8_all_true`]."]
    #[inline(always)]
    pub fn i16x8_all_true(self, a: v128) -> bool {
        unsafe { i16x8_all_true(a) }
    }
    #[doc = "See [`arch::i16x8_bitmask`]."]
    #[inline(always)]
    pub fn i16x8_bitmask(self, a: v128) -> u8 {
        unsafe { i16x8_bitmask(a) }
    }
    #[doc = "See [`arch::i16x8_narrow_i32x4`]."]
    #[inline(always)]
    pub fn i16x8_narrow_i32x4(self, a: v128, b: v128) -> v128 {
        unsafe { i16x8_narrow_i32x4(a, b) }
    }
    #[doc = "See [`arch::u16x8_narrow_i32x4`]."]
    #[inline(always)]
    pub fn u16x8_narrow_i32x4(self, a: v128, b: v128) -> v128 {
        unsafe { u16x8_narrow_i32x4(a, b) }
    }
    #[doc = "See [`arch::i16x8_extend_low_i8x16`]."]
    #[inline(always)]
    pub fn i16x8_extend_low_i8x16(self, a: v128) -> v128 {
        unsafe { i16x8_extend_low_i8x16(a) }
    }
    #[doc = "See [`arch::i16x8_extend_high_i8x16`]."]
    #[inline(always)]
    pub fn i16x8_extend_high_i8x16(self, a: v128) -> v128 {
        unsafe { i16x8_extend_high_i8x16(a) }
    }
    #[doc = "See [`arch::i16x8_extend_low_u8x16`]."]
    #[inline(always)]
    pub fn i16x8_extend_low_u8x16(self, a: v128) -> v128 {
        unsafe { i16x8_extend_low_u8x16(a) }
    }
    #[doc = "See [`arch::i16x8_extend_high_u8x16`]."]
    #[inline(always)]
    pub fn i16x8_extend_high_u8x16(self, a: v128) -> v128 {
        unsafe { i16x8_extend_high_u8x16(a) }
    }
    #[doc = "See [`arch::i16x8_shl`]."]
    #[inline(always)]
    pub fn i16x8_shl(self, a: v128, amt: u32) -> v128 {
        unsafe { i16x8_shl(a, amt) }
    }
    #[doc = "See [`arch::i16x8_shr`]."]
    #[inline(always)]
    pub fn i16x8_shr(self, a: v128, amt: u32) -> v128 {
        unsafe { i16x8_shr(a, amt) }
    }
    #[doc = "See [`arch::u16x8_shr`]."]
    #[inline(always)]
    pub fn u16x8_shr(self, a: v128, amt: u32) -> v128 {
        unsafe { u16x8_shr(a, amt) }
    }
    #[doc = "See [`arch::i16x8_add`]."]
    #[inline(always)]
    pub fn i16x8_add(self, a: v128, b: v128) -> v128 {
        unsafe { i16x8_add(a, b) }
    }
    #[doc = "See [`arch::i16x8_add_sat`]."]
    #[inline(always)]
    pub fn i16x8_add_sat(self, a: v128, b: v128) -> v128 {
        unsafe { i16x8_add_sat(a, b) }
    }
    #[doc = "See [`arch::u16x8_add_sat`]."]
    #[inline(always)]
    pub fn u16x8_add_sat(self, a: v128, b: v128) -> v128 {
        unsafe { u16x8_add_sat(a, b) }
    }
    #[doc = "See [`arch::i16x8_sub`]."]
    #[inline(always)]
    pub fn i16x8_sub(self, a: v128, b: v128) -> v128 {
        unsafe { i16x8_sub(a, b) }
    }
    #[doc = "See [`arch::i16x8_sub_sat`]."]
    #[inline(always)]
    pub fn i16x8_sub_sat(self, a: v128, b: v128) -> v128 {
        unsafe { i16x8_sub_sat(a, b) }
    }
    #[doc = "See [`arch::u16x8_sub_sat`]."]
    #[inline(always)]
    pub fn u16x8_sub_sat(self, a: v128, b: v128) -> v128 {
        unsafe { u16x8_sub_sat(a, b) }
    }
    #[doc = "See [`arch::i16x8_mul`]."]
    #[inline(always)]
    pub fn i16x8_mul(self, a: v128, b: v128) -> v128 {
        unsafe { i16x8_mul(a, b) }
    }
    #[doc = "See [`arch::i16x8_min`]."]
    #[inline(always)]
    pub fn i16x8_min(self, a: v128, b: v128) -> v128 {
        unsafe { i16x8_min(a, b) }
    }
    #[doc = "See [`arch::u16x8_min`]."]
    #[inline(always)]
    pub fn u16x8_min(self, a: v128, b: v128) -> v128 {
        unsafe { u16x8_min(a, b) }
    }
    #[doc = "See [`arch::i16x8_max`]."]
    #[inline(always)]
    pub fn i16x8_max(self, a: v128, b: v128) -> v128 {
        unsafe { i16x8_max(a, b) }
    }
    #[doc = "See [`arch::u16x8_max`]."]
    #[inline(always)]
    pub fn u16x8_max(self, a: v128, b: v128) -> v128 {
        unsafe { u16x8_max(a, b) }
    }
    #[doc = "See [`arch::u16x8_avgr`]."]
    #[inline(always)]
    pub fn u16x8_avgr(self, a: v128, b: v128) -> v128 {
        unsafe { u16x8_avgr(a, b) }
    }
    #[doc = "See [`arch::i16x8_extmul_low_i8x16`]."]
    #[inline(always)]
    pub fn i16x8_extmul_low_i8x16(self, a: v128, b: v128) -> v128 {
        unsafe { i16x8_extmul_low_i8x16(a, b) }
    }
    #[doc = "See [`arch::i16x8_extmul_high_i8x16`]."]
    #[inline(always)]
    pub fn i16x8_extmul_high_i8x16(self, a: v128, b: v128) -> v128 {
        unsafe { i16x8_extmul_high_i8x16(a, b) }
    }
    #[doc = "See [`arch::i16x8_extmul_low_u8x16`]."]
    #[inline(always)]
    pub fn i16x8_extmul_low_u8x16(self, a: v128, b: v128) -> v128 {
        unsafe { i16x8_extmul_low_u8x16(a, b) }
    }
    #[doc = "See [`arch::i16x8_extmul_high_u8x16`]."]
    #[inline(always)]
    pub fn i16x8_extmul_high_u8x16(self, a: v128, b: v128) -> v128 {
        unsafe { i16x8_extmul_high_u8x16(a, b) }
    }
    #[doc = "See [`arch::i32x4_extadd_pairwise_i16x8`]."]
    #[inline(always)]
    pub fn i32x4_extadd_pairwise_i16x8(self, a: v128) -> v128 {
        unsafe { i32x4_extadd_pairwise_i16x8(a) }
    }
    #[doc = "See [`arch::i32x4_extadd_pairwise_u16x8`]."]
    #[inline(always)]
    pub fn i32x4_extadd_pairwise_u16x8(self, a: v128) -> v128 {
        unsafe { i32x4_extadd_pairwise_u16x8(a) }
    }
    #[doc = "See [`arch::i32x4_abs`]."]
    #[inline(always)]
    pub fn i32x4_abs(self, a: v128) -> v128 {
        unsafe { i32x4_abs(a) }
    }
    #[doc = "See [`arch::i32x4_neg`]."]
    #[inline(always)]
    pub fn i32x4_neg(self, a: v128) -> v128 {
        unsafe { i32x4_neg(a) }
    }
    #[doc = "See [`arch::i32x4_all_true`]."]
    #[inline(always)]
    pub fn i32x4_all_true(self, a: v128) -> bool {
        unsafe { i32x4_all_true(a) }
    }
    #[doc = "See [`arch::i32x4_bitmask`]."]
    #[inline(always)]
    pub fn i32x4_bitmask(self, a: v128) -> u8 {
        unsafe { i32x4_bitmask(a) }
    }
    #[doc = "See [`arch::i32x4_extend_low_i16x8`]."]
    #[inline(always)]
    pub fn i32x4_extend_low_i16x8(self, a: v128) -> v128 {
        unsafe { i32x4_extend_low_i16x8(a) }
    }
    #[doc = "See [`arch::i32x4_extend_high_i16x8`]."]
    #[inline(always)]
    pub fn i32x4_extend_high_i16x8(self, a: v128) -> v128 {
        unsafe { i32x4_extend_high_i16x8(a) }
    }
    #[doc = "See [`arch::i32x4_extend_low_u16x8`]."]
    #[inline(always)]
    pub fn i32x4_extend_low_u16x8(self, a: v128) -> v128 {
        unsafe { i32x4_extend_low_u16x8(a) }
    }
    #[doc = "See [`arch::i32x4_extend_high_u16x8`]."]
    #[inline(always)]
    pub fn i32x4_extend_high_u16x8(self, a: v128) -> v128 {
        unsafe { i32x4_extend_high_u16x8(a) }
    }
    #[doc = "See [`arch::i32x4_shl`]."]
    #[inline(always)]
    pub fn i32x4_shl(self, a: v128, amt: u32) -> v128 {
        unsafe { i32x4_shl(a, amt) }
    }
    #[doc = "See [`arch::i32x4_shr`]."]
    #[inline(always)]
    pub fn i32x4_shr(self, a: v128, amt: u32) -> v128 {
        unsafe { i32x4_shr(a, amt) }
    }
    #[doc = "See [`arch::u32x4_shr`]."]
    #[inline(always)]
    pub fn u32x4_shr(self, a: v128, amt: u32) -> v128 {
        unsafe { u32x4_shr(a, amt) }
    }
    #[doc = "See [`arch::i32x4_add`]."]
    #[inline(always)]
    pub fn i32x4_add(self, a: v128, b: v128) -> v128 {
        unsafe { i32x4_add(a, b) }
    }
    #[doc = "See [`arch::i32x4_sub`]."]
    #[inline(always)]
    pub fn i32x4_sub(self, a: v128, b: v128) -> v128 {
        unsafe { i32x4_sub(a, b) }
    }
    #[doc = "See [`arch::i32x4_mul`]."]
    #[inline(always)]
    pub fn i32x4_mul(self, a: v128, b: v128) -> v128 {
        unsafe { i32x4_mul(a, b) }
    }
    #[doc = "See [`arch::i32x4_min`]."]
    #[inline(always)]
    pub fn i32x4_min(self, a: v128, b: v128) -> v128 {
        unsafe { i32x4_min(a, b) }
    }
    #[doc = "See [`arch::u32x4_min`]."]
    #[inline(always)]
    pub fn u32x4_min(self, a: v128, b: v128) -> v128 {
        unsafe { u32x4_min(a, b) }
    }
    #[doc = "See [`arch::i32x4_max`]."]
    #[inline(always)]
    pub fn i32x4_max(self, a: v128, b: v128) -> v128 {
        unsafe { i32x4_max(a, b) }
    }
    #[doc = "See [`arch::u32x4_max`]."]
    #[inline(always)]
    pub fn u32x4_max(self, a: v128, b: v128) -> v128 {
        unsafe { u32x4_max(a, b) }
    }
    #[doc = "See [`arch::i32x4_dot_i16x8`]."]
    #[inline(always)]
    pub fn i32x4_dot_i16x8(self, a: v128, b: v128) -> v128 {
        unsafe { i32x4_dot_i16x8(a, b) }
    }
    #[doc = "See [`arch::i32x4_extmul_low_i16x8`]."]
    #[inline(always)]
    pub fn i32x4_extmul_low_i16x8(self, a: v128, b: v128) -> v128 {
        unsafe { i32x4_extmul_low_i16x8(a, b) }
    }
    #[doc = "See [`arch::i32x4_extmul_high_i16x8`]."]
    #[inline(always)]
    pub fn i32x4_extmul_high_i16x8(self, a: v128, b: v128) -> v128 {
        unsafe { i32x4_extmul_high_i16x8(a, b) }
    }
    #[doc = "See [`arch::i32x4_extmul_low_u16x8`]."]
    #[inline(always)]
    pub fn i32x4_extmul_low_u16x8(self, a: v128, b: v128) -> v128 {
        unsafe { i32x4_extmul_low_u16x8(a, b) }
    }
    #[doc = "See [`arch::i32x4_extmul_high_u16x8`]."]
    #[inline(always)]
    pub fn i32x4_extmul_high_u16x8(self, a: v128, b: v128) -> v128 {
        unsafe { i32x4_extmul_high_u16x8(a, b) }
    }
    #[doc = "See [`arch::i64x2_abs`]."]
    #[inline(always)]
    pub fn i64x2_abs(self, a: v128) -> v128 {
        unsafe { i64x2_abs(a) }
    }
    #[doc = "See [`arch::i64x2_neg`]."]
    #[inline(always)]
    pub fn i64x2_neg(self, a: v128) -> v128 {
        unsafe { i64x2_neg(a) }
    }
    #[doc = "See [`arch::i64x2_all_true`]."]
    #[inline(always)]
    pub fn i64x2_all_true(self, a: v128) -> bool {
        unsafe { i64x2_all_true(a) }
    }
    #[doc = "See [`arch::i64x2_bitmask`]."]
    #[inline(always)]
    pub fn i64x2_bitmask(self, a: v128) -> u8 {
        unsafe { i64x2_bitmask(a) }
    }
    #[doc = "See [`arch::i64x2_extend_low_i32x4`]."]
    #[inline(always)]
    pub fn i64x2_extend_low_i32x4(self, a: v128) -> v128 {
        unsafe { i64x2_extend_low_i32x4(a) }
    }
    #[doc = "See [`arch::i64x2_extend_high_i32x4`]."]
    #[inline(always)]
    pub fn i64x2_extend_high_i32x4(self, a: v128) -> v128 {
        unsafe { i64x2_extend_high_i32x4(a) }
    }
    #[doc = "See [`arch::i64x2_extend_low_u32x4`]."]
    #[inline(always)]
    pub fn i64x2_extend_low_u32x4(self, a: v128) -> v128 {
        unsafe { i64x2_extend_low_u32x4(a) }
    }
    #[doc = "See [`arch::i64x2_extend_high_u32x4`]."]
    #[inline(always)]
    pub fn i64x2_extend_high_u32x4(self, a: v128) -> v128 {
        unsafe { i64x2_extend_high_u32x4(a) }
    }
    #[doc = "See [`arch::i64x2_shl`]."]
    #[inline(always)]
    pub fn i64x2_shl(self, a: v128, amt: u32) -> v128 {
        unsafe { i64x2_shl(a, amt) }
    }
    #[doc = "See [`arch::i64x2_shr`]."]
    #[inline(always)]
    pub fn i64x2_shr(self, a: v128, amt: u32) -> v128 {
        unsafe { i64x2_shr(a, amt) }
    }
    #[doc = "See [`arch::u64x2_shr`]."]
    #[inline(always)]
    pub fn u64x2_shr(self, a: v128, amt: u32) -> v128 {
        unsafe { u64x2_shr(a, amt) }
    }
    #[doc = "See [`arch::i64x2_add`]."]
    #[inline(always)]
    pub fn i64x2_add(self, a: v128, b: v128) -> v128 {
        unsafe { i64x2_add(a, b) }
    }
    #[doc = "See [`arch::i64x2_sub`]."]
    #[inline(always)]
    pub fn i64x2_sub(self, a: v128, b: v128) -> v128 {
        unsafe { i64x2_sub(a, b) }
    }
    #[doc = "See [`arch::i64x2_mul`]."]
    #[inline(always)]
    pub fn i64x2_mul(self, a: v128, b: v128) -> v128 {
        unsafe { i64x2_mul(a, b) }
    }
    #[doc = "See [`arch::i64x2_extmul_low_i32x4`]."]
    #[inline(always)]
    pub fn i64x2_extmul_low_i32x4(self, a: v128, b: v128) -> v128 {
        unsafe { i64x2_extmul_low_i32x4(a, b) }
    }
    #[doc = "See [`arch::i64x2_extmul_high_i32x4`]."]
    #[inline(always)]
    pub fn i64x2_extmul_high_i32x4(self, a: v128, b: v128) -> v128 {
        unsafe { i64x2_extmul_high_i32x4(a, b) }
    }
    #[doc = "See [`arch::i64x2_extmul_low_u32x4`]."]
    #[inline(always)]
    pub fn i64x2_extmul_low_u32x4(self, a: v128, b: v128) -> v128 {
        unsafe { i64x2_extmul_low_u32x4(a, b) }
    }
    #[doc = "See [`arch::i64x2_extmul_high_u32x4`]."]
    #[inline(always)]
    pub fn i64x2_extmul_high_u32x4(self, a: v128, b: v128) -> v128 {
        unsafe { i64x2_extmul_high_u32x4(a, b) }
    }
    #[doc = "See [`arch::f32x4_ceil`]."]
    #[inline(always)]
    pub fn f32x4_ceil(self, a: v128) -> v128 {
        unsafe { f32x4_ceil(a) }
    }
    #[doc = "See [`arch::f32x4_floor`]."]
    #[inline(always)]
    pub fn f32x4_floor(self, a: v128) -> v128 {
        unsafe { f32x4_floor(a) }
    }
    #[doc = "See [`arch::f32x4_trunc`]."]
    #[inline(always)]
    pub fn f32x4_trunc(self, a: v128) -> v128 {
        unsafe { f32x4_trunc(a) }
    }
    #[doc = "See [`arch::f32x4_nearest`]."]
    #[inline(always)]
    pub fn f32x4_nearest(self, a: v128) -> v128 {
        unsafe { f32x4_nearest(a) }
    }
    #[doc = "See [`arch::f32x4_abs`]."]
    #[inline(always)]
    pub fn f32x4_abs(self, a: v128) -> v128 {
        unsafe { f32x4_abs(a) }
    }
    #[doc = "See [`arch::f32x4_neg`]."]
    #[inline(always)]
    pub fn f32x4_neg(self, a: v128) -> v128 {
        unsafe { f32x4_neg(a) }
    }
    #[doc = "See [`arch::f32x4_sqrt`]."]
    #[inline(always)]
    pub fn f32x4_sqrt(self, a: v128) -> v128 {
        unsafe { f32x4_sqrt(a) }
    }
    #[doc = "See [`arch::f32x4_add`]."]
    #[inline(always)]
    pub fn f32x4_add(self, a: v128, b: v128) -> v128 {
        unsafe { f32x4_add(a, b) }
    }
    #[doc = "See [`arch::f32x4_sub`]."]
    #[inline(always)]
    pub fn f32x4_sub(self, a: v128, b: v128) -> v128 {
        unsafe { f32x4_sub(a, b) }
    }
    #[doc = "See [`arch::f32x4_mul`]."]
    #[inline(always)]
    pub fn f32x4_mul(self, a: v128, b: v128) -> v128 {
        unsafe { f32x4_mul(a, b) }
    }
    #[doc = "See [`arch::f32x4_div`]."]
    #[inline(always)]
    pub fn f32x4_div(self, a: v128, b: v128) -> v128 {
        unsafe { f32x4_div(a, b) }
    }
    #[doc = "See [`arch::f32x4_min`]."]
    #[inline(always)]
    pub fn f32x4_min(self, a: v128, b: v128) -> v128 {
        unsafe { f32x4_min(a, b) }
    }
    #[doc = "See [`arch::f32x4_max`]."]
    #[inline(always)]
    pub fn f32x4_max(self, a: v128, b: v128) -> v128 {
        unsafe { f32x4_max(a, b) }
    }
    #[doc = "See [`arch::f32x4_pmin`]."]
    #[inline(always)]
    pub fn f32x4_pmin(self, a: v128, b: v128) -> v128 {
        unsafe { f32x4_pmin(a, b) }
    }
    #[doc = "See [`arch::f32x4_pmax`]."]
    #[inline(always)]
    pub fn f32x4_pmax(self, a: v128, b: v128) -> v128 {
        unsafe { f32x4_pmax(a, b) }
    }
    #[doc = "See [`arch::f64x2_ceil`]."]
    #[inline(always)]
    pub fn f64x2_ceil(self, a: v128) -> v128 {
        unsafe { f64x2_ceil(a) }
    }
    #[doc = "See [`arch::f64x2_floor`]."]
    #[inline(always)]
    pub fn f64x2_floor(self, a: v128) -> v128 {
        unsafe { f64x2_floor(a) }
    }
    #[doc = "See [`arch::f64x2_trunc`]."]
    #[inline(always)]
    pub fn f64x2_trunc(self, a: v128) -> v128 {
        unsafe { f64x2_trunc(a) }
    }
    #[doc = "See [`arch::f64x2_nearest`]."]
    #[inline(always)]
    pub fn f64x2_nearest(self, a: v128) -> v128 {
        unsafe { f64x2_nearest(a) }
    }
    #[doc = "See [`arch::f64x2_abs`]."]
    #[inline(always)]
    pub fn f64x2_abs(self, a: v128) -> v128 {
        unsafe { f64x2_abs(a) }
    }
    #[doc = "See [`arch::f64x2_neg`]."]
    #[inline(always)]
    pub fn f64x2_neg(self, a: v128) -> v128 {
        unsafe { f64x2_neg(a) }
    }
    #[doc = "See [`arch::f64x2_sqrt`]."]
    #[inline(always)]
    pub fn f64x2_sqrt(self, a: v128) -> v128 {
        unsafe { f64x2_sqrt(a) }
    }
    #[doc = "See [`arch::f64x2_add`]."]
    #[inline(always)]
    pub fn f64x2_add(self, a: v128, b: v128) -> v128 {
        unsafe { f64x2_add(a, b) }
    }
    #[doc = "See [`arch::f64x2_sub`]."]
    #[inline(always)]
    pub fn f64x2_sub(self, a: v128, b: v128) -> v128 {
        unsafe { f64x2_sub(a, b) }
    }
    #[doc = "See [`arch::f64x2_mul`]."]
    #[inline(always)]
    pub fn f64x2_mul(self, a: v128, b: v128) -> v128 {
        unsafe { f64x2_mul(a, b) }
    }
    #[doc = "See [`arch::f64x2_div`]."]
    #[inline(always)]
    pub fn f64x2_div(self, a: v128, b: v128) -> v128 {
        unsafe { f64x2_div(a, b) }
    }
    #[doc = "See [`arch::f64x2_min`]."]
    #[inline(always)]
    pub fn f64x2_min(self, a: v128, b: v128) -> v128 {
        unsafe { f64x2_min(a, b) }
    }
    #[doc = "See [`arch::f64x2_max`]."]
    #[inline(always)]
    pub fn f64x2_max(self, a: v128, b: v128) -> v128 {
        unsafe { f64x2_max(a, b) }
    }
    #[doc = "See [`arch::f64x2_pmin`]."]
    #[inline(always)]
    pub fn f64x2_pmin(self, a: v128, b: v128) -> v128 {
        unsafe { f64x2_pmin(a, b) }
    }
    #[doc = "See [`arch::f64x2_pmax`]."]
    #[inline(always)]
    pub fn f64x2_pmax(self, a: v128, b: v128) -> v128 {
        unsafe { f64x2_pmax(a, b) }
    }
    #[doc = "See [`arch::i32x4_trunc_sat_f32x4`]."]
    #[inline(always)]
    pub fn i32x4_trunc_sat_f32x4(self, a: v128) -> v128 {
        unsafe { i32x4_trunc_sat_f32x4(a) }
    }
    #[doc = "See [`arch::u32x4_trunc_sat_f32x4`]."]
    #[inline(always)]
    pub fn u32x4_trunc_sat_f32x4(self, a: v128) -> v128 {
        unsafe { u32x4_trunc_sat_f32x4(a) }
    }
    #[doc = "See [`arch::f32x4_convert_i32x4`]."]
    #[inline(always)]
    pub fn f32x4_convert_i32x4(self, a: v128) -> v128 {
        unsafe { f32x4_convert_i32x4(a) }
    }
    #[doc = "See [`arch::f32x4_convert_u32x4`]."]
    #[inline(always)]
    pub fn f32x4_convert_u32x4(self, a: v128) -> v128 {
        unsafe { f32x4_convert_u32x4(a) }
    }
    #[doc = "See [`arch::i32x4_trunc_sat_f64x2_zero`]."]
    #[inline(always)]
    pub fn i32x4_trunc_sat_f64x2_zero(self, a: v128) -> v128 {
        unsafe { i32x4_trunc_sat_f64x2_zero(a) }
    }
    #[doc = "See [`arch::u32x4_trunc_sat_f64x2_zero`]."]
    #[inline(always)]
    pub fn u32x4_trunc_sat_f64x2_zero(self, a: v128) -> v128 {
        unsafe { u32x4_trunc_sat_f64x2_zero(a) }
    }
    #[doc = "See [`arch::f64x2_convert_low_i32x4`]."]
    #[inline(always)]
    pub fn f64x2_convert_low_i32x4(self, a: v128) -> v128 {
        unsafe { f64x2_convert_low_i32x4(a) }
    }
    #[doc = "See [`arch::f64x2_convert_low_u32x4`]."]
    #[inline(always)]
    pub fn f64x2_convert_low_u32x4(self, a: v128) -> v128 {
        unsafe { f64x2_convert_low_u32x4(a) }
    }
    #[doc = "See [`arch::f32x4_demote_f64x2_zero`]."]
    #[inline(always)]
    pub fn f32x4_demote_f64x2_zero(self, a: v128) -> v128 {
        unsafe { f32x4_demote_f64x2_zero(a) }
    }
    #[doc = "See [`arch::f64x2_promote_low_f32x4`]."]
    #[inline(always)]
    pub fn f64x2_promote_low_f32x4(self, a: v128) -> v128 {
        unsafe { f64x2_promote_low_f32x4(a) }
    }
}
