// This file is automatically generated by `fearless_simd_core_gen`.
// Its template can be found in `fearless_simd_core/gen/templates`.

//! The x86-64-v2 microarchitecture level.

use crate::{TargetFeatureToken, trampoline};

use core::fmt::Debug;

// TODO: Level specific docs?
/// A token indicating that the current CPU has the x86-64-v2 microarchitecture level.
///
/// For more details on the microarchitecture levels, see
/// <https://en.wikipedia.org/wiki/X86-64#Microarchitecture_levels>.
///
/// # Example
///
/// This can be used to [`trampoline!`] into functions like:
///
/// ```rust
/// #[cfg(any(target_arch = "x86", target_arch = "x86_64"))]
/// #[target_feature(enable = "cmpxchg16b,fxsr,popcnt,sse4.2")]
/// fn uses_x86_64_v2() {
///     // ...
/// }
/// ```
///
/// This struct internally contains only the minimal features required to enable this level.
/// This is done to ensure that the fewest target features are checked.
/// However, it can be turned into any target feature it implies using the from impls.
#[derive(Copy, Clone, Hash, PartialEq, Eq)]
pub struct V2 {
    /// The contained proof that `cmpxchg16b` is available.
    pub cmpxchg16b: crate::x86::v2::Cmpxchg16b,
    /// The contained proof that `fxsave + fxrstor` is available.
    pub fxsr: crate::x86::v2::Fxsr,
    /// The contained proof that `popcnt` is available.
    pub popcnt: crate::x86::v2::Popcnt,
    /// The contained proof that SSE4.2 is available.
    pub sse4_2: crate::x86::v2::Sse4_2,
    // This struct explicitly is not non_exhaustive, because it is
    // completely safe to construct from the fields.
}

impl Debug for V2 {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, r#"x86-64-v2 enabled."#)
    }
}

// Safety: This token can only be constructed if you have proofs that all the requisite
// target features are enabled.
unsafe impl TargetFeatureToken for V2 {
    const FEATURES: &[&str] = &[
        "cmpxchg16b",
        "fxsr",
        "popcnt",
        "sse",
        "sse2",
        "sse3",
        "sse4.1",
        "sse4.2",
        "ssse3",
    ];

    #[inline(always)]
    fn vectorize<R>(self, f: impl FnOnce() -> R) -> R {
        // We use the explicitly written out form here as validation that the set of
        // features we've created correctly mapes to the target feature string.
        trampoline!([crate::x86::v2::Cmpxchg16b = self.cmpxchg16b, crate::x86::v2::Fxsr = self.fxsr, crate::x86::v2::Popcnt = self.popcnt, crate::x86::v2::Sse4_2 = self.sse4_2] => "cmpxchg16b,fxsr,popcnt,sse4.2", <(R)> fn<(R)>(f: impl FnOnce() -> R = f) -> R { f() })
    }
}

impl V2 {
    #[cfg(feature = "std")]
    /// Create a new token if the x86-64-v2 target feature is detected as enabled.
    ///
    /// This does not do any caching internally, although note that the standard
    /// library does internally cache the features it detects.
    // TODO: Consider a manual override feature/env var?
    pub fn try_new() -> Option<Self> {
        Some(Self {
            cmpxchg16b: crate::x86::v2::Cmpxchg16b::try_new()?,
            fxsr: crate::x86::v2::Fxsr::try_new()?,
            popcnt: crate::x86::v2::Popcnt::try_new()?,
            sse4_2: crate::x86::v2::Sse4_2::try_new()?,
        })
    }

    #[target_feature(enable = "cmpxchg16b,fxsr,popcnt,sse4.2")]
    /// Create a new token for the x86-64-v2 microarchitecture level.
    ///
    /// This method is useful to get a new token if you have an external proof that
    /// x86-64-v2 is available. This could happen if you are in a target feature
    /// function called by an external library user.
    ///
    /// # Safety
    ///
    /// No conditions other than those inherited from the target feature attribute,
    /// i.e. that the "cmpxchg16b,fxsr,popcnt,sse4.2" target feature is available.
    pub fn new() -> Self {
        Self {
            cmpxchg16b: crate::x86::v2::Cmpxchg16b::new(),
            fxsr: crate::x86::v2::Fxsr::new(),
            popcnt: crate::x86::v2::Popcnt::new(),
            sse4_2: crate::x86::v2::Sse4_2::new(),
        }
    }
}
// TODO: From impls to convert into lower x86 versions.

impl From<V2> for crate::x86::v2::Cmpxchg16b {
    fn from(value: V2) -> Self {
        // This serves as a correctness check of the implicitly enabled features.
        trampoline!([V2 = value] => "cmpxchg16b,fxsr,popcnt,sse4.2", fn() -> crate::x86::v2::Cmpxchg16b { crate::x86::v2::Cmpxchg16b::new() })
    }
}

impl From<V2> for crate::x86::v2::Fxsr {
    fn from(value: V2) -> Self {
        // This serves as a correctness check of the implicitly enabled features.
        trampoline!([V2 = value] => "cmpxchg16b,fxsr,popcnt,sse4.2", fn() -> crate::x86::v2::Fxsr { crate::x86::v2::Fxsr::new() })
    }
}

impl From<V2> for crate::x86::v2::Popcnt {
    fn from(value: V2) -> Self {
        // This serves as a correctness check of the implicitly enabled features.
        trampoline!([V2 = value] => "cmpxchg16b,fxsr,popcnt,sse4.2", fn() -> crate::x86::v2::Popcnt { crate::x86::v2::Popcnt::new() })
    }
}

impl From<V2> for crate::x86::v2::Sse {
    fn from(value: V2) -> Self {
        // This serves as a correctness check of the implicitly enabled features.
        trampoline!([V2 = value] => "cmpxchg16b,fxsr,popcnt,sse4.2", fn() -> crate::x86::v2::Sse { crate::x86::v2::Sse::new() })
    }
}

impl From<V2> for crate::x86::v2::Sse2 {
    fn from(value: V2) -> Self {
        // This serves as a correctness check of the implicitly enabled features.
        trampoline!([V2 = value] => "cmpxchg16b,fxsr,popcnt,sse4.2", fn() -> crate::x86::v2::Sse2 { crate::x86::v2::Sse2::new() })
    }
}

impl From<V2> for crate::x86::v2::Sse3 {
    fn from(value: V2) -> Self {
        // This serves as a correctness check of the implicitly enabled features.
        trampoline!([V2 = value] => "cmpxchg16b,fxsr,popcnt,sse4.2", fn() -> crate::x86::v2::Sse3 { crate::x86::v2::Sse3::new() })
    }
}

impl From<V2> for crate::x86::v2::Sse4_1 {
    fn from(value: V2) -> Self {
        // This serves as a correctness check of the implicitly enabled features.
        trampoline!([V2 = value] => "cmpxchg16b,fxsr,popcnt,sse4.2", fn() -> crate::x86::v2::Sse4_1 { crate::x86::v2::Sse4_1::new() })
    }
}

impl From<V2> for crate::x86::v2::Sse4_2 {
    fn from(value: V2) -> Self {
        // This serves as a correctness check of the implicitly enabled features.
        trampoline!([V2 = value] => "cmpxchg16b,fxsr,popcnt,sse4.2", fn() -> crate::x86::v2::Sse4_2 { crate::x86::v2::Sse4_2::new() })
    }
}

impl From<V2> for crate::x86::v2::SupplementalSse3 {
    fn from(value: V2) -> Self {
        // This serves as a correctness check of the implicitly enabled features.
        trampoline!([V2 = value] => "cmpxchg16b,fxsr,popcnt,sse4.2", fn() -> crate::x86::v2::SupplementalSse3 { crate::x86::v2::SupplementalSse3::new() })
    }
}

const _: () = {
    assert!(
        core::mem::size_of::<V2>() == 0,
        "Target feature tokens should be zero sized."
    );
};
