use proc_macro2::TokenStream;
use std::io::Write as _;

pub(crate) fn write_code(code: TokenStream, out: impl Into<std::process::Stdio>) {
    let mut child = std::process::Command::new("rustfmt")
        .stdin(std::process::Stdio::piped())
        .stdout(out)
        .spawn()
        .expect("`rustfmt` should spawn");
    let mut stdin = child.stdin.take().unwrap();
    stdin
        .write_all(
            format!(
                r#"
// Copyright 2026 the Fearless_SIMD Authors
// SPDX-License-Identifier: Apache-2.0 OR MIT

// This file is autogenerated by fearless_simd_gen

{code}"#
            )
            .as_bytes(),
        )
        .unwrap();
    drop(stdin);
    child.wait().expect("`rustfmt` should succeed");
}
