// This file is automatically generated by `fearless_simd_core_gen`.
// Its template can be found in `fearless_simd_core/gen/templates`.

//! The `xsavec` target feature.

use crate::{TargetFeatureToken, trampoline};

use core::fmt::Debug;

/// ["xsavec"] --- Save processor extended states with compaction
///
/// ["xsavec"]: https://www.felixcloutier.com/x86/xsavec
///
/// A token indicating that the current CPU has the `xsavec` target feature.
///
/// # Example
///
/// This can be used to [`trampoline!`] into functions like:
///
/// ```rust
/// #[cfg(any(target_arch = "x86", target_arch = "x86_64"))]
/// #[target_feature(enable = "xsavec")]
/// fn uses_xsavec() {
///     // ...
/// }
/// ```
#[derive(Copy, Clone, Hash, PartialEq, Eq)]
pub struct Xsavec {
    // We don't use non_exhaustive because we don't want this struct to be constructible.
    // in different modules in this crate.
    _private: (),
}

impl Debug for Xsavec {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, r#""xsavec" enabled."#)
    }
}

unsafe impl TargetFeatureToken for Xsavec {
    const FEATURES: &[&str] = &["xsavec", ];

    #[inline(always)]
    fn vectorize<R>(self, f: impl FnOnce() -> R) -> R {
        // Because we want this constant to be eagerly evaluated.
        trampoline!([Xsavec = self] => "xsavec", <(R)> fn<(R)>(f: impl FnOnce() -> R = f) -> R { f() })
    }
}

impl Xsavec {
    #[cfg(feature = "std")]
    /// Create a new token if the `"xsavec"` target feature is detected as enabled.
    ///
    /// This does not do any caching internally, although note that the standard
    /// library does internally cache the features it detects.
    // TODO: Consider a manual override feature/env var?
    pub fn try_new() -> Option<Self> {
        // Feature flag required to make docs compile.
        // TODO: Extract into a (private) crate::x86::is_x86_feature_detected?
        #[cfg(any(target_arch = "x86", target_arch = "x86_64"))]
        if std::arch::is_x86_feature_detected!("xsavec") {
            // Safety: The required CPU feature was detected.
            unsafe { Some(Self::new()) }
        } else {
            None
        }
    }

    #[target_feature(enable = "xsavec")]
    /// Create a new token for the "xsavec" target feature.
    ///
    /// This method is useful to get a new token if you have an external proof that
    /// `xsavec` is available. This could happen if you are in a target feature
    /// function called by an external library user.
    ///
    /// # Safety
    ///
    /// No conditions other than those inherited from the target feature attribute,
    /// i.e. that the "xsavec" target feature is available.
    ///
    /// [implicitly enables]: https://doc.rust-lang.org/beta/reference/attributes/codegen.html?highlight=implicitly%20enabled#r-attributes.codegen.target_feature.safety-restrictions
    pub fn new() -> Self {
        Self { _private: () }
    }
}


const _: () = {
    assert!(
        core::mem::size_of::<Xsavec>() == 0,
        "Target feature tokens should be zero sized."
    );
};
