// Copyright 2025 the Fearless_SIMD Authors
// SPDX-License-Identifier: Apache-2.0 OR MIT

#![expect(
    missing_docs,
    clippy::unnecessary_cast,
    clippy::cast_possible_truncation,
    clippy::unseparated_literal_suffix,
    clippy::use_self,
    clippy::wrong_self_convention,
    reason = "Simplifies the generator and has no effect on the machine code"
)]
#![allow(
    trivial_numeric_casts,
    reason = "Not every conditionally compiled backend contains a trivial cast"
)]
#![cfg_attr(
    all(
        target_arch = "x86_64",
        any(
            not(all(target_feature = "sse2", target_feature = "fxsr")),
            feature = "force_support_fallback"
        )
    ),
    expect(
        clippy::new_without_default,
        reason = "TODO: https://github.com/linebender/fearless_simd/issues/40"
    )
)]
#![cfg_attr(
    target_arch = "wasm32",
    expect(
        clippy::new_without_default,
        reason = "TODO: https://github.com/linebender/fearless_simd/issues/40"
    )
)]
#![cfg_attr(
    all(
        feature = "std",
        all(not(target_arch = "x86_64"), not(target_arch = "wasm32"))
    ),
    expect(
        clippy::new_without_default,
        reason = "TODO: https://github.com/linebender/fearless_simd/issues/40"
    )
)]

//! A module containing generated files
//!
//! All files in this subdirectory are autogenerated by the `fearless_simd_gen` crate.

// Fallback is unnecessary exactly when one of our SIMD backends is guaranteed as the baseline.
// Keep this predicate in sync with `Level::Fallback` and `dispatch!`.
macro_rules! with_fallback {
    ($($item:item)*) => {$(
        #[cfg(any(
            feature = "force_support_fallback",
            not(any(
                all(target_arch = "aarch64", target_feature = "neon"),
                all(
                    any(target_arch = "x86", target_arch = "x86_64"),
                    target_feature = "sse2",
                    target_feature = "fxsr"
                ),
                all(target_arch = "wasm32", target_feature = "simd128")
            ))
        ))]
        $item
    )*};
}

#[cfg(any(target_arch = "x86", target_arch = "x86_64"))]
mod avx2;
#[cfg(any(target_arch = "x86", target_arch = "x86_64"))]
mod avx512;
with_fallback! {
    mod fallback;
}
#[cfg(target_arch = "aarch64")]
mod neon;
mod ops;
pub(crate) mod simd_trait;
mod simd_types;
#[cfg(any(target_arch = "x86", target_arch = "x86_64"))]
mod sse2;
#[cfg(any(target_arch = "x86", target_arch = "x86_64"))]
mod sse4_2;
#[cfg(all(target_arch = "wasm32", target_feature = "simd128"))]
mod wasm;

#[cfg(any(target_arch = "x86", target_arch = "x86_64"))]
pub use avx2::*;
#[cfg(any(target_arch = "x86", target_arch = "x86_64"))]
pub use avx512::*;
with_fallback! {
    pub use fallback::*;
}
#[cfg(target_arch = "aarch64")]
pub use neon::*;
pub use simd_trait::*;
pub use simd_types::*;
#[cfg(any(target_arch = "x86", target_arch = "x86_64"))]
pub use sse2::*;
#[cfg(any(target_arch = "x86", target_arch = "x86_64"))]
pub use sse4_2::*;
#[cfg(all(target_arch = "wasm32", target_feature = "simd128"))]
pub use wasm::*;
