// Copyright 2025 the Fearless_SIMD Authors
// SPDX-License-Identifier: Apache-2.0 OR MIT

// This file is automatically generated by `fearless_simd_core_gen`.
// Its template can be found in `fearless_simd_core/gen/templates`.
//! The F16C target feature.

use crate::{TargetFeatureToken, trampoline};

use core::fmt::Debug;

/// [F16C] --- 16-bit floating point conversion instructions
///
/// [F16C]: https://en.wikipedia.org/wiki/F16C
///
/// A token indicating that the current CPU has the `f16c` target feature.
///
/// # Example
///
/// This can be used to [`trampoline!`] into functions like:
///
/// ```rust
/// #[cfg(any(target_arch = "x86", target_arch = "x86_64"))]
/// #[target_feature(enable = "f16c")]
/// fn uses_f16c() {
///     // ...
/// }
/// ```
#[derive(Copy, Clone, Hash, PartialEq, Eq)]
pub struct F16c {
    // We don't use non_exhaustive because we don't want this struct to be constructible.
    // in different modules in this crate.
    _private: (),
}

impl Debug for F16c {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, r#""f16c" enabled."#)
    }
}

// Safety: This token can only be constructed if you have proof that all the requisite
// target feature is enabled.
unsafe impl TargetFeatureToken for F16c {
    const FEATURES: &[&str] = &[
        "f16c", "avx", "sse", "sse2", "sse3", "sse4.1", "sse4.2", "ssse3",
    ];

    #[inline(always)]
    fn vectorize<R>(self, f: impl FnOnce() -> R) -> R {
        // Because we need the safety check to be eagerly evaluated, it uses an constant item.
        // This means we can't use `Self = self` here, unfortunately.
        trampoline!([F16c = self] => "f16c", <(R)> fn<(R)>(f: impl FnOnce() -> R = f) -> R { f() })
    }
}

impl F16c {
    #[cfg(feature = "std")]
    /// Create a new token if the `"f16c"` target feature is detected as enabled.
    ///
    /// This does not do any caching internally, although note that the standard
    /// library does internally cache the features it detects.
    // TODO: Consider a manual override feature/env var?
    pub fn try_new() -> Option<Self> {
        // Feature flag required to make docs compile.
        // TODO: Extract into a (private) crate::x86::is_x86_feature_detected?
        #[cfg(any(target_arch = "x86", target_arch = "x86_64"))]
        if std::arch::is_x86_feature_detected!("f16c") {
            // Safety: The required CPU feature was detected.
            unsafe { Some(Self::new()) }
        } else {
            None
        }
    }

    #[target_feature(enable = "f16c")]
    /// Create a new token for the "f16c" target feature.
    ///
    /// This method is useful to get a new token if you have an external proof that
    /// F16C is available. This could happen if you are in a target feature
    /// function called by an external library user.
    ///
    /// # Safety
    ///
    /// No conditions other than those inherited from the target feature attribute,
    /// i.e. that the "f16c" target feature is available.
    ///
    /// [implicitly enables]: https://doc.rust-lang.org/beta/reference/attributes/codegen.html?highlight=implicitly%20enabled#r-attributes.codegen.target_feature.safety-restrictions
    pub fn new() -> Self {
        Self { _private: () }
    }
}

impl From<F16c> for crate::x86::avx::Avx {
    fn from(value: F16c) -> Self {
        // This also serves as a correctness check of the implicitly enabled features.
        trampoline!([F16c = value] => "f16c", fn() -> crate::x86::avx::Avx { crate::x86::avx::Avx::new() })
    }
}

impl From<F16c> for crate::x86::sse::Sse {
    fn from(value: F16c) -> Self {
        // This also serves as a correctness check of the implicitly enabled features.
        trampoline!([F16c = value] => "f16c", fn() -> crate::x86::sse::Sse { crate::x86::sse::Sse::new() })
    }
}

impl From<F16c> for crate::x86::sse::Sse2 {
    fn from(value: F16c) -> Self {
        // This also serves as a correctness check of the implicitly enabled features.
        trampoline!([F16c = value] => "f16c", fn() -> crate::x86::sse::Sse2 { crate::x86::sse::Sse2::new() })
    }
}

impl From<F16c> for crate::x86::sse::Sse3 {
    fn from(value: F16c) -> Self {
        // This also serves as a correctness check of the implicitly enabled features.
        trampoline!([F16c = value] => "f16c", fn() -> crate::x86::sse::Sse3 { crate::x86::sse::Sse3::new() })
    }
}

impl From<F16c> for crate::x86::sse::Sse4_1 {
    fn from(value: F16c) -> Self {
        // This also serves as a correctness check of the implicitly enabled features.
        trampoline!([F16c = value] => "f16c", fn() -> crate::x86::sse::Sse4_1 { crate::x86::sse::Sse4_1::new() })
    }
}

impl From<F16c> for crate::x86::sse::Sse4_2 {
    fn from(value: F16c) -> Self {
        // This also serves as a correctness check of the implicitly enabled features.
        trampoline!([F16c = value] => "f16c", fn() -> crate::x86::sse::Sse4_2 { crate::x86::sse::Sse4_2::new() })
    }
}

impl From<F16c> for crate::x86::sse::SupplementalSse3 {
    fn from(value: F16c) -> Self {
        // This also serves as a correctness check of the implicitly enabled features.
        trampoline!([F16c = value] => "f16c", fn() -> crate::x86::sse::SupplementalSse3 { crate::x86::sse::SupplementalSse3::new() })
    }
}

const _: () = {
    assert!(
        core::mem::size_of::<F16c>() == 0,
        "Target feature tokens should be zero sized."
    );
};
