// This file is automatically generated by `fearless_simd_core_gen`.
// Its template can be found in `fearless_simd_core/gen/templates`.

//! The x86-64-v3 microarchitecture level.

use crate::{TargetFeatureToken, trampoline};

use core::fmt::Debug;

// TODO: Level specific docs?
/// A token indicating that the current CPU has the x86-64-v3 microarchitecture level.
///
/// For more details on the microarchitecture levels, see
/// <https://en.wikipedia.org/wiki/X86-64#Microarchitecture_levels>.
///
/// # Example
///
/// This can be used to [`trampoline!`] into functions like:
///
/// ```rust
/// #[cfg(any(target_arch = "x86", target_arch = "x86_64"))]
/// #[target_feature(enable = "avx2,bmi1,bmi2,cmpxchg16b,f16c,fma,fxsr,lzcnt,movbe,popcnt,xsave")]
/// fn uses_x86_64_v3() {
///     // ...
/// }
/// ```
///
/// This struct internally contains only the minimal features required to enable this level.
/// This is done to ensure that the fewest target features are checked.
/// However, it can be turned into any target feature it implies using the from impls.
#[derive(Copy, Clone, Hash, PartialEq, Eq)]
pub struct V3 {
    /// The contained proof that AVX2 is available.
    pub avx2: crate::x86::v3::Avx2,
    /// The contained proof that  1 is available.
    pub bmi1: crate::x86::v3::Bmi1,
    /// The contained proof that BMI2 is available.
    pub bmi2: crate::x86::v3::Bmi2,
    /// The contained proof that `cmpxchg16b` is available.
    pub cmpxchg16b: crate::x86::v3::Cmpxchg16b,
    /// The contained proof that F16C is available.
    pub f16c: crate::x86::v3::F16c,
    /// The contained proof that FMA3 is available.
    pub fma: crate::x86::v3::Fma,
    /// The contained proof that `fxsave + fxrstor` is available.
    pub fxsr: crate::x86::v3::Fxsr,
    /// The contained proof that `lzcnt` is available.
    pub lzcnt: crate::x86::v3::Lzcnt,
    /// The contained proof that `movbe` is available.
    pub movbe: crate::x86::v3::Movbe,
    /// The contained proof that `popcnt` is available.
    pub popcnt: crate::x86::v3::Popcnt,
    /// The contained proof that `xsave` is available.
    pub xsave: crate::x86::v3::Xsave,
    // This struct explicitly is not non_exhaustive, because it is
    // completely safe to construct from the fields.
}

impl Debug for V3 {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, r#"x86-64-v3 enabled."#)
    }
}

// Safety: This token can only be constructed if you have proofs that all the requisite
// target features are enabled.
unsafe impl TargetFeatureToken for V3 {
    const FEATURES: &[&str] = &[
        "avx",
        "avx2",
        "bmi1",
        "bmi2",
        "cmpxchg16b",
        "f16c",
        "fma",
        "fxsr",
        "lzcnt",
        "movbe",
        "popcnt",
        "sse",
        "sse2",
        "sse3",
        "sse4.1",
        "sse4.2",
        "ssse3",
        "xsave",
    ];

    #[inline(always)]
    fn vectorize<R>(self, f: impl FnOnce() -> R) -> R {
        // We use the explicitly written out form here as validation that the set of
        // features we've created correctly mapes to the target feature string.
        trampoline!([crate::x86::v3::Avx2 = self.avx2, crate::x86::v3::Bmi1 = self.bmi1, crate::x86::v3::Bmi2 = self.bmi2, crate::x86::v3::Cmpxchg16b = self.cmpxchg16b, crate::x86::v3::F16c = self.f16c, crate::x86::v3::Fma = self.fma, crate::x86::v3::Fxsr = self.fxsr, crate::x86::v3::Lzcnt = self.lzcnt, crate::x86::v3::Movbe = self.movbe, crate::x86::v3::Popcnt = self.popcnt, crate::x86::v3::Xsave = self.xsave] => "avx2,bmi1,bmi2,cmpxchg16b,f16c,fma,fxsr,lzcnt,movbe,popcnt,xsave", <(R)> fn<(R)>(f: impl FnOnce() -> R = f) -> R { f() })
    }
}

impl V3 {
    #[cfg(feature = "std")]
    /// Create a new token if the x86-64-v3 target feature is detected as enabled.
    ///
    /// This does not do any caching internally, although note that the standard
    /// library does internally cache the features it detects.
    // TODO: Consider a manual override feature/env var?
    pub fn try_new() -> Option<Self> {
        Some(Self {
            avx2: crate::x86::v3::Avx2::try_new()?,
            bmi1: crate::x86::v3::Bmi1::try_new()?,
            bmi2: crate::x86::v3::Bmi2::try_new()?,
            cmpxchg16b: crate::x86::v3::Cmpxchg16b::try_new()?,
            f16c: crate::x86::v3::F16c::try_new()?,
            fma: crate::x86::v3::Fma::try_new()?,
            fxsr: crate::x86::v3::Fxsr::try_new()?,
            lzcnt: crate::x86::v3::Lzcnt::try_new()?,
            movbe: crate::x86::v3::Movbe::try_new()?,
            popcnt: crate::x86::v3::Popcnt::try_new()?,
            xsave: crate::x86::v3::Xsave::try_new()?,
        })
    }

    #[target_feature(enable = "avx2,bmi1,bmi2,cmpxchg16b,f16c,fma,fxsr,lzcnt,movbe,popcnt,xsave")]
    /// Create a new token for the x86-64-v3 microarchitecture level.
    ///
    /// This method is useful to get a new token if you have an external proof that
    /// x86-64-v3 is available. This could happen if you are in a target feature
    /// function called by an external library user.
    ///
    /// # Safety
    ///
    /// No conditions other than those inherited from the target feature attribute,
    /// i.e. that the "avx2,bmi1,bmi2,cmpxchg16b,f16c,fma,fxsr,lzcnt,movbe,popcnt,xsave" target feature is available.
    pub fn new() -> Self {
        Self {
            avx2: crate::x86::v3::Avx2::new(),
            bmi1: crate::x86::v3::Bmi1::new(),
            bmi2: crate::x86::v3::Bmi2::new(),
            cmpxchg16b: crate::x86::v3::Cmpxchg16b::new(),
            f16c: crate::x86::v3::F16c::new(),
            fma: crate::x86::v3::Fma::new(),
            fxsr: crate::x86::v3::Fxsr::new(),
            lzcnt: crate::x86::v3::Lzcnt::new(),
            movbe: crate::x86::v3::Movbe::new(),
            popcnt: crate::x86::v3::Popcnt::new(),
            xsave: crate::x86::v3::Xsave::new(),
        }
    }
}
// TODO: From impls to convert into lower x86 versions.

impl From<V3> for crate::x86::v3::Avx {
    fn from(value: V3) -> Self {
        // This serves as a correctness check of the implicitly enabled features.
        trampoline!([V3 = value] => "avx2,bmi1,bmi2,cmpxchg16b,f16c,fma,fxsr,lzcnt,movbe,popcnt,xsave", fn() -> crate::x86::v3::Avx { crate::x86::v3::Avx::new() })
    }
}

impl From<V3> for crate::x86::v3::Avx2 {
    fn from(value: V3) -> Self {
        // This serves as a correctness check of the implicitly enabled features.
        trampoline!([V3 = value] => "avx2,bmi1,bmi2,cmpxchg16b,f16c,fma,fxsr,lzcnt,movbe,popcnt,xsave", fn() -> crate::x86::v3::Avx2 { crate::x86::v3::Avx2::new() })
    }
}

impl From<V3> for crate::x86::v3::Bmi1 {
    fn from(value: V3) -> Self {
        // This serves as a correctness check of the implicitly enabled features.
        trampoline!([V3 = value] => "avx2,bmi1,bmi2,cmpxchg16b,f16c,fma,fxsr,lzcnt,movbe,popcnt,xsave", fn() -> crate::x86::v3::Bmi1 { crate::x86::v3::Bmi1::new() })
    }
}

impl From<V3> for crate::x86::v3::Bmi2 {
    fn from(value: V3) -> Self {
        // This serves as a correctness check of the implicitly enabled features.
        trampoline!([V3 = value] => "avx2,bmi1,bmi2,cmpxchg16b,f16c,fma,fxsr,lzcnt,movbe,popcnt,xsave", fn() -> crate::x86::v3::Bmi2 { crate::x86::v3::Bmi2::new() })
    }
}

impl From<V3> for crate::x86::v3::Cmpxchg16b {
    fn from(value: V3) -> Self {
        // This serves as a correctness check of the implicitly enabled features.
        trampoline!([V3 = value] => "avx2,bmi1,bmi2,cmpxchg16b,f16c,fma,fxsr,lzcnt,movbe,popcnt,xsave", fn() -> crate::x86::v3::Cmpxchg16b { crate::x86::v3::Cmpxchg16b::new() })
    }
}

impl From<V3> for crate::x86::v3::F16c {
    fn from(value: V3) -> Self {
        // This serves as a correctness check of the implicitly enabled features.
        trampoline!([V3 = value] => "avx2,bmi1,bmi2,cmpxchg16b,f16c,fma,fxsr,lzcnt,movbe,popcnt,xsave", fn() -> crate::x86::v3::F16c { crate::x86::v3::F16c::new() })
    }
}

impl From<V3> for crate::x86::v3::Fma {
    fn from(value: V3) -> Self {
        // This serves as a correctness check of the implicitly enabled features.
        trampoline!([V3 = value] => "avx2,bmi1,bmi2,cmpxchg16b,f16c,fma,fxsr,lzcnt,movbe,popcnt,xsave", fn() -> crate::x86::v3::Fma { crate::x86::v3::Fma::new() })
    }
}

impl From<V3> for crate::x86::v3::Fxsr {
    fn from(value: V3) -> Self {
        // This serves as a correctness check of the implicitly enabled features.
        trampoline!([V3 = value] => "avx2,bmi1,bmi2,cmpxchg16b,f16c,fma,fxsr,lzcnt,movbe,popcnt,xsave", fn() -> crate::x86::v3::Fxsr { crate::x86::v3::Fxsr::new() })
    }
}

impl From<V3> for crate::x86::v3::Lzcnt {
    fn from(value: V3) -> Self {
        // This serves as a correctness check of the implicitly enabled features.
        trampoline!([V3 = value] => "avx2,bmi1,bmi2,cmpxchg16b,f16c,fma,fxsr,lzcnt,movbe,popcnt,xsave", fn() -> crate::x86::v3::Lzcnt { crate::x86::v3::Lzcnt::new() })
    }
}

impl From<V3> for crate::x86::v3::Movbe {
    fn from(value: V3) -> Self {
        // This serves as a correctness check of the implicitly enabled features.
        trampoline!([V3 = value] => "avx2,bmi1,bmi2,cmpxchg16b,f16c,fma,fxsr,lzcnt,movbe,popcnt,xsave", fn() -> crate::x86::v3::Movbe { crate::x86::v3::Movbe::new() })
    }
}

impl From<V3> for crate::x86::v3::Popcnt {
    fn from(value: V3) -> Self {
        // This serves as a correctness check of the implicitly enabled features.
        trampoline!([V3 = value] => "avx2,bmi1,bmi2,cmpxchg16b,f16c,fma,fxsr,lzcnt,movbe,popcnt,xsave", fn() -> crate::x86::v3::Popcnt { crate::x86::v3::Popcnt::new() })
    }
}

impl From<V3> for crate::x86::v3::Sse {
    fn from(value: V3) -> Self {
        // This serves as a correctness check of the implicitly enabled features.
        trampoline!([V3 = value] => "avx2,bmi1,bmi2,cmpxchg16b,f16c,fma,fxsr,lzcnt,movbe,popcnt,xsave", fn() -> crate::x86::v3::Sse { crate::x86::v3::Sse::new() })
    }
}

impl From<V3> for crate::x86::v3::Sse2 {
    fn from(value: V3) -> Self {
        // This serves as a correctness check of the implicitly enabled features.
        trampoline!([V3 = value] => "avx2,bmi1,bmi2,cmpxchg16b,f16c,fma,fxsr,lzcnt,movbe,popcnt,xsave", fn() -> crate::x86::v3::Sse2 { crate::x86::v3::Sse2::new() })
    }
}

impl From<V3> for crate::x86::v3::Sse3 {
    fn from(value: V3) -> Self {
        // This serves as a correctness check of the implicitly enabled features.
        trampoline!([V3 = value] => "avx2,bmi1,bmi2,cmpxchg16b,f16c,fma,fxsr,lzcnt,movbe,popcnt,xsave", fn() -> crate::x86::v3::Sse3 { crate::x86::v3::Sse3::new() })
    }
}

impl From<V3> for crate::x86::v3::Sse4_1 {
    fn from(value: V3) -> Self {
        // This serves as a correctness check of the implicitly enabled features.
        trampoline!([V3 = value] => "avx2,bmi1,bmi2,cmpxchg16b,f16c,fma,fxsr,lzcnt,movbe,popcnt,xsave", fn() -> crate::x86::v3::Sse4_1 { crate::x86::v3::Sse4_1::new() })
    }
}

impl From<V3> for crate::x86::v3::Sse4_2 {
    fn from(value: V3) -> Self {
        // This serves as a correctness check of the implicitly enabled features.
        trampoline!([V3 = value] => "avx2,bmi1,bmi2,cmpxchg16b,f16c,fma,fxsr,lzcnt,movbe,popcnt,xsave", fn() -> crate::x86::v3::Sse4_2 { crate::x86::v3::Sse4_2::new() })
    }
}

impl From<V3> for crate::x86::v3::SupplementalSse3 {
    fn from(value: V3) -> Self {
        // This serves as a correctness check of the implicitly enabled features.
        trampoline!([V3 = value] => "avx2,bmi1,bmi2,cmpxchg16b,f16c,fma,fxsr,lzcnt,movbe,popcnt,xsave", fn() -> crate::x86::v3::SupplementalSse3 { crate::x86::v3::SupplementalSse3::new() })
    }
}

impl From<V3> for crate::x86::v3::Xsave {
    fn from(value: V3) -> Self {
        // This serves as a correctness check of the implicitly enabled features.
        trampoline!([V3 = value] => "avx2,bmi1,bmi2,cmpxchg16b,f16c,fma,fxsr,lzcnt,movbe,popcnt,xsave", fn() -> crate::x86::v3::Xsave { crate::x86::v3::Xsave::new() })
    }
}

const _: () = {
    assert!(
        core::mem::size_of::<V3>() == 0,
        "Target feature tokens should be zero sized."
    );
};
