// Copyright 2025 the Fearless_SIMD Authors
// SPDX-License-Identifier: Apache-2.0 OR MIT

// This file is automatically generated by `fearless_simd_core_gen`.
// Its template can be found in `fearless_simd_core/gen/templates`.
//! The WIDE KEYLOCKER target feature.

use crate::{TargetFeatureToken, trampoline};

use core::fmt::Debug;

/// [KEYLOCKER_WIDE] --- Intel Wide Keylocker Instructions
///
/// [KEYLOCKER_WIDE]: https://en.wikipedia.org/wiki/List_of_x86_cryptographic_instructions#Intel_Key_Locker_instructions
///
/// A token indicating that the current CPU has the `widekl` target feature.
///
/// # Example
///
/// This can be used to [`trampoline!`] into functions like:
///
/// ```rust
/// #[cfg(any(target_arch = "x86", target_arch = "x86_64"))]
/// #[target_feature(enable = "widekl")]
/// fn uses_wide_keylocker() {
///     // ...
/// }
/// ```
#[derive(Copy, Clone, Hash, PartialEq, Eq)]
pub struct WideKeylocker {
    // We don't use non_exhaustive because we don't want this struct to be constructible.
    // in different modules in this crate.
    _private: (),
}

impl Debug for WideKeylocker {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, r#""widekl" enabled."#)
    }
}

// Safety: This token can only be constructed if you have proof that all the requisite
// target feature is enabled.
unsafe impl TargetFeatureToken for WideKeylocker {
    const FEATURES: &[&str] = &["widekl", "kl"];

    #[inline(always)]
    fn vectorize<R>(self, f: impl FnOnce() -> R) -> R {
        // Because we need the safety check to be eagerly evaluated, it uses an constant item.
        // This means we can't use `Self = self` here, unfortunately.
        trampoline!([WideKeylocker = self] => "widekl", <(R)> fn<(R)>(f: impl FnOnce() -> R = f) -> R { f() })
    }
}

impl WideKeylocker {
    #[cfg(feature = "std")]
    /// Create a new token if the `"widekl"` target feature is detected as enabled.
    ///
    /// This does not do any caching internally, although note that the standard
    /// library does internally cache the features it detects.
    // TODO: Consider a manual override feature/env var?
    pub fn try_new() -> Option<Self> {
        // Feature flag required to make docs compile.
        // TODO: Extract into a (private) crate::x86::is_x86_feature_detected?
        #[cfg(any(target_arch = "x86", target_arch = "x86_64"))]
        if std::arch::is_x86_feature_detected!("widekl") {
            // Safety: The required CPU feature was detected.
            unsafe { Some(Self::new()) }
        } else {
            None
        }
    }

    #[target_feature(enable = "widekl")]
    /// Create a new token for the "widekl" target feature.
    ///
    /// This method is useful to get a new token if you have an external proof that
    /// WIDE KEYLOCKER is available. This could happen if you are in a target feature
    /// function called by an external library user.
    ///
    /// # Safety
    ///
    /// No conditions other than those inherited from the target feature attribute,
    /// i.e. that the "widekl" target feature is available.
    ///
    /// [implicitly enables]: https://doc.rust-lang.org/beta/reference/attributes/codegen.html?highlight=implicitly%20enabled#r-attributes.codegen.target_feature.safety-restrictions
    pub fn new() -> Self {
        Self { _private: () }
    }
}

impl From<WideKeylocker> for crate::x86::crypto::Keylocker {
    fn from(value: WideKeylocker) -> Self {
        // This also serves as a correctness check of the implicitly enabled features.
        trampoline!([WideKeylocker = value] => "widekl", fn() -> crate::x86::crypto::Keylocker { crate::x86::crypto::Keylocker::new() })
    }
}

const _: () = {
    assert!(
        core::mem::size_of::<WideKeylocker>() == 0,
        "Target feature tokens should be zero sized."
    );
};
