//! Expanded test suite generated by Claude Code based on mod.rs
//! 
//! In the future we might want to add a more rigorous automatic generation
//! of test cases for various vector sizes, but this is a simple first step
//! towards increased test coverage.